//! Stateful prefix evaluator. Future bars are neither indexed nor read by a decision.
use super::exact::n;
use super::{exact::{D,d,div,div_at,floor_ratio,sqrt,ln_ratio,tanh,text},quant::{Parameters,QuantBar,HistorySemantics,Signal,IndicatorPoint,strategy_catalog},structure::{atr,price_structure_cached,smart_events_cached,TrendState}};
use anyhow::{Result,ensure};
use num_traits::{Zero,One,ToPrimitive};
use serde_json::{Value,json};
use std::collections::BTreeMap;
use serde::{Serialize,Deserialize};

fn sign(value:&D)->i8{if value>&D::zero(){1}else if value<&D::zero(){-1}else{0}}
fn clamp(value:D,low:&str,high:&str)->D{value.max(d(low)).min(d(high))}
fn average(values:&[D])->Option<D>{if values.is_empty(){None}else{Some(div(&values.iter().cloned().sum::<D>(),&n(values.len())))}}
fn deviation(values:&[D])->Option<D>{super::exact::population_deviation(&values.iter().cloned().sum::<D>(),&values.iter().map(|v|v*v).sum::<D>(),values.len())}
fn ratio(a:&D,b:&D)->Option<D>{if b.is_zero(){None}else{Some(div(a,b))}}

#[derive(Clone,Debug,Serialize,Deserialize)]
struct Recurrence {macd:D,histogram:D,k:D,kd:D,j:D,zone:String,dulling:String,cross:String,streak:usize,rsi:Option<D>,rsi_direction:i8,rsi_state:String,rsi_signal:String,nine_direction:i8,nine_streak:usize,nine_perfected:bool}
#[derive(Clone,Debug,Serialize,Deserialize)]
pub struct Evaluator{
    pub parameters:Parameters,pub bars:Vec<QuantBar>,trend_state:TrendState,recurrences:Vec<Recurrence>,
    #[serde(skip)]pub timings:BTreeMap<String,u64>,
    fast:Option<D>,slow:Option<D>,signal:D,k:D,kd:D,
    previous_k:Option<D>,previous_d:Option<D>,zone:String,zone_streak:usize,
    average_gain:Option<D>,average_loss:Option<D>,previous_rsi:Option<D>,
    atr14:Vec<D>,tr_sums:Vec<D>,log_returns:Vec<Option<D>>,bollinger_widths:Vec<Option<D>>,width_ready:Vec<bool>,close_sums:Vec<D>,
    retained_limit:usize,prefix_before_start:D,pub processed_bars:usize,nine_direction:i8,nine_streak:usize,nine_perfected:bool,
}
impl Evaluator{
    #[cfg(test)] pub fn retain_all_for_oracle(&mut self){self.retained_limit=usize::MAX/4;}
    pub fn snapshot(&self)->Result<Value>{Ok(json!({"calculation_version":super::quant::CALCULATION_VERSION,"parameters_hash":super::quant::content_hash(&self.parameters)?,"state":self}))}
    pub fn restore(value:Value,parameters:&Parameters)->Result<Self>{parameters.validate()?;ensure!(value["calculation_version"]==super::quant::CALCULATION_VERSION,"evaluator checkpoint version mismatch");ensure!(value["parameters_hash"]==super::quant::content_hash(parameters)?,"evaluator checkpoint parameter mismatch");let restored:Self=serde_json::from_value(value["state"].clone())?;ensure!(restored.parameters==*parameters,"evaluator checkpoint parameters differ");ensure!(restored.bars.len()<=restored.retained_limit*2&&restored.recurrences.len()==restored.bars.len()&&restored.close_sums.len()==restored.bars.len()&&restored.log_returns.len()==restored.bars.len()&&restored.bollinger_widths.len()==restored.bars.len()&&restored.width_ready.len()==restored.bars.len()&&restored.atr14.len()==restored.bars.len()&&restored.tr_sums.len()==restored.bars.len(),"invalid bounded evaluator checkpoint");for bar in &restored.bars{bar.validate()?;}Ok(restored)}

    pub fn new(parameters:Parameters)->Result<Self>{parameters.validate()?;let retained_limit=512.max(parameters.macd_slow+2).max(parameters.macd_signal+2).max(parameters.ma_periods.last().unwrap()+parameters.ma_slope_bars+2).max(parameters.momentum_horizons.last().unwrap()+2).max(parameters.poc_bars+2).max(parameters.pattern.lookback_bars+parameters.pattern.pivot_radius+2).max(parameters.bollinger_rank_bars+parameters.bollinger_period+2).max(parameters.flow_bars+2).max(parameters.volume_price_bars+2).max(parameters.fvg_bars+2).max(parameters.volatility_period+2).max(parameters.rsi_period+2).max(parameters.kdj_period+2).max(parameters.slope_bars+2).max(parameters.atr_period+2);
        Ok(Self{parameters,bars:vec![],recurrences:vec![],trend_state:TrendState::default(),timings:BTreeMap::new(),fast:None,slow:None,signal:D::zero(),k:d("50"),kd:d("50"),previous_k:None,previous_d:None,zone:"middle".into(),zone_streak:0,average_gain:None,average_loss:None,previous_rsi:None,atr14:vec![],tr_sums:vec![],log_returns:vec![],bollinger_widths:vec![],width_ready:vec![],close_sums:vec![],retained_limit,prefix_before_start:D::zero(),processed_bars:0,nine_direction:0,nine_streak:0,nine_perfected:false})}
    pub fn push(&mut self,bar:QuantBar,semantics:&HistorySemantics)->Result<IndicatorPoint>{self.push_mode(bar,semantics,true,true)}
    /// Keeps every recurrence/window update; expensive nonrecursive context is
    /// materialized only at a batch's last confirmed point by the accumulator.
    pub fn push_state(&mut self,bar:QuantBar,semantics:&HistorySemantics)->Result<IndicatorPoint>{self.push_mode(bar,semantics,false,true)}
    /// Context-only strategies cannot affect a fill. Trading still computes all
    /// eligible directions at every bar; complete UI snapshots use push().
    pub fn push_execution(&mut self,bar:QuantBar,semantics:&HistorySemantics)->Result<IndicatorPoint>{self.push_mode(bar,semantics,true,false)}
    pub fn advance(&mut self,bar:QuantBar,semantics:&HistorySemantics)->Result<()>{
        if self.bars.len()>=self.retained_limit*2{let drop=self.bars.len()-self.retained_limit;self.prefix_before_start=self.close_sums[drop-1].clone();self.bars.drain(..drop);self.recurrences.drain(..drop);self.close_sums.drain(..drop);self.log_returns.drain(..drop);self.bollinger_widths.drain(..drop);self.width_ready.drain(..drop);self.atr14.drain(..drop);self.tr_sums.drain(..drop);}
        self.timings.clear();let clock=std::time::Instant::now();
        bar.validate()?;ensure!(bar.state=="final"&&(semantics==&HistorySemantics::FinalRevisionHistory||bar.finalized_at.is_some()),"confirmed evaluator only accepts final bars");
        ensure!(self.bars.last().is_none_or(|last|bar.open_time>last.open_time),"evaluator requires strictly ordered bars");
        self.bars.push(bar);self.processed_bars+=1;let i=self.bars.len()-1;let latest=&self.bars[i];let close=latest.close.clone();let p=&self.parameters;
        self.close_sums.push(self.close_sums.last().cloned().unwrap_or_default()+&close);
        let tr=if i==0{&latest.high-&latest.low}else{(&latest.high-&latest.low).max((&latest.high-&self.bars[i-1].close).abs()).max((&latest.low-&self.bars[i-1].close).abs())};self.tr_sums.push(self.tr_sums.last().cloned().unwrap_or_default()+tr);let sum=&self.tr_sums[i]-if i>=14{self.tr_sums[i-14].clone()}else{D::zero()};self.atr14.push(div(&sum,&n(self.processed_bars.min(14))));
        let ema=|previous:&Option<D>,period:usize|previous.as_ref().map_or_else(||close.clone(),|old|div(&(&close*2+old*n(period-1)),&n(period+1)));
        self.fast=Some(ema(&self.fast,p.macd_fast));self.slow=Some(ema(&self.slow,p.macd_slow));
        let macd=self.fast.as_ref().unwrap()-self.slow.as_ref().unwrap();self.signal=if i==0{macd.clone()}else{div(&(&macd*2+&self.signal*n(p.macd_signal-1)),&n(p.macd_signal+1))};let histogram=&macd-&self.signal;
        let k_window=&self.bars[(i+1).saturating_sub(p.kdj_period)..=i];let low=k_window.iter().map(|b|b.low.clone()).min().unwrap();let high=k_window.iter().map(|b|b.high.clone()).max().unwrap();
        let rsv=if high==low{d("50")}else{div(&((&close-&low)*100),&(&high-&low))};self.k=div(&(&self.k*2+rsv),&d("3"));self.kd=div(&(&self.kd*2+&self.k),&d("3"));let j=&self.k*3-&self.kd*2;
        let cross=if self.previous_k.as_ref().zip(self.previous_d.as_ref()).is_some_and(|(k,d)|k<=d&&self.k>self.kd){"bullish"}else if self.previous_k.as_ref().zip(self.previous_d.as_ref()).is_some_and(|(k,d)|k>=d&&self.k<self.kd){"bearish"}else{"none"};
        let zone=if self.k>=p.kdj_upper&&self.kd>=p.kdj_upper{"high"}else if self.k<=p.kdj_lower&&self.kd<=p.kdj_lower{"low"}else{"middle"};
        let dulling=if zone!="middle"{format!("{zone}-{}",if self.zone==zone&&self.zone_streak+1>=p.kdj_dulling_bars{"dulling"}else{"entering"})}else if self.zone=="high"&&self.zone_streak>=p.kdj_dulling_bars&&cross=="bearish"{"high-releasing".into()}else if self.zone=="low"&&self.zone_streak>=p.kdj_dulling_bars&&cross=="bullish"{"low-releasing".into()}else{"normal".into()};
        self.zone_streak=if zone=="middle"{0}else if zone==self.zone{self.zone_streak+1}else{1};self.zone=zone.into();self.previous_k=Some(self.k.clone());self.previous_d=Some(self.kd.clone());
        let mut rsi=None;let mut rsi_direction=0;let mut rsi_state="warming";let mut rsi_signal="none";
        if i>=p.rsi_period{let delta=&close-&self.bars[i-1].close;let gain=delta.clone().max(D::zero());let loss=(-delta).max(D::zero());
            let(gain,loss)=if i==p.rsi_period{let changes:Vec<_>=(1..=i).map(|n|&self.bars[n].close-&self.bars[n-1].close).collect();(div(&changes.iter().map(|v|v.clone().max(D::zero())).sum::<D>(),&n(p.rsi_period)),div(&changes.iter().map(|v|(-v).max(D::zero())).sum::<D>(),&n(p.rsi_period)))}else{(div(&(self.average_gain.as_ref().unwrap()*n(p.rsi_period-1)+gain),&n(p.rsi_period)),div(&(self.average_loss.as_ref().unwrap()*n(p.rsi_period-1)+loss),&n(p.rsi_period)))};
            let value=if gain.is_zero()&&loss.is_zero(){d("50")}else if loss.is_zero(){d("100")}else if gain.is_zero(){D::zero()}else{d("100")-div(&d("100"),&(D::one()+div(&gain,&loss)))};
            rsi_state=if value<=p.rsi_lower{"oversold"}else if value>=p.rsi_upper{"overbought"}else{"neutral"};
            if self.previous_rsi.as_ref().is_some_and(|previous|previous<=&p.rsi_lower)&&value>p.rsi_lower{rsi_direction=1;rsi_signal="oversold-recovery";}else if self.previous_rsi.as_ref().is_some_and(|previous|previous>=&p.rsi_upper)&&value<p.rsi_upper{rsi_direction=-1;rsi_signal="overbought-reversal";}
            self.average_gain=Some(gain);self.average_loss=Some(loss);self.previous_rsi=Some(value.clone());rsi=Some(value);}
        self.log_returns.push(None);self.bollinger_widths.push(None);self.width_ready.push(false);
        let comparison=if i>=4{sign(&(&close-&self.bars[i-4].close))}else{0};self.nine_streak=if comparison==0{0}else if comparison==self.nine_direction{self.nine_streak.saturating_add(1)}else{1};if comparison!=self.nine_direction{self.nine_perfected=false;}self.nine_direction=comparison;
        if self.nine_streak==9&&i>=3{self.nine_perfected=if comparison>0{self.bars[i].high.clone().max(self.bars[i-1].high.clone())>=self.bars[i-2].high.clone().max(self.bars[i-3].high.clone())}else{self.bars[i].low.clone().min(self.bars[i-1].low.clone())<=self.bars[i-2].low.clone().min(self.bars[i-3].low.clone())};}
        self.recurrences.push(Recurrence{macd,histogram,k:self.k.clone(),kd:self.kd.clone(),j,zone:zone.into(),dulling,cross:cross.into(),streak:self.zone_streak,rsi,rsi_direction,rsi_state:rsi_state.into(),rsi_signal:rsi_signal.into(),nine_direction:self.nine_direction,nine_streak:self.nine_streak,nine_perfected:self.nine_perfected});
        if p.enabled_strategies.contains("auto-trend"){self.trend_state.advance(&self.bars,i,&self.atr14,self.processed_bars-self.bars.len());}
        self.timings.insert("recurrence".into(),clock.elapsed().as_micros() as u64);Ok(())
    }
    /// Preserve the scalar display prefix without building historical JSON or signals.
    pub fn advance_snapshot(&mut self,bar:QuantBar,semantics:&HistorySemantics)->Result<()>{self.retained_limit=self.retained_limit.max(1024+self.required_window());self.advance(bar,semantics)}
    fn required_window(&self)->usize{let p=&self.parameters;(*p.ma_periods.last().unwrap()+p.ma_slope_bars+2).max(p.bollinger_rank_bars+p.bollinger_period+2).max(p.volatility_period+2).max(p.kdj_period+2).max(p.atr_period+2).max(p.pattern.lookback_bars+p.pattern.pivot_radius+2)}
    pub fn current_point(&mut self,semantics:&HistorySemantics)->Result<Option<IndicatorPoint>>{if self.bars.is_empty(){Ok(None)}else{self.render(self.bars.len()-1,semantics,true,true,false).map(Some)}}
    pub fn chart_points_after(&mut self,semantics:&HistorySemantics,after:Option<chrono::DateTime<chrono::Utc>>)->Result<Vec<super::snapshot::ChartIndicatorPoint>>{(self.bars.len().saturating_sub(1024)..self.bars.len()).filter(|&i|after.is_none_or(|at|self.bars[i].open_time>at)).collect::<Vec<_>>().into_iter().map(|i|self.render(i,semantics,false,false,true).map(|p|super::snapshot::ChartIndicatorPoint::from(&p))).collect()}
    fn push_mode(&mut self,bar:QuantBar,semantics:&HistorySemantics,derive_windows:bool,derive_context:bool)->Result<IndicatorPoint>{self.advance(bar,semantics)?;self.render(self.bars.len()-1,semantics,derive_windows,derive_context,false)}
    fn prepare_log_returns(&mut self,i:usize){for at in (i+1).saturating_sub(self.parameters.volatility_period)..=i{if self.log_returns[at].is_none()&&at>0&&self.bars[at].close>D::zero()&&self.bars[at-1].close>D::zero(){self.log_returns[at]=ln_ratio(&self.bars[at].close,&self.bars[at-1].close);}}}
    fn prepare_widths(&mut self,i:usize){let start=(i+1).saturating_sub(self.parameters.bollinger_rank_bars).saturating_sub(1);for at in start..=i{if !self.width_ready[at]{self.bollinger_widths[at]=self.bandwidth(at);self.width_ready[at]=true;}}}
    fn bandwidth(&self,i:usize)->Option<D>{let period=self.parameters.bollinger_period;if i+1<period{return None;}let closes:Vec<_>=self.bars[i+1-period..=i].iter().map(|b|b.close.clone()).collect();let middle=average(&closes)?;if middle.is_zero(){None}else{let dev=deviation(&closes)?;let upper=&middle+&dev*&self.parameters.bollinger_deviations;let lower=&middle-&dev*&self.parameters.bollinger_deviations;Some(div(&(upper-lower),&middle.abs()))}}
    fn render(&mut self,i:usize,semantics:&HistorySemantics,derive_windows:bool,derive_context:bool,chart_only:bool)->Result<IndicatorPoint>{
        let clock=std::time::Instant::now();self.prepare_widths(i);if !chart_only{self.prepare_log_returns(i);}let latest=&self.bars[i];let close=latest.close.clone();let p=&self.parameters;let processed_bars=self.processed_bars-self.bars.len()+i+1;let r=&self.recurrences[i];
        let macd=r.macd.clone();let histogram=r.histogram.clone();let zone=r.zone.as_str();let dulling=r.dulling.as_str();let cross=r.cross.as_str();let j=r.j.clone();let rsi=r.rsi.clone();let rsi_direction=r.rsi_direction;let rsi_state=r.rsi_state.as_str();let rsi_signal=r.rsi_signal.as_str();
        let mut values=BTreeMap::new();let mut signals=vec![];
        let signal=|id:&str,direction:i8,confidence:D,state:&str,title:&str,evidence:Vec<String>|{let qualification=strategy_catalog().into_iter().find(|item|item.id==id).unwrap();Signal{strategy_id:id.into(),direction:if direction>0{"bullish"}else if direction<0{"bearish"}else{"neutral"}.into(),confidence,as_of:latest.open_time,state:state.into(),title:title.into(),evidence,composite_eligible:qualification.composite_eligible,backtest_eligible:qualification.backtest_eligible}};
        let mut add=|id:&str,direction:i8,confidence:D,state:&str,title:&str,evidence:Vec<String>|{if p.enabled_strategies.contains(id){signals.push(signal(id,direction,confidence,state,title,evidence));}};
        values.insert("macd".into(),if processed_bars>=p.macd_slow{json!({"value":text(&macd),"signal":text(&(&macd-&histogram)),"histogram":text(&histogram)})}else{Value::Null});
        add("macd",sign(&histogram),if processed_bars>=p.macd_slow{clamp(d("0.56")+div(&histogram.abs(),&close.clone().max(D::one()))*60,"0.56","0.82")}else{D::zero()},if processed_bars>=p.macd_slow{"ready"}else{"warming"},"MACD 动量",vec![]);
        let k_eligible=zone=="middle";let k_direction=if !k_eligible{0}else if dulling=="high-releasing"{-1}else if dulling=="low-releasing"{1}else{sign(&(&r.k-&r.kd))};
        values.insert("kdj".into(),if i+1>=p.kdj_period{json!({"k":text(&r.k),"d":text(&r.kd),"j":text(&j),"zone":zone,"dulling":dulling,"streak":r.streak,"cross":cross,"score_eligible":k_eligible})}else{Value::Null});
        add("kdj",k_direction,if i+1<p.kdj_period||!k_eligible{D::zero()}else if dulling.ends_with("releasing"){d("0.52")}else{d("0.56")},if i+1>=p.kdj_period{"ready"}else{"warming"},"KDJ 摆动与钝化",vec!["极值钝化不独自产生逆势方向".into()]);
        values.insert("rsi".into(),rsi.as_ref().map_or(Value::Null,|v|json!({"period":p.rsi_period,"value":text(v),"state":rsi_state,"signal":rsi_signal})));
        add("rsi",rsi_direction,if rsi_direction==0{D::zero()}else{d("0.54")},if rsi.is_some(){"ready"}else{"warming"},"Wilder RSI",vec![]);
        let sma=|index:usize,period:usize|->Option<D>{if index+1<period{None}else{Some(div(&(&self.close_sums[index]-if index>=period{self.close_sums[index-period].clone()}else{self.prefix_before_start.clone()}),&n(period)))}};
        let volatility=atr(&self.bars,i,p.atr_period,false).unwrap_or_else(||close.abs()*d("0.005"));let mut ma_values=vec![];let mut ma_available=vec![];let mut interaction_direction=0;
        for (position,&period)in p.ma_periods.iter().enumerate(){let value=sma(i,period);let slope=value.as_ref().zip(i.checked_sub(p.ma_slope_bars).and_then(|n|sma(n,period)).as_ref()).and_then(|(value,anchor)|ratio(value,anchor)).map(|r|div(&((r-1)*100),&n(p.ma_slope_bars)));
            let distance=value.as_ref().and_then(|v|ratio(&(&close-v),&volatility));let mut interaction="none";
            if let Some(v)=&value{let buffer=&volatility*if period>=120{d("0.38")}else{d("0.28")};let previous=i.checked_sub(1).and_then(|n|sma(n,period));
                if i>0&&previous.as_ref().is_some_and(|old|(self.bars[i-1].close>=*old&&close<v-&buffer)||(self.bars[i-1].close<=*old&&close>v+&buffer)){interaction="break";}else if close>=*v&&latest.low<=v+&buffer{interaction="support-test";}else if close<=*v&&latest.high>=v-&buffer{interaction="resistance-test";}
                ma_available.push((v.clone(),slope.clone()));if interaction_direction==0&&(position==1||position==3){interaction_direction=match interaction{"support-test"=>1,"resistance-test"=>-1,"break"=>sign(&(&close-v)),_=>0};}}
            ma_values.push(json!({"period":period,"value":value.as_ref().map(text),"slope_percent":slope.as_ref().map(text),"distance_atr":distance.as_ref().map(text),"interaction":interaction}));}
        let alignment=if ma_available.len()<2{"insufficient"}else if close>ma_available[0].0&&ma_available.windows(2).all(|v|v[0].0>v[1].0)&&ma_available.iter().all(|(_,s)|s.as_ref().is_none_or(|v|v>=&D::zero())){"bullish"}else if close<ma_available[0].0&&ma_available.windows(2).all(|v|v[0].0<v[1].0)&&ma_available.iter().all(|(_,s)|s.as_ref().is_none_or(|v|v<=&D::zero())){"bearish"}else{"mixed"};
        values.insert("moving_average".into(),if i+1>=p.ma_periods[0]{json!({"alignment":alignment,"values":ma_values})}else{Value::Null});
        add("ma-structure",if interaction_direction!=0{interaction_direction}else if alignment=="bullish"{1}else if alignment=="bearish"{-1}else{0},if alignment=="insufficient"{D::zero()}else{clamp(d("0.52")+n(ma_available.len())*d("0.045"),"0.52","0.72")},if alignment=="insufficient"{"warming"}else{"ready"},"MA 均线结构",vec![]);
        let mut bb_direction=0;let mut bb=None;
        if i+1>=p.bollinger_period{let closes:Vec<_>=self.bars[i+1-p.bollinger_period..=i].iter().map(|b|b.close.clone()).collect();let middle=average(&closes).unwrap();let dev=deviation(&closes).unwrap();
            if !middle.is_zero(){let half=(&dev*&p.bollinger_deviations).max(d("0.0000000000000002220446049250313"));let upper=&middle+&dev*&p.bollinger_deviations;let lower=&middle-&dev*&p.bollinger_deviations;let bandwidth=div(&(&upper-&lower),&middle.abs());let position=div(&(&close-&middle),&half);
                let mut ranks:Vec<_>=self.bollinger_widths[(i+1).saturating_sub(p.bollinger_rank_bars)..i].iter().flatten().cloned().collect();ranks.push(bandwidth.clone());let percentile=if ranks.len()<20{None}else{Some(div(&n(ranks.iter().filter(|v|**v<=bandwidth).count()),&n(ranks.len())))};
                let expanding=i.checked_sub(1).and_then(|at|self.bollinger_widths[at].as_ref()).is_some_and(|old|bandwidth>old*d("1.04"));let state=if percentile.as_ref().is_some_and(|rank|rank<=&d("0.2")){"squeeze"}else if expanding&&percentile.clone().unwrap_or_else(||d("0.5"))>=d("0.45"){"expanding"}else{"normal"};
                if state=="expanding"{bb_direction=if position>d("1"){1}else if position<d("-1"){-1}else{0};}
                bb=Some(json!({"middle":text(&middle),"upper":text(&upper),"lower":text(&lower),"bandwidth":text(&bandwidth),"bandwidth_percentile":percentile.as_ref().map(text),"position":text(&position),"state":state}));}}
        values.insert("bollinger".into(),bb.unwrap_or(Value::Null));add("bollinger",bb_direction,if bb_direction==0{D::zero()}else{d("0.61")},if i+1<p.bollinger_period{"warming"}else if values["bollinger"].is_null(){"unavailable"}else{"ready"},"布林波动结构",if values["bollinger"].is_null()&&i+1>=p.bollinger_period{vec!["中轨为零，带宽比例不可定义".into()]}else{vec![]});
        if chart_only{return Ok(IndicatorPoint{as_of:latest.open_time,decision_at:latest.known_at(semantics),indicators:values,signals:vec![],composite_score:D::zero(),direction:0});}
        let comparison=r.nine_direction;
        let setup_direction=if comparison>0{"sell-setup"}else if comparison<0{"buy-setup"}else{"none"};let count=r.nine_streak.min(9);let perfected=r.nine_perfected;
        values.insert("nine_count".into(),if i>=4{json!({"direction":setup_direction,"count":count,"perfected":perfected,"completed_now":r.nine_streak==9})}else{Value::Null});add("nine-count",0,D::zero(),if i>=4{"context"}else{"warming"},"九转 Setup 9",vec![format!("{setup_direction} {count}/9；perfected={perfected}；不包含 Countdown 13")]);
        let mut momentum=None;let mut momentum_direction=0;let mut momentum_confidence=D::zero();let mut unavailable_reason=None;
        if i>=p.momentum_horizons[0]{if self.bars[(i+1).saturating_sub(p.volatility_period+1)..=i].iter().any(|b|b.close<=D::zero()){unavailable_reason=Some("非正价格，对数收益不可定义");}else{let sample:Vec<_>=self.log_returns[(i+1).saturating_sub(p.volatility_period)..=i].iter().cloned().collect();let vol=if sample.len()==p.volatility_period&&sample.iter().all(Option::is_some){deviation(&sample.into_iter().flatten().collect::<Vec<_>>()).unwrap()}else{D::zero()};
                let(mut score,mut weight,mut positive,mut negative)=(D::zero(),D::zero(),0,0);let mut returns=vec![];for(horizon,w)in p.momentum_horizons.iter().zip(&p.momentum_weights){let raw:Option<D>=i.checked_sub(*horizon).and_then(|n|if self.bars[n].close>D::zero(){Some(div(&close,&self.bars[n].close)-1)}else{None});if let Some(raw)=&raw{positive+=usize::from(raw>&D::zero());negative+=usize::from(raw<&D::zero());let scale=if vol>D::zero(){&vol*sqrt(&n(*horizon)).unwrap()}else{raw.abs().max(d("0.01"))};score+=tanh(&div(raw,&scale.max(d("0.0001"))))*w;weight+=w;}returns.push(json!({"horizon":horizon,"percent":raw.as_ref().map(|v|text(&(v*100)))}));}
                let available=positive+negative+returns.iter().filter(|v|v["percent"]=="0").count();if weight>D::zero(){score=div(&score,&weight);}if positive>=2&&score>d("0.15"){momentum_direction=1;}else if negative>=2&&score<d("-0.15"){momentum_direction=-1;}if momentum_direction!=0{momentum_confidence=clamp(d("0.5")+score.abs()*d("0.22"),"0.5","0.72");}momentum=Some(json!({"score":text(&score),"available_horizons":available,"returns":returns}));}}
        values.insert("momentum".into(),momentum.unwrap_or(Value::Null));add("momentum-ensemble",momentum_direction,momentum_confidence,if unavailable_reason.is_some(){"unavailable"}else if i<p.momentum_horizons[0]{"warming"}else{"ready"},"多尺度趋势动量",unavailable_reason.map(|v|vec![v.into()]).unwrap_or_default());
        let window=&self.bars[(i+1).saturating_sub(p.slope_bars)..=i];let slope=if window.len()<4{None}else{let mean_x=div(&n(window.len()-1),&d("2"));let mean_y=div(&window.iter().map(|b|b.close.clone()).sum::<D>(),&n(window.len()));let mut numerator=D::zero();let mut denominator=D::zero();for(index,b)in window.iter().enumerate(){let x=n(index)-&mean_x;numerator+=&x*(&b.close-&mean_y);denominator+=&x*&x;}if mean_y.is_zero(){None}else{Some(div(&div(&numerator,&denominator),&mean_y)*100)}};
        values.insert("trend_slope_percent".into(),slope.as_ref().map_or(Value::Null,|v|json!(text(v))));
        self.timings.insert("numerical".into(),clock.elapsed().as_micros() as u64);let stage=std::time::Instant::now();
        if derive_windows{
        if p.enabled_strategies.contains("structure"){let structure=price_structure_cached(&self.bars,i,&p.pattern,&self.atr14);let patterns:Vec<_>=structure.patterns.iter().filter(|v|v.status=="confirmed"&&v.detected_at==latest.open_time).collect();let conflict=patterns.iter().any(|v|v.direction=="bullish")&&patterns.iter().any(|v|v.direction=="bearish");let strongest=patterns.iter().max_by(|a,b|a.confidence.cmp(&b.confidence).then_with(||b.id.cmp(&a.id)));
            let direction=if conflict{0}else if let Some(v)=strongest{if v.direction=="bullish"{1}else{-1}}else{slope.as_ref().map_or(0,|v|if v>&p.slope_threshold{1}else if v<&(-&p.slope_threshold){-1}else{0})};let confidence=if conflict{D::zero()}else if let Some(v)=strongest{v.confidence.clone()}else if let Some(v)=&slope{clamp(d("0.56")+v.abs()*5,"0.56","0.82")}else{D::zero()};
            add("structure",direction,confidence,if slope.is_none()&&strongest.is_none(){"warming"}else{"ready"},if conflict{"同柱结构方向冲突"}else{"已确认价格结构"},vec!["摆动点需右侧完成；新确认 W/M/2B 优先于斜率".into()]);values.insert("structure".into(),serde_json::to_value(structure)?);}
        self.timings.insert("structure".into(),stage.elapsed().as_micros() as u64);let stage=std::time::Instant::now();
        let mut zones=vec![];for n in 2.max(i.saturating_sub(p.fvg_bars-1))..=i{let first=&self.bars[n-2];let third=&self.bars[n];if third.low>first.high{zones.push(json!({"start":first.open_time,"end":latest.open_time,"low":text(&first.high),"high":text(&third.low),"direction":"bullish","formed_at":third.open_time}));}else if third.high<first.low{zones.push(json!({"start":first.open_time,"end":latest.open_time,"low":text(&third.high),"high":text(&first.low),"direction":"bearish","formed_at":third.open_time}));}}
        if zones.len()>4{zones.drain(..zones.len()-4);}let zone_direction=zones.last().map_or(0,|v|if v["direction"]=="bullish"{1}else{-1});add("fair-value",zone_direction,if zones.is_empty(){D::zero()}else{d("0.57")},if i<2{"warming"}else{"ready"},"三柱公允价值缺口",vec!["沿用既有版本：保留扫描窗口最后四个缺口，不声明已跟踪回补失效".into()]);values.insert("value_zones".into(),json!(zones));
        let window=&self.bars[(i+1).saturating_sub(p.poc_bars)..=i];let minimum=window.iter().map(|b|b.low.clone()).min().unwrap();let maximum=window.iter().map(|b|b.high.clone()).max().unwrap();let unknown=window.iter().filter(|b|b.volume.is_none()).count();let unit_weight=window.iter().filter(|b|b.volume.as_ref().is_none_or(|v|v<=&D::zero())).count();
        let poc=if maximum<=minimum{close.clone()}else{let range=&maximum-&minimum;let center_scale=window.iter().flat_map(|b|[b.low.as_bigint_and_exponent().1,b.high.as_bigint_and_exponent().1,b.volume.as_ref().map_or(0,|v|v.as_bigint_and_exponent().1)]).max().unwrap_or(0).max(28)+16;
        let mut weights=vec![D::zero();p.poc_bins];for b in window{let first=floor_ratio(&((&b.low-&minimum)*n(p.poc_bins)),&range).to_usize().unwrap_or_default().min(p.poc_bins-1);let last=floor_ratio(&((&b.high-&minimum)*n(p.poc_bins)),&range).to_usize().unwrap_or_default().min(p.poc_bins-1);let weight=div_at(&b.volume.as_ref().filter(|v|*v>&D::zero()).cloned().unwrap_or_else(D::one),&n(last-first+1),center_scale);for value in &mut weights[first..=last]{*value+=&weight;}}
        let best=weights.iter().enumerate().max_by(|(ia,a),(ib,b)|a.cmp(b).then_with(||ib.cmp(ia))).unwrap().0;&minimum+div_at(&(range*n(best*2+1)),&n(p.poc_bins*2),center_scale)};

        values.insert("poc".into(),json!({"price":text(&poc),"weighting":if unit_weight==window.len(){"price_density"}else if unit_weight>0{"mixed"}else{"bar_volume_proxy"},"missing_volume_count":unknown,"unit_weight_count":unit_weight,"bar_count":window.len(),"actual_price_volume_profile":false}));add("poc-proxy",if close>=poc{1}else{-1},d("0.52"),"ready","价格密度代理",vec![format!("非逐价成交量；{unknown} 根缺量，{unit_weight} 根使用价格密度等权")]);
        let flow=&self.bars[(i+1).saturating_sub(p.flow_bars)..=i];let(mut weighted,mut weight_sum)=(D::zero(),D::zero());for b in flow{let range=(&b.high-&b.low).max(b.close.abs()*d("0.00000001"));if range.is_zero(){continue;}let weight=b.volume.as_ref().filter(|v|*v>&D::zero()).and_then(sqrt).unwrap_or_else(D::one);weighted+=clamp(div(&(&b.close-&b.open),&range),"-1","1")*&weight;weight_sum+=weight;}let pressure=ratio(&weighted,&weight_sum).map(|v|clamp(v,"-1","1"));let flow_direction=pressure.as_ref().map_or(0,|v|if v>&p.flow_threshold{1}else if v<&(-&p.flow_threshold){-1}else{0});
        values.insert("order_flow".into(),json!({"pressure":pressure.as_ref().map(text),"weighting":"OHLC_body_range_proxy","missing_volume_count":flow.iter().filter(|b|b.volume.is_none()).count(),"actual_order_flow":false}));add("order-flow-proxy",flow_direction,if pressure.is_some(){d("0.44")}else{D::zero()},if pressure.is_some(){"ready"}else{"unavailable"},"OHLC 压力代理",vec!["缺 bid/ask、主动方向与 L2；缺量/零量使用等权代理".into()]);
        let raw=&self.bars[(i+1).saturating_sub(p.volume_price_bars)..=i];let volume_bars:Vec<_>=raw.iter().filter(|b|b.volume.as_ref().is_some_and(|v|v>&D::zero())).collect();let volume_state=if latest.volume.is_none()||volume_bars.len()<12{"unavailable"}else{let half=volume_bars.len()/2;let earlier=div(&volume_bars[..half].iter().map(|b|b.volume.clone().unwrap()).sum::<D>(),&n(half));let later=div(&volume_bars[half..].iter().map(|b|b.volume.clone().unwrap()).sum::<D>(),&n(volume_bars.len()-half));let vm=&later-&earlier;let pm=&volume_bars.last().unwrap().close-&volume_bars[0].close;if sign(&vm)==sign(&pm)||div(&vm,&earlier).abs()<d("0.04"){"confirming"}else{"diverging"}};
        values.insert("volume_price_state".into(),json!(volume_state));add("volume-price",if volume_state=="confirming"{1}else if volume_state=="diverging"{-1}else{0},if volume_state=="unavailable"{D::zero()}else{d("0.54")},if volume_state=="unavailable"{"unavailable"}else{"ready"},"量价确认",vec!["保留实际零量；该规则需要至少12个正量样本，缺量不填零".into()]);
        self.timings.insert("proxies".into(),stage.elapsed().as_micros() as u64);let stage=std::time::Instant::now();
        if derive_context&&p.enabled_strategies.contains("smart-money"){let events=smart_events_cached(&self.bars,i,&self.atr14);let shift=events.iter().rev().find(|v|v.status=="confirmed"&&v.confirmation.index==i&& !v.kind.contains("sweep"));let setup=shift.and_then(|shift|events.iter().rev().find(|v|v.status=="confirmed"&&v.direction==shift.direction&&v.kind.contains("sweep")&&v.confirmation.index<shift.confirmation.index&&shift.confirmation.index-v.confirmation.index<=8).map(|sweep|(shift,sweep)));let(direction,confidence)=setup.map_or((0,D::zero()),|(shift,sweep)|(if shift.direction=="bullish"{1}else{-1},clamp(div(&(&shift.confidence+&sweep.confidence),&d("2"))+d("0.08"),"0","0.82")));add("smart-money",direction,confidence,"context","流动性与结构代理",vec!["扫掠后8根内结构确认；不进入合成/交易".into()]);let visible=&events[events.len().saturating_sub(16)..];values.insert("market_structure_events".into(),serde_json::to_value(visible)?);}
        self.timings.insert("smart_money".into(),stage.elapsed().as_micros() as u64);
        }
        let stage=std::time::Instant::now();
        if derive_context&&p.enabled_strategies.contains("auto-trend"){let lines=self.trend_state.push(&self.bars,i,&self.atr14,self.processed_bars-self.bars.len());if derive_windows{values.insert("trend_lines".into(),serde_json::to_value(lines)?);}add("auto-trend",0,D::zero(),if i<12{"warming"}else{"context"},"已确认摆动趋势线",vec!["右侧2柱确认；负/零端价按既有趋势线版本不产生候选；不进入合成/回测".into()]);}
        if !derive_context{for id in ["smart-money","auto-trend"]{add(id,0,D::zero(),"context_omitted_for_execution",id,vec!["上下文策略不影响成交；完整快照单独生成".into()]);}}
        for id in ["multi-timeframe","vix-gvz","volume-open-interest"]{add(id,0,D::zero(),"context_unavailable",id,vec![if id=="auto-trend"{"趋势线独立结构图层，不形成交易方向".into()}else{"须有截止点以前已知的外部同源快照".into()}]);}
        self.timings.insert("auto_trend".into(),stage.elapsed().as_micros() as u64);let stage=std::time::Instant::now();
        signals.sort_by(|a,b|a.strategy_id.cmp(&b.strategy_id));let actionable:Vec<_>=signals.iter().filter(|s|s.composite_eligible&&s.confidence>D::zero()).collect();let denominator=actionable.iter().map(|s|s.confidence.clone()).sum::<D>();let score=if denominator.is_zero(){D::zero()}else{div(&actionable.iter().map(|s|&s.confidence*if s.direction=="bullish"{D::one()}else if s.direction=="bearish"{-D::one()}else{D::zero()}).sum::<D>(),&denominator)};
        let direction=if score>p.composite_threshold{1}else if score<(-&p.composite_threshold){-1}else{0};
        let offset=self.processed_bars-self.bars.len();if offset>0{fn shift(value:&mut Value,offset:usize){match value{Value::Object(object)=>for(key,value)in object{if ["index","confirmed_at_index"].contains(&key.as_str()){if let Some(index)=value.as_u64(){*value=json!(index+offset as u64);}}else{shift(value,offset);}},Value::Array(values)=>for value in values{shift(value,offset);},_=>{}}}for value in values.values_mut(){shift(value,offset);}}
        self.timings.insert("composite".into(),stage.elapsed().as_micros() as u64);
        Ok(IndicatorPoint{as_of:latest.open_time,decision_at:latest.known_at(semantics),indicators:values,signals,composite_score:score,direction})
    }
}
