use super::{exact::{d,D,text},quant::*,evaluator::Evaluator};
use chrono::{DateTime,Utc};
use num_traits::{Zero,One};
use serde_json::{Value,json};
use std::collections::BTreeSet;
fn at(index:i64)->DateTime<Utc>{DateTime::from_timestamp(1_700_000_000+index*60,0).unwrap()}
fn bar(index:i64,close:D,volume:Option<D>)->QuantBar{QuantBar{open_time:at(index),bucket_end:at(index+1),open:close.clone(),high:&close+D::one(),low:&close-D::one(),close,known_volume_sum:volume.clone().unwrap_or_default(),known_volume_count:u64::from(volume.is_some()),component_count:1,volume,state:"final".into(),revision:1,observed_at:at(index+1),received_at:at(index+1),accepted_at:Some(at(index+1)),finalized_at:Some(at(index+1)),applied_frame_seq:Some(index as u64+1),source_precision_ns:Some(1),source_volume_components:None,source_volume_component_groups:Vec::new()}}
#[test]
fn structural_coverage_is_hashed_and_displayed_without_a_market_clock() {
    let mut parameters = Parameters::default();
    parameters.enabled_strategies.insert("vix-gvz".into());
    let mut source = input(vec![bar(0,d("100"),None)],at(5));
    let baseline = evidence(&source,&parameters).unwrap();
    for kind in ["calendar_coverage", "source_point_coverage", "source_clock_coverage", "volatility"] {
        source.external_facts.push(ExternalFact { kind:kind.into(), source:"same-view-fixture".into(), record_id:Some(kind.into()), revision:Some(1), provenance:json!({"snapshot_version":{"commit_id":"1"}}), observed_at:None, published_at:None, received_at:None, unavailable_reason:None, value:json!({"source_event_coverage_complete":false,"known_unclassified_point_count_lower_bound":"2","sha256":"fixed-point-summary"}) });
    }
    let before = evidence(&source,&parameters).unwrap();
    assert_ne!(baseline.input_hash,before.input_hash);
    assert_ne!(baseline.effective_input_hash,before.effective_input_hash);
    let pure = super::snapshot::evaluate(&source,&parameters).unwrap();
    assert!(pure.confirmed.as_ref().unwrap().indicators["volatility"].is_null(), "coverage never supplies a market observation");
    for fact in &pure.external[..3] {
        assert_eq!(fact["included"],true);
        assert!(fact["known_at"].is_null() && fact["received_at"].is_null());
        assert!(fact["unavailable_reason"].is_null());
        assert_eq!(fact["value"]["known_unclassified_point_count_lower_bound"],"2");
        assert!(fact["evidence_role"].as_str().unwrap().contains("structural_coverage"));
    }
    assert_eq!(pure.external[3]["included"],false);
    assert_eq!(pure.external[3]["unavailable_reason"],"unknown availability time");
    let mut accumulator = super::snapshot::SnapshotAccumulator::new(parameters.clone()).unwrap();
    accumulator.push(source.clone()).unwrap();
    let current = accumulator.current().unwrap();
    assert_eq!(pure.external,current.external);
    assert_eq!(pure.evidence.input_hash,current.evidence.input_hash);
    source.decision_as_of=at(6); source.token.commit_id+=1;
    source.external_facts[1].provenance["snapshot_version"]["commit_id"]=json!("2");
    let clock_only=evidence(&source,&parameters).unwrap();
    assert_eq!(before.effective_input_hash,clock_only.effective_input_hash);
    source.external_facts[1].value["known_unclassified_point_count_lower_bound"]=json!("3");
    let changed=evidence(&source,&parameters).unwrap();
    assert_ne!(clock_only.input_hash,changed.input_hash);
    assert_ne!(clock_only.effective_input_hash,changed.effective_input_hash);
    let mut resumed=super::snapshot::SnapshotAccumulator::restore(accumulator.snapshot().unwrap(),&parameters).unwrap().resume();
    let mut context=source.clone(); context.bars.clear(); resumed.push(context).unwrap();
    assert_eq!(resumed.current().unwrap().evidence.input_hash,changed.input_hash);
}
#[test]fn effective_ai_identity_changes_only_for_visible_inputs_not_read_clocks(){
 let p=Parameters::default();let mut source=input((0..30).map(|i|bar(i,d("100"),None)).collect(),at(31));source.quote=Some(QuantQuote{price:d("100"),observed_at:at(30),received_at:at(30),accepted_at:Some(at(30)),applied_frame_seq:Some(30),source_precision_ns:Some(1)});source.external_facts.push(ExternalFact{record_id:Some("derived-commit-1".into()),revision:Some(1),provenance:json!({"snapshot_version":{"commit_id":"1"},"aggregation_version":"fixed"}),kind:"multi_timeframe".into(),source:"fixture".into(),observed_at:Some(at(29)),published_at:None,received_at:Some(at(30)),unavailable_reason:None,value:json!({"horizons":[],"decision_cutoff_ns":"read-clock-1"})});
 let first=evidence(&source,&p).unwrap();source.decision_as_of=at(32);source.token.commit_id+=1;source.external_facts[0].record_id=Some("derived-commit-2".into());source.external_facts[0].revision=Some(2);source.external_facts[0].provenance["snapshot_version"]["commit_id"]=json!("2");source.external_facts[0].value["decision_cutoff_ns"]=json!("read-clock-2");let same=evidence(&source,&p).unwrap();assert_eq!(first.effective_input_hash,same.effective_input_hash);assert_ne!(first.input_hash,same.input_hash);
 source.external_facts.push(ExternalFact{record_id:Some("future-publication".into()),revision:Some(1),provenance:json!({"source":"fixed"}),kind:"volatility".into(),source:"fixed-external".into(),observed_at:Some(at(1)),published_at:None,received_at:Some(at(33)),unavailable_reason:None,value:json!({"vix":"20"})});assert_eq!(same.effective_input_hash,evidence(&source,&p).unwrap().effective_input_hash);source.decision_as_of=at(33);let visible=evidence(&source,&p).unwrap();assert_ne!(same.effective_input_hash,visible.effective_input_hash);
 let mut event=source.clone();event.quote.as_mut().unwrap().received_at=at(31);event.quote.as_mut().unwrap().applied_frame_seq=Some(31);assert_ne!(visible.effective_input_hash,evidence(&event,&p).unwrap().effective_input_hash,"same price is a new genuine event when source receipt/sequence differs");let mut params=p.clone();params.rsi_period=10;assert_ne!(visible.effective_input_hash,evidence(&source,&params).unwrap().effective_input_hash);
 let mut forming=bar(30,d("101"),None);forming.state="forming".into();forming.finalized_at=None;source.bars.push(forming);let preview=evidence(&source,&p).unwrap();source.bars[30]=bar(30,d("101"),None);assert_ne!(preview.effective_input_hash,evidence(&source,&p).unwrap().effective_input_hash,"forming becomes confirmed");
}
#[test]fn unchanged_recursive_prefix_does_not_require_checkpoint_republication(){
 let parameters=Parameters::default();let mut accumulator=super::snapshot::SnapshotAccumulator::new(parameters.clone()).unwrap();let initial=input((0..30).map(|i|bar(i,d("100"),None)).collect(),at(31));accumulator.push(initial).unwrap();let identity=accumulator.checkpoint_identity().unwrap();let saved=accumulator.snapshot().unwrap();let mut resumed=super::snapshot::SnapshotAccumulator::restore(saved,&parameters).unwrap().resume();let mut context=input(vec![],at(32));context.token.commit_id+=1;context.token.committed_frame_seq+=1;context.quote=Some(QuantQuote{price:d("123"),observed_at:at(31),received_at:at(31),accepted_at:Some(at(31)),applied_frame_seq:Some(31),source_precision_ns:Some(1)});resumed.push(context).unwrap();assert_eq!(identity,resumed.checkpoint_identity().unwrap());let current=resumed.current().unwrap();assert_eq!(current.quote.unwrap().price,d("123"));assert_eq!(current.evidence.token.commit_id,10001);let mut append=resumed.resume();append.push(input(vec![bar(30,d("101"),None)],at(32))).unwrap();assert_ne!(identity,append.checkpoint_identity().unwrap());
}
pub(super) fn input(bars:Vec<QuantBar>,cutoff:DateTime<Utc>)->QuantInput{QuantInput{code:"TEST".into(),instrument:"TEST".into(),name:"fixed test fixture".into(),unit:"USD/unit".into(),executable_contract:true,source_id:"fixture".into(),period:"1m".into(),decision_as_of:cutoff,application_cursor:None,token:SnapshotToken{store_epoch:"fixture-v1".into(),commit_id:10000.max(cutoff.signed_duration_since(at(0)).num_minutes().max(0) as u64),capture_epoch:Some("capture-v1".into()),capture_digest:Some("immutable-content".into()),aggregation_version:"v1".into(),schema_version:"v1".into(),projector_version:"v1".into(),committed_frame_seq:10000.max(cutoff.signed_duration_since(at(0)).num_minutes().max(0) as u64),committed_part:None,catalog_version:"v1".into(),schedule_version:"v1".into(),route_version:"v1".into()},semantics:HistorySemantics::FinalRevisionHistory,derivation_id:None,capabilities:BTreeSet::from(["bars".into()]),revision_start:None,revision_end:None,warmup_complete:true,series_version:None,bars,quote:None,external_facts:vec![]}}
#[test]fn independent_high_precision_transcendental_oracle(){let oracle:Value=serde_json::from_str(include_str!("../../assets/quant-transcendental-oracle.json")).unwrap();for case in oracle["cases"].as_array().unwrap(){let x=d(case["input"].as_str().unwrap());let actual=if case["function"]=="ln"{super::exact::ln(&x).unwrap()}else{super::exact::tanh(&x)};assert_eq!(actual,d(case["expected"].as_str().unwrap()),"{}({}) produced {}",case["function"],case["input"],text(&actual));}}
#[test]fn decision_hash_ignores_future_bars_and_later_global_commit(){let bars:Vec<_>=(0..40).map(|i|bar(i,d("100")+D::from(i),None)).collect();let mut old=input(bars[..30].to_vec(),at(30));let before=evidence(&old,&Parameters::default()).unwrap();old.bars=bars;old.token.commit_id+=1;old.token.committed_frame_seq+=1;old.quote=Some(QuantQuote{price:d("999"),observed_at:at(40),received_at:at(40),accepted_at:Some(at(40)),applied_frame_seq:Some(40),source_precision_ns:Some(1)});let after=evidence(&old,&Parameters::default()).unwrap();assert_eq!(before.snapshot_hash,after.snapshot_hash);old.bars[2].close+=d(".5");let corrected=evidence(&old,&Parameters::default()).unwrap();assert_ne!(before.snapshot_hash,corrected.snapshot_hash);let mut changed=Parameters::default();changed.macd_fast=10;assert_ne!(corrected.snapshot_hash,evidence(&old,&changed).unwrap().snapshot_hash);}
#[test]fn missing_is_not_zero_and_negative_price_is_retained(){let mut e=Evaluator::new(Parameters::default()).unwrap();let mut last=None;for i in 0..130{last=Some(e.push(bar(i,-d("2"),if i%2==0{None}else{Some(D::zero())}),&HistorySemantics::FinalRevisionHistory).unwrap());}let p=last.unwrap();assert!(p.indicators["momentum"].is_null());assert!(p.signals.iter().any(|s|s.strategy_id=="momentum-ensemble"&&s.state=="unavailable"));assert_eq!(p.indicators["volume_price_state"],"unavailable");let missing=bar(1,d("1"),None);let zero=bar(1,d("1"),Some(D::zero()));assert!(serde_json::to_value(missing).unwrap()["volume"].is_null());assert_eq!(serde_json::to_value(zero).unwrap()["volume"],"0");}
#[test]fn all_seventeen_qualifications_remain_explicit(){let catalog=strategy_catalog();assert_eq!(catalog.len(),17);assert_eq!(catalog.iter().filter(|s|s.backtest_eligible).count(),11);let mut p=Parameters::default();p.enabled_strategies=catalog.iter().map(|s|s.id.into()).collect();let mut e=Evaluator::new(p).unwrap();let mut last=None;for i in 0..260{last=Some(e.push(bar(i,d("100")+D::from((i%13)-6),Some(d("100"))),&HistorySemantics::FinalRevisionHistory).unwrap());}let result=last.unwrap();assert_eq!(result.signals.len(),17);for s in &result.signals{let spec=catalog.iter().find(|v|v.id==s.strategy_id).unwrap();assert_eq!(s.composite_eligible,spec.composite_eligible);assert_eq!(s.backtest_eligible,spec.backtest_eligible);}}
#[test]fn flat_price_independent_indicator_expectations_and_checkpoint(){let mut e=Evaluator::new(Parameters::default()).unwrap();for i in 0..260{let point=e.push(bar(i,d("100"),Some(d("100"))),&HistorySemantics::FinalRevisionHistory).unwrap();if i==259{assert_eq!(point.indicators["macd"]["value"],"0");assert_eq!(point.indicators["kdj"]["k"],"50");assert_eq!(point.indicators["rsi"]["value"],"50");assert_eq!(point.indicators["moving_average"]["values"][3]["value"],"100");assert_eq!(point.indicators["momentum"]["score"],"0");}}
let saved=e.snapshot().unwrap();assert!(saved["state"]["bars"][0]["close"].is_string());let mut restored=Evaluator::restore(saved,&Parameters::default()).unwrap();let future=bar(260,d("102"),None);assert_eq!(serde_json::to_value(e.push(future.clone(),&HistorySemantics::FinalRevisionHistory).unwrap()).unwrap(),serde_json::to_value(restored.push(future,&HistorySemantics::FinalRevisionHistory).unwrap()).unwrap());let mut p=Parameters::default();p.rsi_period=10;assert!(Evaluator::restore(e.snapshot().unwrap(),&p).is_err());}
#[test]fn final_and_original_time_semantics_are_honest(){let mut b=bar(0,d("100"),None);b.received_at=at(10);let mut i=input(vec![b],at(1));assert_eq!(i.confirmed_bars().len(),1);i.semantics=HistorySemantics::OriginalEventReplay;assert!(i.confirmed_bars().is_empty());i.decision_as_of=at(10);assert_eq!(i.confirmed_bars().len(),1);}
#[test]fn null_parameter_and_unknown_modes_are_rejected(){assert!(serde_json::from_value::<Parameters>(json!({"rsi_period":null})).is_err());assert!(serde_json::from_value::<Parameters>(json!({"unexpected":1})).is_err());assert!(serde_json::from_value::<super::simulation::SimulationConfig>(json!({"fee_rate":0.02})).is_err());}
#[test]fn poc_handles_256_scale_adjacent_prices(){let mut p=Parameters::default();p.enabled_strategies=BTreeSet::from(["poc-proxy".into()]);let mut e=Evaluator::new(p).unwrap();let low=d("1");let high=&low+d(&format!("0.{}1","0".repeat(255)));let mut b=bar(0,low.clone(),Some(D::zero()));b.low=low.clone();b.open=low.clone();b.high=high.clone();let point=e.push(b,&HistorySemantics::FinalRevisionHistory).unwrap();let price=d(point.indicators["poc"]["price"].as_str().unwrap());assert!(price>low&&price<high);assert_eq!(point.signals[0].strategy_id,"poc-proxy");}
#[test]fn bounded_state_matches_untrimmed_oracle_across_drains(){let mut p=Parameters::default();p.enabled_strategies=BTreeSet::from(["macd".into(),"nine-count".into(),"structure".into(),"auto-trend".into(),"smart-money".into()]);let mut bounded=Evaluator::new(p.clone()).unwrap();let mut full=Evaluator::new(p.clone()).unwrap();full.retain_all_for_oracle();for index in 0..1620_i64{let b=bar(index,d("100")+D::from(index%13),Some(d("100")));let actual=bounded.push(b.clone(),&HistorySemantics::FinalRevisionHistory).unwrap();let expected=full.push(b,&HistorySemantics::FinalRevisionHistory).unwrap();assert_eq!(serde_json::to_value(&actual).unwrap(),serde_json::to_value(&expected).unwrap(),"bar {index}");if index==1200{bounded=Evaluator::restore(bounded.snapshot().unwrap(),&p).unwrap();}}assert!(bounded.bars.len()<1024);}
#[test]#[ignore="explicit release performance benchmark"]fn all_strategies_long_stream_profile(){let count=std::env::var("TRACEFANG_QUANT_BENCH_BARS").ok().and_then(|v|v.parse::<i64>().ok()).unwrap_or(520_000);let mut p=Parameters::default();p.enabled_strategies=strategy_catalog().iter().map(|s|s.id.into()).collect();let mut e=Evaluator::new(p).unwrap();let mut phases=std::collections::BTreeMap::<String,u64>::new();let started=std::time::Instant::now();for index in 0..count{let b=bar(index,d("100")+D::from(index%13)+super::exact::div(&D::from(index%31),&d("10")),if index%17==0{None}else{Some(D::from(index%1000))});e.push(b,&HistorySemantics::FinalRevisionHistory).unwrap();for(k,v)in &e.timings{*phases.entry(k.clone()).or_default()+=v;}if index%5000==0{eprintln!("quant progress {index}/{count} elapsed {}ms",started.elapsed().as_millis());}}let total_elapsed=started.elapsed().as_millis();let append=std::time::Instant::now();e.push(bar(count,d("101"),None),&HistorySemantics::FinalRevisionHistory).unwrap();let append_microseconds=append.elapsed().as_micros();let mut usage:libc::rusage=unsafe{std::mem::zeroed()};unsafe{libc::getrusage(libc::RUSAGE_SELF,&mut usage)};let output=json!({"maximum_resident_bytes":if cfg!(target_os="macos"){usage.ru_maxrss as u64}else{usage.ru_maxrss as u64*1024},"next_bar_microseconds":append_microseconds,"fixture":"synthetic exact OHLC; all17 enabled; mixed missing/zero/known volume","bars":count,"elapsed_ms":total_elapsed,"phases_microseconds":phases,"retained_bars":e.bars.len(),"checkpoint_bytes":serde_json::to_vec(&e.snapshot().unwrap()).unwrap().len()});println!("{output}");}
#[test]fn incremental_trend_matches_independent_full_formula(){let mut p=Parameters::default();p.enabled_strategies=BTreeSet::from(["auto-trend".into()]);let mut e=Evaluator::new(p).unwrap();let mut bars=vec![];for index in 0..650{let b=bar(index,d("100")+D::from(index%13)+super::exact::div(&D::from(index%31),&d("10")),None);bars.push(b.clone());let point=e.push(b,&HistorySemantics::FinalRevisionHistory).unwrap();if index>=12{let oracle=super::structure::trend_lines(&bars,index as usize);assert_eq!(point.indicators["trend_lines"],serde_json::to_value(oracle).unwrap(),"at {index}");}}}
#[test]fn tiny_variance_uses_guard_precision_and_exact_cancellation(){let tiny=d("0.00000000000000000001");let values=[-tiny.clone(),tiny.clone()];let sum=values.iter().cloned().sum::<D>();let squares=values.iter().map(|v|v*v).sum::<D>();assert_eq!(super::exact::population_deviation(&sum,&squares,2),Some(tiny.clone()));let shift=d("10000000000000000.01");let shifted=[&shift-&tiny,&shift+&tiny];assert_eq!(super::exact::population_deviation(&shifted.iter().cloned().sum::<D>(),&shifted.iter().map(|v|v*v).sum::<D>(),2),Some(tiny));}
#[test]fn legacy_import_clock_native_acceptance_and_cursor_are_distinct(){let mut legacy=bar(0,d("100"),None);legacy.accepted_at=None;let mut raw=input(vec![legacy],at(1));raw.semantics=HistorySemantics::OriginalEventReplay;raw.application_cursor=Some(1);assert_eq!(raw.confirmed_bars().len(),1);let mut native=bar(1,d("101"),None);native.accepted_at=Some(at(2)+chrono::Duration::milliseconds(7));raw.bars.push(native.clone());raw.application_cursor=Some(2);raw.decision_as_of=at(2);assert_eq!(raw.confirmed_bars().len(),1);raw.decision_as_of=native.accepted_at.unwrap();assert_eq!(raw.confirmed_bars().len(),2);raw.application_cursor=Some(1);assert_eq!(raw.confirmed_bars().len(),1);}

#[test]fn accepted_canonical_decimal_boundaries_round_trip(){
 for source in ["-1e-4096","1e4096","-1e-8192"]{let value=crate::exact::Decimal::from_str_exact(source).unwrap().as_bigdecimal();let canonical=text(&value);assert_eq!(super::exact::parse(&canonical).unwrap(),value);}
 let product=d("1e4096")*d("1e4096");assert_eq!(super::exact::parse(&text(&product)).unwrap(),product);
}
#[test]fn legacy_finalization_unknown_is_only_final_revision_history(){let mut b=bar(0,d("100"),None);b.finalized_at=None;b.accepted_at=None;b.received_at=at(10000);let mut i=input(vec![b],at(1));assert_eq!(i.confirmed_bars().len(),1);let mut acc=super::snapshot::SnapshotAccumulator::new(Parameters::default()).unwrap();acc.push(i.clone()).unwrap();assert_eq!(acc.current().unwrap().evidence.confirmed_count,1);i.semantics=HistorySemantics::OriginalEventReplay;i.application_cursor=Some(1);i.decision_as_of=at(10000);assert!(i.confirmed_bars().is_empty());}
#[test]fn replay_checkpoint_rebuild_ignores_physical_store_but_binds_cursor_digest(){let mut i=input((0..45).map(|n|bar(n,d("100")+D::from(n%13),None)).collect(),at(45));i.semantics=HistorySemantics::OriginalEventReplay;i.derivation_id=Some("stable-build-scope-v1".into());i.application_cursor=Some(45);let expected=evidence(&i,&Parameters::default()).unwrap();i.token.store_epoch="temporary-rebuild-2".into();assert_eq!(expected.input_hash,evidence(&i,&Parameters::default()).unwrap().input_hash);let mut acc=super::snapshot::SnapshotAccumulator::new(Parameters::default()).unwrap();let mut prefix=i.clone();prefix.bars.truncate(30);prefix.application_cursor=Some(30);prefix.decision_as_of=at(30);acc.push_replay(prefix).unwrap();let mut restored=super::snapshot::SnapshotAccumulator::restore(acc.snapshot().unwrap(),&Parameters::default()).unwrap();let mut tail=i.clone();tail.bars=tail.bars[30..].to_vec();restored.push_replay(tail).unwrap();assert_eq!(expected.input_hash,restored.current().unwrap().evidence.input_hash);i.token.capture_digest=Some("another-cursor-prefix-digest".into());assert_ne!(expected.input_hash,evidence(&i,&Parameters::default()).unwrap().input_hash);}

#[test]fn resumed_forming_tail_becomes_final_without_stale_preview_counts(){let p=Parameters::default();let mut first=input((0..30).map(|n|bar(n,d("100"),None)).collect(),at(31));let mut forming=bar(30,d("101"),None);forming.state="forming".into();forming.finalized_at=None;first.bars.push(forming);let mut acc=super::snapshot::SnapshotAccumulator::new(p.clone()).unwrap();acc.push(first.clone()).unwrap();assert_eq!(acc.current().unwrap().evidence.preview_count,1);let mut next=first.clone();next.bars[30]=bar(30,d("101"),None);next.decision_as_of=at(31);let expected=super::snapshot::evaluate(&next,&p).unwrap();let mut tail=next.clone();tail.bars=tail.bars[30..].to_vec();acc=acc.resume();acc.push(tail).unwrap();let actual=acc.current().unwrap();assert_eq!(actual.evidence.input_count,expected.evidence.input_count);assert_eq!(actual.evidence.preview_count,0);assert_eq!(actual.evidence.confirmed_count,31);assert_eq!(actual.evidence.input_hash,expected.evidence.input_hash);}

#[test]fn state_only_warmup_matches_complete_prefix_points_series_and_restore(){let mut p=Parameters::default();p.enabled_strategies=strategy_catalog().iter().map(|s|s.id.into()).collect();let mut oracle=Evaluator::new(p.clone()).unwrap();let mut fast=super::snapshot::SnapshotAccumulator::new(p.clone()).unwrap();let mut all_series=std::collections::VecDeque::new();let mut buffer=vec![];for index in 0..5200{let b=bar(index,d("100")+D::from(index%13)+super::exact::div(&D::from(index%31),&d("10")),if index%17==0{None}else{Some(D::from(index%1000))});let mut point=oracle.push(b.clone(),&HistorySemantics::FinalRevisionHistory).unwrap();all_series.push_back(super::snapshot::ChartIndicatorPoint::from(&point));if all_series.len()>1024{all_series.pop_front();}buffer.push(b);if buffer.len()==127||index==5199{let batch=input(std::mem::take(&mut buffer),at(5200));super::snapshot::external_context_at(&mut point,&batch,batch.decision_as_of);fast.push(batch).unwrap();let current=fast.current().unwrap();assert_eq!(serde_json::to_value(&current.confirmed).unwrap(),serde_json::to_value(Some(point)).unwrap(),"batch ending {index}");assert_eq!(current.series.len(),all_series.len());for (position,(actual,expected))in current.series.iter().zip(&all_series).enumerate(){assert_eq!(serde_json::to_value(actual).unwrap(),serde_json::to_value(expected).unwrap(),"series ending {index} point {position}");}if index>3500&&index<3750{fast=super::snapshot::SnapshotAccumulator::restore(fast.snapshot().unwrap(),&p).unwrap();}}}assert!(fast.current().unwrap().bars.len()<5200-2*1200,"oracle must cross at least two actual bounded drains");}
#[test]fn execution_context_skip_preserves_every_eligible_decision(){let mut p=Parameters::default();p.enabled_strategies=strategy_catalog().iter().map(|s|s.id.into()).collect();let mut full=Evaluator::new(p.clone()).unwrap();let mut trading=Evaluator::new(p).unwrap();for index in 0..350{let b=bar(index,d("100")+D::from(index%13),Some(D::from(index%1000)));let a=full.push(b.clone(),&HistorySemantics::FinalRevisionHistory).unwrap();let b=trading.push_execution(b,&HistorySemantics::FinalRevisionHistory).unwrap();assert_eq!(a.composite_score,b.composite_score);assert_eq!(a.direction,b.direction);let a:Vec<_>=a.signals.iter().filter(|s|s.backtest_eligible).collect();let b:Vec<_>=b.signals.iter().filter(|s|s.backtest_eligible).collect();assert_eq!(serde_json::to_value(a).unwrap(),serde_json::to_value(b).unwrap());}}
#[test]#[ignore="explicit cold state-only performance benchmark"]fn state_only_long_stream_profile(){
 let count=std::env::var("TRACEFANG_QUANT_BENCH_BARS").ok().and_then(|v|v.parse::<i64>().ok()).unwrap_or(10_000);let mut p=Parameters::default();p.enabled_strategies=strategy_catalog().iter().map(|s|s.id.into()).collect();let mut acc=super::snapshot::SnapshotAccumulator::new(p).unwrap();let start=std::time::Instant::now();let mut batch=vec![];
 for index in 0..count{batch.push(bar(index,d("100")+D::from(index%13)+super::exact::div(&D::from(index%31),&d("10")),if index%17==0{None}else{Some(D::from(index%1000))}));if batch.len()==256||index+1==count{acc.push(input(std::mem::take(&mut batch),at(count))).unwrap();}if index%50_000==0{eprintln!("typed progress {index}/{count} elapsed {}ms",start.elapsed().as_millis());}}
 let warmup=start.elapsed().as_millis();let materialize=std::time::Instant::now();let current=acc.current().unwrap();let materialize_ms=materialize.elapsed().as_millis();let repeat=std::time::Instant::now();let repeated=acc.current().unwrap();let repeat_us=repeat.elapsed().as_micros();assert_eq!(current.evidence.snapshot_hash,repeated.evidence.snapshot_hash);let append=std::time::Instant::now();let mut resumed=acc.clone().resume();resumed.push(input(vec![bar(count,d("101"),None)],at(count+1))).unwrap();let appended=resumed.current().unwrap();let append_us=append.elapsed().as_micros();assert_eq!(appended.evidence.confirmed_count,count as usize+1);
 println!("{}",json!({"bars":count,"fixture_watermark":10000.max(count as u64).to_string(),"warmup_ms":warmup,"materialize_ms":materialize_ms,"cold_total_ms":warmup+materialize_ms,"repeat_current_microseconds":repeat_us,"append_with_point_and_series_microseconds":append_us,"confirmed_count":current.evidence.confirmed_count,"snapshot_hash":current.evidence.snapshot_hash,"checkpoint_bytes":serde_json::to_vec(&acc.snapshot().unwrap()).unwrap().len(),"display_points":current.series.len(),"retained_bars":current.bars.len(),"mode":"all17 enabled; every history bar typed recurrence; complete endpoint and last1024 materialize; appended and repeated render cache"}));
}

#[test]fn snapshot_external_clock_does_not_rewrite_historical_decision(){let mut p=Parameters::default();p.enabled_strategies.insert("vix-gvz".into());let mut i=input(vec![bar(0,d("100"),None)],at(5));i.external_facts.push(ExternalFact{record_id:Some("fixed-test-record".into()),revision:Some(1),provenance:json!({"fixture":true}),kind:"volatility".into(),source:"fixed-evidence".into(),observed_at:Some(at(0)),published_at:None,received_at:Some(at(3)),unavailable_reason:None,value:json!({"value":"1"})});let snapshot=super::snapshot::evaluate(&i,&p).unwrap();let current=snapshot.confirmed.unwrap();assert_eq!(current.indicators["volatility"]["value"],"1");assert_eq!(current.decision_at,at(1));assert_eq!(current.indicators["external_context_cutoff"],json!(at(5)));let mut historical=Evaluator::new(p.clone()).unwrap().push(i.bars[0].clone(),&i.semantics).unwrap();super::snapshot::external_context(&mut historical,&i);assert!(historical.indicators["volatility"].is_null());let mut replay=i.clone();replay.semantics=HistorySemantics::OriginalEventReplay;replay.application_cursor=Some(1);replay.decision_as_of=at(1);assert!(super::snapshot::evaluate(&replay,&p).unwrap().confirmed.unwrap().indicators["volatility"].is_null());}

#[test]fn maximum_ma_window_typed_warmup_drains_and_restores(){
 let mut p=Parameters::default();p.ma_periods=vec![30,120,512,4096];p.enabled_strategies=BTreeSet::from(["macd".into(),"ma-structure".into(),"bollinger".into(),"rsi".into()]);
 let mut oracle=Evaluator::new(p.clone()).unwrap();oracle.retain_all_for_oracle();let mut fast=super::snapshot::SnapshotAccumulator::new(p.clone()).unwrap();let mut pending=vec![];let mut chart_oracle=std::collections::VecDeque::new();let count=21_000;
 for index in 0..count{let b=bar(index,d("100")+D::from(index%13),Some(D::from(index%1000)));let mut expected=oracle.push(b.clone(),&HistorySemantics::FinalRevisionHistory).unwrap();chart_oracle.push_back(super::snapshot::ChartIndicatorPoint::from(&expected));if chart_oracle.len()>1024{chart_oracle.pop_front();}pending.push(b);
  if pending.len()==256||index+1==count{let batch=input(std::mem::take(&mut pending),at(count));super::snapshot::external_context_at(&mut expected,&batch,batch.decision_as_of);fast.push(batch).unwrap();if index==12543{fast=super::snapshot::SnapshotAccumulator::restore(fast.snapshot().unwrap(),&p).unwrap();}if index+1==count{let actual=fast.current().unwrap();assert!(actual.bars.len()<11000,"must cross at least two actual drains");assert_eq!(serde_json::to_value(&actual.series).unwrap(),serde_json::to_value(&chart_oracle).unwrap());assert_eq!(serde_json::to_value(actual.confirmed).unwrap(),serde_json::to_value(Some(expected)).unwrap());}}
 }
}
#[test]fn typed_render_cache_append_and_external_refresh_match_cold(){
 let p=Parameters::default();let rows:Vec<_>=(0..1450).map(|i|bar(i,d("100")+D::from(i%13),None)).collect();let mut acc=super::snapshot::SnapshotAccumulator::new(p.clone()).unwrap();acc.push(input(rows[..1449].to_vec(),at(1450))).unwrap();let first=acc.current().unwrap();assert_eq!(first.series.len(),1024);let repeated=acc.current().unwrap();assert_eq!(serde_json::to_value(first).unwrap(),serde_json::to_value(repeated).unwrap());let mut resumed=acc.resume();resumed.push(input(rows[1449..].to_vec(),at(1450))).unwrap();let warm=resumed.current().unwrap();let mut cold=super::snapshot::SnapshotAccumulator::new(p.clone()).unwrap();cold.push(input(rows,at(1450))).unwrap();let expected=cold.current().unwrap();assert_eq!(serde_json::to_value(warm).unwrap(),serde_json::to_value(expected).unwrap());
}

#[test]fn resumed_prefix_preview_counts_match_current_canonical_input(){
 let p=Parameters::default();let mut rows:Vec<_>=(0..8).map(|i|bar(i,d("100"),None)).collect();rows[2].state="forming".into();rows[2].finalized_at=None;rows[7].state="forming".into();rows[7].finalized_at=None;
 let mut acc=super::snapshot::SnapshotAccumulator::new(p.clone()).unwrap();acc.push(input(rows.clone(),at(8))).unwrap();let before=acc.current().unwrap();assert_eq!(before.evidence.preview_count,2);let mut resumed=acc.resume();resumed.push(input(rows[7..].to_vec(),at(8))).unwrap();let hot=resumed.current().unwrap();assert_eq!(hot.evidence.input_count,before.evidence.input_count);assert_eq!(hot.evidence.preview_count,before.evidence.preview_count);assert_eq!(hot.evidence.input_hash,before.evidence.input_hash);
 rows[7].state="final".into();rows[7].finalized_at=Some(at(8));let mut hot_acc=resumed.resume();hot_acc.push(input(rows[7..].to_vec(),at(8))).unwrap();let hot=hot_acc.current().unwrap();let mut cold=super::snapshot::SnapshotAccumulator::new(p).unwrap();cold.push(input(rows,at(8))).unwrap();let cold=cold.current().unwrap();assert_eq!(hot.evidence.input_count,cold.evidence.input_count);assert_eq!(hot.evidence.preview_count,cold.evidence.preview_count);assert_eq!(hot.evidence.confirmed_count,cold.evidence.confirmed_count);assert_eq!(hot.evidence.input_hash,cold.evidence.input_hash);
}

#[test]fn nullable_canonical_volume_keeps_distinct_source_component_evidence(){
 let mut value=bar(1,d("100"),None);value.source_volume_components=Some(SourceVolumeComponents{known_volume_sum:d("2.0000000000000000000000000001"),known_count:1,total_count:2,policy:"fuyao-source-field-13-interval-v1".into()});value.validate().unwrap();
 assert!(value.volume.is_none());assert_eq!(value.known_volume_sum,d("0"));assert_eq!((value.known_volume_count,value.component_count),(0,1));
 let encoded=serde_json::to_value(&value).unwrap();assert_eq!(encoded["source_volume_components"]["known_volume_sum"],"2.0000000000000000000000000001");assert_eq!(encoded["source_volume_components"]["known_count"],"1");assert_eq!(encoded["source_volume_components"]["total_count"],"2");
 let original=content_hash(&value).unwrap();value.source_volume_components.as_mut().unwrap().known_volume_sum=d("3");assert_ne!(content_hash(&value).unwrap(),original);
 for (sum,known,total) in [("-1",1,2),("1",3,2),("1",0,2)]{value.source_volume_components=Some(SourceVolumeComponents{known_volume_sum:d(sum),known_count:known,total_count:total,policy:"fixed-source-policy".into()});assert!(value.validate().is_err());}
 value.source_volume_components=None;assert!(serde_json::to_value(value).unwrap().get("source_volume_components").is_none());
}

#[test]fn distinct_source_volume_policies_remain_separate_and_bounded(){
 let mut value=bar(1,d("100"),None);let original=serde_json::to_value(&value).unwrap();
 assert!(original.get("source_volume_component_groups").is_none());let old:QuantBar=serde_json::from_value(original).unwrap();assert!(old.source_volume_component_groups.is_empty());assert_eq!(content_hash(&value).unwrap(),content_hash(&old).unwrap());
 let source=SourceVolumeComponents{known_volume_sum:d("2.0000000000000000000000000001"),known_count:1,total_count:2,policy:"fuyao-source-field-13-interval-v1".into()};
 let fallback=SourceVolumeComponents{known_volume_sum:d("7"),known_count:1,total_count:1,policy:"canonical-minute-fallback-v1".into()};
 value.source_volume_component_groups=vec![source.clone(),fallback];value.validate().unwrap();assert!(value.volume.is_none());assert!(value.known_volume_sum.is_zero());
 let encoded=serde_json::to_value(&value).unwrap();assert!(encoded.get("source_volume_components").is_none());assert_eq!(encoded["source_volume_component_groups"][1]["known_volume_sum"],"2.0000000000000000000000000001");assert_eq!(encoded["source_volume_component_groups"][0]["known_volume_sum"],"7");let restored:QuantBar=serde_json::from_value(encoded).unwrap();assert_eq!(restored.source_volume_component_groups[0].policy,"canonical-minute-fallback-v1");assert_eq!(content_hash(&value).unwrap(),content_hash(&restored).unwrap());let mut reversed=value.clone();reversed.source_volume_component_groups.reverse();assert_eq!(content_hash(&value).unwrap(),content_hash(&reversed).unwrap());
 let hash=content_hash(&value).unwrap();value.source_volume_component_groups[1].known_volume_sum=d("8");assert_ne!(hash,content_hash(&value).unwrap());
 value.source_volume_components=Some(source.clone());assert!(value.validate().is_err());value.source_volume_components=None;
 value.source_volume_component_groups=vec![source.clone(),source.clone()];assert!(value.validate().is_err());
 value.source_volume_component_groups=(0..9).map(|i|SourceVolumeComponents{policy:format!("policy-{i}"),..source.clone()}).collect();assert!(value.validate().is_err());
 value.source_volume_component_groups.truncate(8);value.validate().unwrap();value.source_volume_component_groups[0].known_count=0;assert!(value.validate().is_err());value.source_volume_component_groups=vec![SourceVolumeComponents{known_volume_sum:d("0"),known_count:0,total_count:0,policy:"empty-policy".into()}];assert!(value.validate().is_err());
}

#[test]fn source_group_order_preserves_cold_snapshot_and_resumed_prefix_hash(){
 let source=SourceVolumeComponents{known_volume_sum:d("2.0000000000000000000000000001"),known_count:1,total_count:2,policy:"fuyao-source-field-13-interval-v1".into()};
 let fallback=SourceVolumeComponents{known_volume_sum:d("0"),known_count:0,total_count:1,policy:"canonical-minute-fallback-v1".into()};
 let mut a=bar(0,d("100"),None);a.source_volume_component_groups=vec![source.clone(),fallback.clone()];
 let mut b=bar(1,d("101"),None);b.source_volume_component_groups=vec![source,fallback];
 let p=Parameters::default();let full=input(vec![a.clone(),b.clone()],at(2));let mut full_acc=super::snapshot::SnapshotAccumulator::new(p.clone()).unwrap();full_acc.push(full).unwrap();let cold=full_acc.current().unwrap();
 a.source_volume_component_groups.reverse();b.source_volume_component_groups.reverse();let mut reversed_acc=super::snapshot::SnapshotAccumulator::new(p.clone()).unwrap();reversed_acc.push(input(vec![a.clone(),b.clone()],at(2))).unwrap();let reversed=reversed_acc.current().unwrap();assert_eq!(serde_json::to_value(&cold).unwrap(),serde_json::to_value(reversed).unwrap());
 let mut acc=super::snapshot::SnapshotAccumulator::new(p.clone()).unwrap();acc.push(input(vec![a],at(2))).unwrap();let mut restored=super::snapshot::SnapshotAccumulator::restore(acc.snapshot().unwrap(),&p).unwrap().resume();restored.push(input(vec![b],at(2))).unwrap();assert_eq!(serde_json::to_value(cold).unwrap(),serde_json::to_value(restored.current().unwrap()).unwrap());
}
