//! Immutable server-owned research inputs. This authority is not a live MVCC view.
use super::{quant::*,results::{atomic_json,create_directory,sync_directory}};
use anyhow::{Result,Context,ensure};
use chrono::{DateTime,Utc};
use serde::{Serialize,Deserialize};
use serde_json::Value;
use sha2::{Digest,Sha256};
use std::{collections::BTreeSet,fs,io::{BufRead,BufReader,BufWriter,Read,Write},path::{Path,PathBuf}};
use crate::persistence_contract::{CanonicalScanSummary,SnapshotVersion};

const VERSION:&str="research-authority-v1";
static AUTHORITY_WRITES:std::sync::Mutex<()>=std::sync::Mutex::new(());
fn retained_bytes(root:&Path)->Result<u64>{let mut total=0u64;let mut pending=vec![root.to_owned()];while let Some(directory)=pending.pop(){for entry in fs::read_dir(directory)?{let entry=entry?;let kind=entry.file_type()?;if kind.is_dir(){pending.push(entry.path());}else if kind.is_file(){total=total.checked_add(entry.metadata()?.len()).context("research retained byte count overflow")?;}}}Ok(total)}
fn disk_budget()->Result<u64>{let budget=match std::env::var("TRACEFANG_RESEARCH_AUTHORITY_MAX_BYTES"){Ok(value)=>value.parse::<u64>().context("invalid research disk budget")?,Err(std::env::VarError::NotPresent)=>8*1024*1024*1024,Err(error)=>return Err(error.into())};ensure!(budget>=1_048_576,"research disk budget must be at least 1 MiB");Ok(budget)}
#[derive(Clone,Debug,Serialize,Deserialize,PartialEq,Eq)]
#[serde(deny_unknown_fields)]
pub struct ResearchScope{pub source:String,pub symbol:String,pub asset:String,pub period:String,pub adjustment:String}
#[derive(Clone,Debug,Serialize,Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ResearchManifest{
 pub authority:String,pub scope:ResearchScope,pub query:Value,pub feed:String,pub fetched_at:DateTime<Utc>,
 pub first_open:Option<DateTime<Utc>>,pub last_open:Option<DateTime<Utc>>,pub row_count:u64,
 pub canonical_sha256:String,pub canonical_bytes:u64,pub upstream_payload_sha256:String,pub rejected_rows:u64,
 pub parser_version:String,pub calendar_version:String,pub precision_policy:String,pub pagination_evidence:Value,
 pub warmup_complete:bool,pub coverage_reason:String,pub unit:String,
}
#[derive(Clone,Debug,Serialize,Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ResearchAuthority{pub id:String,pub manifest:ResearchManifest}
fn valid_id(id:&str)->bool{id.len()==64&&id.bytes().all(|b|b.is_ascii_hexdigit()&& !b.is_ascii_uppercase())}
fn directory(root:&Path,id:&str)->Result<PathBuf>{ensure!(valid_id(id),"invalid research snapshot id");Ok(root.join(id))}

pub fn publish(root:&Path,manifest:ResearchManifest,bars:&[QuantBar])->Result<ResearchAuthority>{
 let mut rows=bars.iter().cloned();publish_stream(root,manifest,move||Ok(rows.next()),|_|{})
}
fn publish_stream<F,P>(root:&Path,mut manifest:ResearchManifest,mut next:F,finish_provenance:P)->Result<ResearchAuthority>where F:FnMut()->Result<Option<QuantBar>>,P:FnOnce(&mut ResearchManifest){
 let _write=AUTHORITY_WRITES.lock().map_err(|_|anyhow::anyhow!("research authority publication lock poisoned"))?;create_directory(root)?;let retained=retained_bytes(root)?;let budget=disk_budget()?;let temporary=root.join(format!(".pending-{}",uuid::Uuid::new_v4()));create_directory(&temporary)?;
 let outcome=(||->Result<ResearchAuthority>{
  let mut writer=BufWriter::new(fs::File::create(temporary.join("canonical.jsonl"))?);let mut hasher=Sha256::new();let mut previous=None;let mut first=None;let mut count=0u64;let mut published_bytes=0u64;
  while let Some(bar)=next()?{bar.validate()?;ensure!(previous.is_none_or(|at|bar.open_time>at),"research rows must be ordered and unique");previous=Some(bar.open_time);if first.is_none(){first=Some(bar.open_time);}count+=1;let mut line=serde_json::to_vec(&bar)?;line.push(b'\n');published_bytes=published_bytes.checked_add(line.len() as u64).context("research byte count overflow")?;ensure!(retained.checked_add(published_bytes).and_then(|value|value.checked_add(1_048_576)).is_some_and(|value|value<=budget),"研究版本存储空间达到本机预算；旧版本仍保留，本次未发布新版本");writer.write_all(&line)?;hasher.update(&line);}
  writer.flush()?;writer.get_ref().sync_all()?;manifest.authority=VERSION.into();manifest.row_count=count;manifest.first_open=first;manifest.last_open=previous;manifest.canonical_bytes=writer.get_ref().metadata()?.len();manifest.canonical_sha256=hex::encode(hasher.finalize());finish_provenance(&mut manifest);
  ensure!(!manifest.warmup_complete,"research available-window input cannot claim full historical warmup");
  let authority=ResearchAuthority{id:content_hash(&manifest)?,manifest};atomic_json(&temporary.join("manifest.json"),&serde_json::to_value(&authority)?)?;sync_directory(&temporary)?;
  let target=directory(root,&authority.id)?;if target.exists(){let existing=read(root,&authority.id)?;ensure!(content_hash(&existing.manifest)?==authority.id,"existing research manifest differs");fs::remove_dir_all(&temporary)?;}else{fs::rename(&temporary,&target)?;sync_directory(root)?;}Ok(authority)
 })();if outcome.is_err(){let _=fs::remove_dir_all(&temporary);}outcome
}
fn read_manifest(root:&Path,id:&str)->Result<ResearchAuthority>{let dir=directory(root,id)?;let authority:ResearchAuthority=serde_json::from_reader(fs::File::open(dir.join("manifest.json"))?)?;ensure!(authority.id==id&&authority.manifest.authority==VERSION&&content_hash(&authority.manifest)?==id,"research manifest identity or content differs");Ok(authority)}
pub fn read(root:&Path,id:&str)->Result<ResearchAuthority>{let authority=read_manifest(root,id)?;let mut file=fs::File::open(directory(root,id)?.join("canonical.jsonl"))?;ensure!(file.metadata()?.len()==authority.manifest.canonical_bytes,"research input size differs");let mut digest=Sha256::new();let mut buffer=[0_u8;65536];loop{let count=file.read(&mut buffer)?;if count==0{break;}digest.update(&buffer[..count]);}ensure!(hex::encode(digest.finalize())==authority.manifest.canonical_sha256,"research canonical input checksum differs");Ok(authority)}
struct VerifiedRows{reader:BufReader<fs::File>,manifest:ResearchManifest,digest:Sha256,rows:u64,bytes:u64,previous:Option<DateTime<Utc>>,complete:bool}
impl VerifiedRows{
 fn new(root:&Path,authority:&ResearchAuthority)->Result<Self>{Ok(Self{reader:BufReader::new(fs::File::open(directory(root,&authority.id)?.join("canonical.jsonl"))?),manifest:authority.manifest.clone(),digest:Sha256::new(),rows:0,bytes:0,previous:None,complete:false})}
 fn next(&mut self)->Result<Option<QuantBar>>{if self.complete{return Ok(None);}let mut line=Vec::new();self.reader.by_ref().take(1_048_577).read_until(b'\n',&mut line)?;ensure!(line.len()<=1_048_576,"research row exceeds bound");if line.is_empty(){ensure!(self.rows==self.manifest.row_count&&self.bytes==self.manifest.canonical_bytes,"research merge parent count differs");ensure!(hex::encode(self.digest.clone().finalize())==self.manifest.canonical_sha256,"research merge parent checksum differs");self.complete=true;return Ok(None);}ensure!(line.last()==Some(&b'\n'),"research row lacks canonical delimiter");self.digest.update(&line);self.bytes+=line.len() as u64;self.rows+=1;let bar:QuantBar=serde_json::from_slice(&line)?;bar.validate()?;ensure!(self.previous.is_none_or(|previous|bar.open_time>previous),"research merge parent order differs");self.previous=Some(bar.open_time);Ok(Some(bar))}
}
/// Merge separately fetched pages into an explicitly composite immutable source.
/// Parent manifests preserve their original fetch clocks; no common upstream
/// transaction is asserted. Conflicting same-time facts reject publication.
pub fn merge(root:&Path,left_id:&str,right_id:&str)->Result<ResearchAuthority>{
 let left=read_manifest(root,left_id)?;let right=read_manifest(root,right_id)?;ensure!(left.manifest.scope==right.manifest.scope,"research merge scope differs");ensure!(left.manifest.parser_version==right.manifest.parser_version&&left.manifest.calendar_version==right.manifest.calendar_version&&left.manifest.precision_policy==right.manifest.precision_policy&&left.manifest.unit==right.manifest.unit,"research merge normalization/units differ");
 if left_id==right_id{return read(root,left_id);}
 let mut a=VerifiedRows::new(root,&left)?;let mut b=VerifiedRows::new(root,&right)?;let mut x=a.next()?;let mut y=b.next()?;let duplicates=std::cell::Cell::new(0u64);let mut manifest=left.manifest.clone();manifest.fetched_at=left.manifest.fetched_at.max(right.manifest.fetched_at);manifest.feed="composite immutable server-owned research pages".into();manifest.query=serde_json::json!({"scope":manifest.scope,"parent_authorities":[left_id,right_id]});manifest.upstream_payload_sha256=content_hash(&(&left.id,&left.manifest.upstream_payload_sha256,&right.id,&right.manifest.upstream_payload_sha256))?;manifest.rejected_rows=left.manifest.rejected_rows.checked_add(right.manifest.rejected_rows).context("research rejection count overflow")?;manifest.warmup_complete=false;manifest.coverage_reason="merged independently fetched available windows; full listing history and common upstream MVCC are not proven".into();manifest.pagination_evidence=serde_json::json!({"merge_schema":"research-page-merge-v1","merged_at":Utc::now(),"common_upstream_mvcc":false,"same_time_conflict_policy":"reject differing facts; deduplicate equal facts and retain earliest actual received time","parents":[{"id":left.id,"canonical_sha256":left.manifest.canonical_sha256,"fetched_at":left.manifest.fetched_at,"row_count":left.manifest.row_count},{"id":right.id,"canonical_sha256":right.manifest.canonical_sha256,"fetched_at":right.manifest.fetched_at,"row_count":right.manifest.row_count}]});
 let scope=manifest.scope.clone();let result=publish_stream(root,manifest,||{
  let picked=match (&x,&y){(None,None)=>return Ok(None),(Some(_),None)=>{let value=x.take().unwrap();x=a.next()?;value},(None,Some(_))=>{let value=y.take().unwrap();y=b.next()?;value},(Some(first),Some(second)) if first.open_time<second.open_time=>{let value=x.take().unwrap();x=a.next()?;value},(Some(first),Some(second)) if first.open_time>second.open_time=>{let value=y.take().unwrap();y=b.next()?;value},(Some(first),Some(second))=>{
    let mut first_fact=serde_json::to_value(first)?;let mut second_fact=serde_json::to_value(second)?;first_fact.as_object_mut().unwrap().remove("received_at");second_fact.as_object_mut().unwrap().remove("received_at");if first_fact!=second_fact{let evidence=serde_json::json!({"schema":"research-page-merge-conflict-v1","scope":scope,"parents":[left_id,right_id],"conflict_count":"1","open_time":first.open_time,"left_fact_sha256":content_hash(&first_fact)?,"right_fact_sha256":content_hash(&second_fact)?,"published_authority":null});atomic_json(&root.join(format!("merge-conflict-{}.json",uuid::Uuid::new_v4())),&evidence)?;anyhow::bail!("研究历史同一时点存在冲突，已保存冲突证据，本次未发布合并版本");}duplicates.set(duplicates.get()+1);let value=if first.received_at<=second.received_at{x.take().unwrap()}else{y.take().unwrap()};x=a.next()?;y=b.next()?;value
   }};Ok(Some(picked))
 },|manifest|manifest.pagination_evidence["deduplicated_rows"]=serde_json::json!(duplicates.get().to_string()));result
}
fn version(authority:&ResearchAuthority)->SnapshotVersion{SnapshotVersion{store_epoch:format!("research-manifest:{}",authority.id),commit_id:0,committed_capture:None,schema_version:VERSION.into(),aggregation_version:authority.manifest.calendar_version.clone(),projector_version:authority.manifest.parser_version.clone(),catalog_version:"research-source-config-v1".into(),schedule_version:authority.manifest.calendar_version.clone(),route_version:content_hash(&authority.manifest.scope).expect("scope serialization"),active_generation:authority.id.clone()}}
pub fn scan<F>(root:&Path,request:&QuantInputRequest,batch_rows:usize,mut accept:F)->Result<CanonicalScanSummary> where F:FnMut(QuantInput)->Result<()>{
 ensure!(batch_rows>0&&batch_rows<=4096,"research scan batch outside bounds");ensure!(request.application_cursor.is_none(),"research snapshots are final revision history, not capture replay");let id=request.research_snapshot_id.as_deref().context("research snapshot reference required")?;let authority=read_manifest(root,id)?;let scope=&authority.manifest.scope;
 ensure!(request.code==scope.symbol&&request.source_id.as_ref()==Some(&scope.source)&&request.period==scope.period&&request.research_adjustment.as_ref()==Some(&scope.adjustment)&&request.research_asset.as_ref()==Some(&scope.asset),"research snapshot does not match source, symbol, asset, period or adjustment");
 let cutoff=request.decision_as_of.unwrap_or(authority.manifest.fetched_at);let end=request.end.unwrap_or(cutoff).min(cutoff);ensure!(request.start.is_none_or(|at|at<=end),"research range is inverted");
 if let Some(resume)=&request.resume{ensure!(resume.series_version.series_generation==id&&resume.series_version.correction_epoch==0,"quant_resume_invalid: research authority changed");}
 let version=version(&authority);let mut capabilities=BTreeSet::from(["research_immutable_manifest".into(),"final_revision_history".into(),"finalization_time_unknown".into(),"available_window_only".into(),authority.manifest.coverage_reason.clone(),authority.manifest.precision_policy.clone()]);capabilities.insert(format!("research_snapshot_id:{id}"));capabilities.insert(format!("research_full_manifest_sha256:{}",authority.manifest.canonical_sha256));
 let template=QuantInput{code:scope.symbol.clone(),instrument:scope.symbol.clone(),name:scope.symbol.clone(),unit:authority.manifest.unit.clone(),executable_contract:false,source_id:scope.source.clone(),period:scope.period.clone(),decision_as_of:cutoff,application_cursor:None,token:SnapshotToken{store_epoch:version.store_epoch.clone(),commit_id:0,capture_epoch:None,capture_digest:None,aggregation_version:version.aggregation_version.clone(),schema_version:version.schema_version.clone(),projector_version:version.projector_version.clone(),committed_frame_seq:0,committed_part:None,catalog_version:version.catalog_version.clone(),schedule_version:version.schedule_version.clone(),route_version:version.route_version.clone()},semantics:HistorySemantics::FinalRevisionHistory,derivation_id:Some(id.into()),capabilities,revision_start:authority.manifest.first_open,revision_end:authority.manifest.last_open,warmup_complete:false,series_version:Some(SeriesVersion{series_generation:id.into(),correction_epoch:0,append_watermark_ns:authority.manifest.last_open.and_then(|at|at.timestamp_nanos_opt()).map(|ns|ns.to_string()),last_mutation_commit_id:0}),bars:vec![],quote:None,external_facts:vec![]};
 let mut batch=template.clone();let mut row_count=0_u64;let mut read_count=0_u64;let mut bytes=0_u64;let mut previous=None;let mut full_digest=Sha256::new();let mut delivered_digest=Sha256::new();let mut file=BufReader::new(fs::File::open(directory(root,id)?.join("canonical.jsonl"))?);let mut line=vec![];
 loop{line.clear();let count=file.by_ref().take(1_048_577).read_until(b'\n',&mut line)?;if count==0{break;}ensure!(line.len()<=1_048_576,"research canonical row exceeds bound");bytes+=count as u64;full_digest.update(&line);let bar:QuantBar=serde_json::from_slice(&line)?;bar.validate()?;ensure!(previous.is_none_or(|at|bar.open_time>at),"research canonical order differs");previous=Some(bar.open_time);read_count+=1;if bar.open_time>=end||request.resume.as_ref().is_some_and(|r|bar.open_time<=r.after){continue;}let mut delivered=serde_json::to_vec(&bar)?;delivered.push(b'\n');delivered_digest.update(&delivered);batch.bars.push(bar);row_count+=1;if batch.bars.len()==batch_rows{accept(batch)?;batch=template.clone();}}
 ensure!(read_count==authority.manifest.row_count&&bytes==authority.manifest.canonical_bytes,"research input row count or bytes differs");ensure!(hex::encode(full_digest.finalize())==authority.manifest.canonical_sha256,"research canonical input checksum differs");if !batch.bars.is_empty()||row_count==0{accept(batch)?;}Ok(CanonicalScanSummary{version,row_count,sha256:hex::encode(delivered_digest.finalize()),complete:true})

}

#[cfg(test)]mod tests{
 use super::*;use super::super::exact::d;
 fn fixture()->(ResearchManifest,Vec<QuantBar>){let at=DateTime::parse_from_rfc3339("2024-01-01T00:00:00Z").unwrap().with_timezone(&Utc);let scope=ResearchScope{source:"fixed-test-source".into(),symbol:"SIGNED".into(),asset:"future".into(),period:"1m".into(),adjustment:"raw".into()};let bars=(0..7).map(|i|{let time=at+chrono::Duration::minutes(i);QuantBar{open_time:time,bucket_end:time+chrono::Duration::minutes(1),open:d("-1.0000000000000000000000000001"),high:d("0"),low:d("-2"),close:d("-1"),volume:if i==0{None}else{Some(d("0"))},known_volume_sum:d("0"),known_volume_count:u64::from(i!=0),component_count:1,state:"final".into(),revision:1,observed_at:time,received_at:at+chrono::Duration::days(1),accepted_at:None,finalized_at:None,applied_frame_seq:None,source_precision_ns:Some(1),source_volume_components:None,source_volume_component_groups:Vec::new()}}).collect();(ResearchManifest{authority:String::new(),scope,query:Value::Null,feed:"fixed test data".into(),fetched_at:at+chrono::Duration::days(1),first_open:None,last_open:None,row_count:0,canonical_sha256:String::new(),canonical_bytes:0,upstream_payload_sha256:content_hash(&"fixed input").unwrap(),rejected_rows:0,parser_version:"fixed-test".into(),calendar_version:"calendar-v1".into(),precision_policy:"exact_source_lexeme".into(),pagination_evidence:Value::Null,warmup_complete:false,coverage_reason:"only supplied research window".into(),unit:"test units".into()},bars)}
 #[test]fn merged_pages_are_new_authority_with_exact_rows_clocks_and_conflict_rejection(){
  let root=tempfile::tempdir().unwrap();let (manifest,bars)=fixture();let a=publish(root.path(),manifest.clone(),&bars[3..]).unwrap();let mut later=manifest.clone();later.fetched_at+=chrono::Duration::minutes(1);let mut older=bars[..4].to_vec();for bar in &mut older{bar.received_at+=chrono::Duration::minutes(1);}let b=publish(root.path(),later.clone(),&older).unwrap();let merged=merge(root.path(),&a.id,&b.id).unwrap();assert_ne!(merged.id,a.id);assert_eq!(merged.manifest.row_count,7);assert_eq!(merged.manifest.pagination_evidence["common_upstream_mvcc"],false);assert_eq!(merged.manifest.pagination_evidence["deduplicated_rows"],"1");assert_eq!(merged.manifest.fetched_at,later.fetched_at);assert!(!merged.manifest.warmup_complete);let mut reader=VerifiedRows::new(root.path(),&merged).unwrap();let mut seen=Vec::new();while let Some(bar)=reader.next().unwrap(){seen.push(bar);}assert_eq!(seen[3].received_at,bars[3].received_at);assert!(seen[0].volume.is_none());assert_eq!(seen[1].volume,Some(d("0")));assert_eq!(seen[0].open,bars[0].open);
  older[3].close=d("-1.5");let conflicting=publish(root.path(),later.clone(),&older).unwrap();assert!(merge(root.path(),&a.id,&conflicting.id).is_err());assert!(fs::read_dir(root.path()).unwrap().any(|entry|entry.unwrap().file_name().to_string_lossy().starts_with("merge-conflict-")));let mut wrong=manifest.clone();wrong.scope.adjustment="forward".into();let wrong=publish(root.path(),wrong,&bars).unwrap();assert!(merge(root.path(),&merged.id,&wrong.id).is_err());assert_eq!(read(root.path(),&a.id).unwrap().id,a.id);
 }
 #[test]fn immutable_source_scope_exact_stream_and_tamper(){let temp=tempfile::tempdir().unwrap();let (manifest,bars)=fixture();let a=publish(temp.path(),manifest.clone(),&bars).unwrap();let mut changed=manifest.clone();changed.fetched_at+=chrono::Duration::seconds(1);let b=publish(temp.path(),changed,&bars).unwrap();assert_ne!(a.id,b.id);assert_eq!(read(temp.path(),&a.id).unwrap().id,a.id);let query=QuantInputRequest{code:manifest.scope.symbol.clone(),source_id:Some(manifest.scope.source.clone()),period:manifest.scope.period.clone(),research_snapshot_id:Some(a.id.clone()),research_asset:Some("future".into()),research_adjustment:Some("raw".into()),..Default::default()};let mut seen=vec![];scan(temp.path(),&query,2,|input|{assert!(!input.warmup_complete);assert!(input.token.capture_epoch.is_none());seen.extend(input.bars);Ok(())}).unwrap();assert_eq!(content_hash(&bars).unwrap(),content_hash(&seen).unwrap());assert_eq!(seen[0].volume,None);let mut wrong=query.clone();wrong.research_adjustment=Some("forward".into());assert!(scan(temp.path(),&wrong,2,|_|Ok(())).is_err());fs::write(temp.path().join(&a.id).join("canonical.jsonl"),vec![b' ';1_048_577]).unwrap();assert!(scan(temp.path(),&query,2,|_|Ok(())).unwrap_err().to_string().contains("row exceeds bound"));let mut oversized=VerifiedRows::new(temp.path(),&a).unwrap();assert!(oversized.next().unwrap_err().to_string().contains("row exceeds bound"));fs::write(temp.path().join(&a.id).join("canonical.jsonl"),b"changed").unwrap();assert!(read(temp.path(),&a.id).is_err());assert!(read(temp.path(),"../unpublished").is_err());assert_eq!(read(temp.path(),&b.id).unwrap().id,b.id);}
}
