//! Bounded research jobs. Authority input is scanned once in a single MVCC view.
use super::{quant::*,simulation::{SimulationConfig,Simulator,LedgerEvent},snapshot::external_context};
use crate::api::{AppState,ApiError,ApiResult};
use anyhow::{Result,Context,ensure};
use axum::{Router,Json,extract::{State,Path,Query},routing::{get,post},http::StatusCode};
use serde::{Serialize,Deserialize};
use serde_json::{Value,json};
use sha2::{Digest,Sha256};
use super::results::{root,sync_directory,durability_scope,atomic_json,write_canonical,EventWriter,create_directory};
use std::{sync::{Arc,Mutex,LazyLock,atomic::{AtomicBool,Ordering}},collections::BTreeMap,path::{Path as FsPath,PathBuf},io::{BufReader,BufWriter,Write},fs};
use tokio::sync::{Semaphore,mpsc,Notify};
use tracefang_core::persistence_contract::CanonicalScanSummary;
static LIMIT:LazyLock<Arc<Semaphore>>=LazyLock::new(||Arc::new(Semaphore::new(2)));
static JOBS:LazyLock<Mutex<BTreeMap<String,Arc<Job>>>>=LazyLock::new(||Mutex::new(BTreeMap::new()));
struct Job{cancel:AtomicBool,status:Mutex<Value>,directory:PathBuf}
#[derive(Clone,Debug,Deserialize)]#[serde(deny_unknown_fields)]
struct RunRequest{input:QuantInputRequest,config:SimulationConfig,#[serde(default)]expected_input_hash:Option<String>,#[serde(default)]base_run_id:Option<String>}
#[derive(Deserialize,Default)]#[serde(default,deny_unknown_fields)]struct PageQuery{page:usize}
fn valid_id(id:&str)->bool{uuid::Uuid::parse_str(id).is_ok()}
fn error(e:impl ToString)->ApiError{ApiError(StatusCode::UNPROCESSABLE_ENTITY,e.to_string())}
fn publish(job:&Job,status:Value)->Result<()>{atomic_json(&job.directory.join("manifest.json"),&status)?;*job.status.lock().expect("job status lock")=status;Ok(())}
fn persisted(id:&str)->Result<Value>{ensure!(valid_id(id),"invalid research run id");let active=JOBS.lock().expect("jobs lock").contains_key(id);super::results::manifest(&root().join(id),active)}
pub fn router()->Router<AppState>{Router::new().route("/api/expert/quant/snapshot",post(snapshot)).route("/api/expert/quant/defaults",get(defaults)).route("/api/expert/quant/snapshot/jobs/{id}",get(snapshot_status)).route("/api/expert/quant/snapshot/jobs/{id}/cancel",post(snapshot_cancel)).route("/api/expert/simulations",get(list).post(start)).route("/api/expert/simulations/{id}",get(status)).route("/api/expert/simulations/{id}/cancel",post(cancel)).route("/api/expert/simulations/{id}/events",get(events)).route("/api/expert/simulations/{id}/audit",get(audit))}
async fn defaults()->Json<Value>{Json(json!({"parameters":Parameters::default(),"config":SimulationConfig::default(),"strategy_catalog":strategy_catalog(),"schema_version":SCHEMA_VERSION,"calculation_version":CALCULATION_VERSION,"execution_version":super::simulation::EXECUTION_VERSION,"rounding_policy":super::exact::POLICY,"active_limit":2}))}
static SNAPSHOTS:LazyLock<Mutex<BTreeMap<String,(std::time::Instant,super::snapshot::SnapshotAccumulator)>>>=LazyLock::new(||Mutex::new(BTreeMap::new()));
static VERSIONS:LazyLock<Mutex<BTreeMap<String,(std::time::Instant,super::snapshot::QuantSnapshot,QuantInputRequest)>>>=LazyLock::new(||Mutex::new(BTreeMap::new()));
static BUILD_JOBS:LazyLock<Mutex<BTreeMap<String,Arc<SnapshotJob>>>>=LazyLock::new(||Mutex::new(BTreeMap::new()));
static BUILD_SCOPE:LazyLock<Mutex<BTreeMap<String,String>>>=LazyLock::new(||Mutex::new(BTreeMap::new()));
static ENGINE_BUILD:LazyLock<String>=LazyLock::new(super::results::backend_build_fingerprint);
struct SnapshotJob{cancel:AtomicBool,status:Mutex<Value>,changed:Notify}
fn snapshot_key(request:&QuantInputRequest)->Result<String>{content_hash(&(&request.code,&request.source_id,&request.period,request.start,request.end,request.decision_as_of,request.application_cursor,&request.parameters,&request.research_snapshot_id,&request.research_adjustment,&request.research_asset,&*ENGINE_BUILD))}
fn checkpoint_path(key:&str)->PathBuf{root().join("checkpoints").join(format!("{key}.json"))}
fn save_checkpoint(key:&str,accumulator:&super::snapshot::SnapshotAccumulator,complete:bool)->Result<()>{save_checkpoint_profile(key,accumulator,complete).map(|_|())}
fn save_checkpoint_profile(key:&str,accumulator:&super::snapshot::SnapshotAccumulator,complete:bool)->Result<Value>{let path=checkpoint_path(key);create_directory(path.parent().unwrap())?;let started=std::time::Instant::now();let state=accumulator.snapshot()?;let state_materialize_us=started.elapsed().as_micros();let started=std::time::Instant::now();let hash=content_hash(&state)?;let state_hash_us=started.elapsed().as_micros();let envelope=json!({"checkpoint_schema":"quant-persisted-v1","scope_key":key,"engine_build":&*ENGINE_BUILD,"state_sha256":hash,"complete":complete,"processed_bars":accumulator.processed_bars().to_string(),"saved_at":chrono::Utc::now(),"state":state});let mut profile=super::results::atomic_json_profile(&path,&envelope)?;profile["state_materialize_us"]=json!(state_materialize_us.to_string());profile["state_hash_us"]=json!(state_hash_us.to_string());Ok(profile)}
fn load_checkpoint_file(path:&FsPath,key:&str,parameters:&Parameters)->Result<(Option<(super::snapshot::SnapshotAccumulator,bool)>,Value)>{
 if !path.exists(){return Ok((None,json!({"state":"absent"})));}
 let started=std::time::Instant::now();let file=fs::File::open(path)?;let bytes=file.metadata()?.len();
 let value:Value=serde_json::from_reader(BufReader::with_capacity(128*1024,file))?;let read_parse_us=started.elapsed().as_micros();
 ensure!(value["checkpoint_schema"]=="quant-persisted-v1"&&value["scope_key"]==key&&value["engine_build"]==*ENGINE_BUILD,"persisted checkpoint identity differs");
 let started=std::time::Instant::now();ensure!(value["state_sha256"]==content_hash(&value["state"])? ,"persisted checkpoint checksum differs");let state_hash_us=started.elapsed().as_micros();
 let started=std::time::Instant::now();let state=super::snapshot::SnapshotAccumulator::restore(value["state"].clone(),parameters)?;let restore_us=started.elapsed().as_micros();
 Ok((Some((state,value["complete"]==true)),json!({"state":"disk_checkpoint","bytes":bytes.to_string(),"read_parse_us":read_parse_us.to_string(),"state_hash_us":state_hash_us.to_string(),"typed_restore_us":restore_us.to_string()})))
}
fn load_checkpoint(key:&str,parameters:&Parameters)->Result<(Option<(super::snapshot::SnapshotAccumulator,bool)>,Value)>{load_checkpoint_file(&checkpoint_path(key),key,parameters)}

async fn snapshot(State(state):State<AppState>,Json(request):Json<QuantInputRequest>)->ApiResult{
 request.parameters.validate().map_err(error)?;let key=snapshot_key(&request).map_err(error)?;
 // One in-flight calculation per complete view scope; a new request after
 // completion revalidates the current source generation in another MVCC read.
 let mut scopes=BUILD_SCOPE.lock().expect("build scopes lock");
 if let Some(id)=scopes.get(&key){if let Some(job)=BUILD_JOBS.lock().expect("build jobs lock").get(id){if job.status.lock().expect("snapshot job status")["state"]=="building"{return Ok(Json(job.status.lock().expect("snapshot job status").clone()));}}}
 let permit=LIMIT.clone().try_acquire_owned().map_err(|_|ApiError(StatusCode::TOO_MANY_REQUESTS,"研究计算正在进行，请稍后刷新".into()))?;
 let id=uuid::Uuid::new_v4().to_string();let initial=json!({"state":"building","job_id":id,"processed_bars":"0","phase":"loading_checkpoint","complete":false});
 let job=Arc::new(SnapshotJob{cancel:AtomicBool::new(false),status:Mutex::new(initial.clone()),changed:Notify::new()});
 {let mut jobs=BUILD_JOBS.lock().expect("build jobs lock");if jobs.len()>=16{let remove:Vec<_>=jobs.iter().filter(|(_,v)|v.status.lock().unwrap()["state"]!="building").map(|(k,_)|k.clone()).take(jobs.len()-15).collect();for id in remove{jobs.remove(&id);}scopes.retain(|_,id|jobs.contains_key(id));}jobs.insert(id.clone(),job.clone());}
 scopes.insert(key.clone(),id.clone());drop(scopes);
 tokio::spawn(async move{let outcome=build_snapshot(&state,&request,&key,&job).await;drop(permit);match outcome{Ok(value)=>{let started=std::time::Instant::now();let ready=json!({"state":"ready","job_id":id,"complete":true,"processed_bars":value.evidence.confirmed_count.to_string(),"snapshot":value});let mut status=job.status.lock().expect("snapshot job status");let profile=status["profile"].clone();let basis=profile["chart_basis_hash"].clone();*status=ready;status["profile"]=profile;status["chart_basis_hash"]=basis;status["profile"]["response_materialize_us"]=json!(started.elapsed().as_micros().to_string());},Err(e)=>{let mut status=job.status.lock().expect("snapshot job status");status["state"]=json!(if job.cancel.load(Ordering::Relaxed){"cancelled"}else{"failed"});status["complete"]=json!(false);status["error"]=json!(e.to_string());}}job.changed.notify_waiters();});
 Ok(Json(initial))
}
#[derive(Deserialize,Default)]#[serde(default,deny_unknown_fields)]struct SnapshotWait{wait_ms:u64,known_chart_basis_hash:Option<String>}
async fn snapshot_status(Path(id):Path<String>,Query(wait):Query<SnapshotWait>)->ApiResult{let job=BUILD_JOBS.lock().expect("build jobs lock").get(&id).cloned().ok_or_else(||ApiError(StatusCode::NOT_FOUND,"该指标计算已结束并清理，请刷新".into()))?;
 if wait.wait_ms>0{let notified=job.changed.notified();tokio::pin!(notified);notified.as_mut().enable();let building=job.status.lock().expect("snapshot job status")["state"]=="building";if building{let _=tokio::time::timeout(std::time::Duration::from_millis(wait.wait_ms.min(2000)),notified).await;}}
 let status=job.status.lock().expect("snapshot job status");Ok(Json(snapshot_status_payload(&status,wait.known_chart_basis_hash.as_deref())))}
fn snapshot_status_payload(status:&Value,known_basis:Option<&str>)->Value {
 let basis=status["chart_basis_hash"].as_str();let snapshot=status["snapshot"].as_object();
 let mut value=if status["state"]=="ready"&&basis.is_some()&&known_basis==basis&&snapshot.is_some(){
  let metadata=snapshot.unwrap().iter().filter(|(key,_)|!matches!(key.as_str(),"bars"|"series")).map(|(key,value)|(key.clone(),value.clone())).collect::<serde_json::Map<_,_>>();
  json!({"state":"ready","job_id":status["job_id"],"complete":status["complete"],"processed_bars":status["processed_bars"],"chart_basis_hash":basis,"snapshot_delta":{"base_id":basis,"snapshot":metadata},"profile":status["profile"]})
 }else{status.clone()};value["long_poll"]=json!(true);value
}
fn chart_basis_hash(snapshot:&super::snapshot::QuantSnapshot,request:&QuantInputRequest)->Result<String>{
 let evidence=&snapshot.evidence;let token=&evidence.token;
 content_hash(&("quant-chart-basis-v1",&*ENGINE_BUILD,&request.code,&request.source_id,&request.period,request.start,request.end,&request.research_snapshot_id,&request.research_asset,&request.research_adjustment,(&evidence.confirmed_prefix_hash,evidence.schema_version,evidence.calculation_version,evidence.rounding_policy,&evidence.parameters,(&token.store_epoch,&token.capture_epoch,&token.schema_version,&token.projector_version,&token.aggregation_version,&token.catalog_version,&token.schedule_version,&token.route_version)),(&snapshot.bars,&snapshot.series)))
}
async fn snapshot_cancel(Path(id):Path<String>)->ApiResult{let job=BUILD_JOBS.lock().expect("build jobs lock").get(&id).cloned().ok_or_else(||ApiError(StatusCode::NOT_FOUND,"没有该指标计算".into()))?;job.cancel.store(true,Ordering::Relaxed);Ok(Json(json!({"job_id":id,"cancel_requested":true})))}
/// AI consumes a published immutable version; it never starts a long cold scan.
pub fn authority_version(request:&QuantInputRequest,input_hash:&str)->Result<super::snapshot::QuantSnapshot>{let versions=VERSIONS.lock().expect("snapshot versions lock");let published=versions.get(input_hash).context("该输入版本尚未就绪或已清理，请先刷新指标")?;let snapshot=&published.1;let scope=&published.2;ensure!(request.application_cursor.is_none_or(|cursor|scope.application_cursor==Some(cursor))&&request.start.is_none_or(|start|scope.start==Some(start))&&request.end.is_none_or(|end|scope.end==Some(end))&&request.research_adjustment.as_ref().is_none_or(|value|scope.research_adjustment.as_ref()==Some(value))&&request.research_asset.as_ref().is_none_or(|value|scope.research_asset.as_ref()==Some(value)),"AI requested cursor/range/research scope differs from the published authority");ensure!(snapshot.evidence.code==request.code&&request.source_id.as_ref().is_none_or(|source|*source==snapshot.evidence.source_id)&&snapshot.evidence.period==request.period&&snapshot.evidence.parameters==request.parameters&&request.decision_as_of.is_none_or(|cutoff|cutoff==snapshot.evidence.decision_as_of),"AI input version differs from the selected view");ensure!(request.research_snapshot_id.as_ref().is_none_or(|id|snapshot.evidence.token.store_epoch==format!("research-manifest:{id}")),"AI research authority differs from the selected manifest");Ok(snapshot.clone())}
async fn build_snapshot(state:&AppState,request:&QuantInputRequest,key:&str,job:&Arc<SnapshotJob>)->Result<super::snapshot::QuantSnapshot>{
 let total_started=std::time::Instant::now();let load_started=std::time::Instant::now();let cached=SNAPSHOTS.lock().expect("snapshots lock").get(key).map(|(_,acc)|acc.clone());let disk_key=key.to_owned();let parameters=request.parameters.clone();let (saved,load_profile)=if cached.is_none(){match tokio::task::spawn_blocking(move||load_checkpoint(&disk_key,&parameters)).await?{Ok(value)=>value,Err(error)=>{job.status.lock().unwrap()["checkpoint_discarded_reason"]=json!(error.to_string());(None,json!({"state":"discarded","reason":error.to_string()}))}}}else{(None,json!({"state":"memory_cache"}))};
 let load_us=load_started.elapsed().as_micros();let mut query=request.clone();let mut initial=super::snapshot::SnapshotAccumulator::new(request.parameters.clone())?;let mut prior_checkpoint=None;
 if let Some((cached,complete))=cached.map(|value|(value,true)).or(saved){if complete{prior_checkpoint=Some(cached.checkpoint_identity()?);}if let Some(resume)=cached.resume_cursor(){query.resume=Some(resume);initial=cached.resume();}}
 let mut result=scan_snapshot(state,&query,initial,key,job).await;
 if result.as_ref().is_err_and(|e|e.to_string().contains("quant_resume_invalid")){query.resume=None;result=scan_snapshot(state,&query,super::snapshot::SnapshotAccumulator::new(request.parameters.clone())?,key,job).await;}
 let accumulator=result?;ensure!(!job.cancel.load(Ordering::Relaxed),"cancelled");let checkpoint_started=std::time::Instant::now();let checkpoint_changed=prior_checkpoint.as_ref()!=Some(&accumulator.checkpoint_identity()?);let checkpoint_profile=if checkpoint_changed{let saved=accumulator.clone();let disk_key=key.to_owned();tokio::task::spawn_blocking(move||save_checkpoint_profile(&disk_key,&saved,true)).await??}else{Value::Null};let checkpoint_us=checkpoint_started.elapsed().as_micros();
 let render_started=std::time::Instant::now();let snapshot=accumulator.current()?;let render_us=render_started.elapsed().as_micros();let mut cache=SNAPSHOTS.lock().expect("snapshots lock");if cache.len()>=8{if let Some(old)=cache.iter().min_by_key(|(_,entry)|entry.0).map(|(k,_)|k.clone()){cache.remove(&old);}}cache.insert(key.into(),(std::time::Instant::now(),accumulator));drop(cache);
 let mut versions=VERSIONS.lock().expect("snapshot versions lock");if versions.len()>=16{if let Some(old)=versions.iter().min_by_key(|(_,entry)|entry.0).map(|(k,_)|k.clone()){versions.remove(&old);}}versions.insert(snapshot.evidence.input_hash.clone(),(std::time::Instant::now(),snapshot.clone(),request.clone()));drop(versions);let mut status=job.status.lock().unwrap();status["profile"]["chart_basis_hash"]=json!(chart_basis_hash(&snapshot,request)?);status["profile"]["load_checkpoint_us"]=json!(load_us.to_string());status["profile"]["load_checkpoint_detail"]=load_profile;status["profile"]["checkpoint_publish_us"]=json!(checkpoint_us.to_string());status["profile"]["checkpoint_rewritten"]=json!(checkpoint_changed);status["profile"]["checkpoint_detail"]=checkpoint_profile;status["profile"]["current_materialize_us"]=json!(render_us.to_string());status["profile"]["build_total_us"]=json!(total_started.elapsed().as_micros().to_string());Ok(snapshot)
}
async fn scan_snapshot(state:&AppState,request:&QuantInputRequest,initial:super::snapshot::SnapshotAccumulator,key:&str,job:&Arc<SnapshotJob>)->Result<super::snapshot::SnapshotAccumulator>{let accumulator=Arc::new(Mutex::new(Some(initial)));let worker=accumulator.clone();let key=key.to_owned();let job=job.clone();let profile_job=job.clone();let mut last_saved=worker.lock().unwrap().as_ref().unwrap().processed_bars();job.status.lock().unwrap()["phase"]=json!("preparing_input");let cancel_job=job.clone();let cancel=Arc::new(move||cancel_job.cancel.load(Ordering::Relaxed));let scan_started=std::time::Instant::now();let profile=Arc::new(Mutex::new((0_u128,0_usize,0_usize)));let batch_profile=profile.clone();let result=crate::quant_input::scan_controlled(state,request,256,cancel,move|input|{
 ensure!(!job.cancel.load(Ordering::Relaxed),"cancelled");let mut guard=worker.lock().expect("snapshot accumulator lock");let accumulator=guard.as_mut().unwrap();let immutable_research=input.capabilities.contains("research_immutable_manifest");let rows=input.bars.len();let evaluate_started=std::time::Instant::now();accumulator.push(input)?;{let mut profile=batch_profile.lock().unwrap();profile.0+=evaluate_started.elapsed().as_micros();profile.1+=rows;profile.2+=1;}let processed=accumulator.processed_bars();{let mut status=job.status.lock().expect("snapshot job status");status["processed_bars"]=json!(processed.to_string());status["phase"]=json!("evaluating");}
 if !immutable_research&&processed.saturating_sub(last_saved)>=5000{save_checkpoint(&key,accumulator,false)?;last_saved=processed;}Ok(())
 }).await?;ensure!(result.complete,"authority scan incomplete");{let profile=profile.lock().unwrap();let mut status=profile_job.status.lock().unwrap();status["profile"]=json!({"authority_scan_us":scan_started.elapsed().as_micros().to_string(),"evaluator_update_us":profile.0.to_string(),"delivered_rows":profile.1.to_string(),"batches":profile.2});}let result=accumulator.lock().expect("snapshot accumulator lock").take().unwrap();Ok(result)}

async fn list()->ApiResult{let result=tokio::task::spawn_blocking(move||->Result<Value>{let mut values=vec![];if root().exists(){for entry in fs::read_dir(root())?{let entry=entry?;if !entry.file_type()?.is_dir(){continue;}let Some(id)=entry.file_name().to_str().map(str::to_owned)else{continue;};if !valid_id(&id){continue;}if let Ok(value)=persisted(&id){values.push(value);}}}values.sort_by(|a,b|b["created_at"].as_str().cmp(&a["created_at"].as_str()));Ok(json!({"runs":values}))}).await.map_err(error)?.map_err(error)?;Ok(Json(result))}
async fn status(Path(id):Path<String>)->ApiResult{if let Some(job)=JOBS.lock().expect("jobs lock").get(&id).cloned(){return Ok(Json(job.status.lock().expect("job status lock").clone()));}let value=tokio::task::spawn_blocking(move||persisted(&id)).await.map_err(error)?.map_err(|_|ApiError(StatusCode::NOT_FOUND,"没有这次模拟结果".into()))?;Ok(Json(value))}
async fn cancel(Path(id):Path<String>)->ApiResult{let job=JOBS.lock().expect("jobs lock").get(&id).cloned().ok_or_else(||ApiError(StatusCode::NOT_FOUND,"该运行已结束或不在当前服务中".into()))?;job.cancel.store(true,Ordering::Relaxed);Ok(Json(json!({"id":id,"cancel_requested":true})))}
async fn events(Path(id):Path<String>,Query(query):Query<PageQuery>)->ApiResult{ensure_id(&id)?;let value=tokio::task::spawn_blocking(move||->Result<Value>{let manifest=persisted(&id)?;let pages=manifest["event_pages"].as_u64().unwrap_or(0);if query.page as u64>=pages{return Ok(json!({"page":query.page,"page_count":pages,"items":[],"has_next":false}));}let items=super::results::page(&root().join(id),query.page)?;Ok(json!({"page":query.page,"page_count":pages,"items":items,"has_next":query.page as u64+1<pages}))}).await.map_err(error)?.map_err(error)?;Ok(Json(value))}
fn ensure_id(id:&str)->Result<(),ApiError>{if valid_id(id){Ok(())}else{Err(error("invalid run id"))}}
async fn start(State(state):State<AppState>,Json(mut request):Json<RunRequest>)->ApiResult{
    ensure_simulation_context(&request.input).map_err(error)?;request.config.validate().map_err(error)?;request.input.parameters=request.config.parameters.clone();request.input.start=request.config.start;request.input.end=request.config.end;request.input.decision_as_of=request.config.end.or(request.input.decision_as_of);
    let permit=LIMIT.clone().try_acquire_owned().map_err(|_|ApiError(StatusCode::TOO_MANY_REQUESTS,"最多同时运行两次研究计算".into()))?;
    let saved_source=if let Some(base)=request.base_run_id.clone(){ensure_id(&base)?;let base_for_read=base.clone();let (manifest,input)=tokio::task::spawn_blocking(move||->Result<_>{let manifest=persisted(&base_for_read)?;let input=super::results::saved_run_input(&root().join(&base_for_read),&manifest)?;Ok((manifest,input))}).await.map_err(error)?.map_err(error)?;
        ensure_saved_scope(&request,&manifest,&input).map_err(error)?;let mut fixed:QuantInputRequest=serde_json::from_value(manifest["request"].clone()).map_err(error)?;fixed.parameters=request.config.parameters.clone();fixed.decision_as_of=Some(input.decision_as_of);fixed.application_cursor=input.application_cursor;request.input=fixed;
        let expected=manifest["input_hash"].as_str().ok_or_else(||error("source run input version missing"))?.to_owned();if request.expected_input_hash.as_ref().is_some_and(|value|value!=&expected){return Err(error("comparison requested input differs from source run"));}request.expected_input_hash=Some(expected);Some((root().join(&base),manifest))
    }else{None};
    let id=uuid::Uuid::new_v4().to_string();let directory=root().join(&id);create_directory(&directory).map_err(error)?;let initial=json!({"id":id,"status":"running","phase":if saved_source.is_some(){"saved_authority_scan"}else{"snapshot_scan"},"base_run_id":request.base_run_id,"fixed_market_data_sha256":saved_source.as_ref().map(|(_,manifest)|manifest["canonical_file_sha256"].clone()),"base_input_hash":saved_source.as_ref().map(|(_,manifest)|manifest["input_hash"].clone()),"created_at":chrono::Utc::now(),"processed_bars":"0","event_pages":0,"complete":false,"durability_scope":durability_scope(),"request":request.input,"config":request.config});
    let job=Arc::new(Job{cancel:AtomicBool::new(false),status:Mutex::new(initial.clone()),directory});
    {let mut jobs=JOBS.lock().expect("jobs lock");jobs.retain(|_,j|j.status.lock().expect("status lock")["status"]=="running");jobs.insert(id.clone(),job.clone());}
    if let Err(failure)=publish(&job,initial.clone()){JOBS.lock().expect("jobs lock").remove(&id);return Err(error(failure));}
    tokio::spawn(async move{let (sender,receiver)=mpsc::channel::<ScanMessage>(2);let worker_job=job.clone();let expected=request.expected_input_hash.clone();let config=request.config.clone();let worker=tokio::task::spawn_blocking(move||process(receiver,&worker_job,config,expected));let batch_sender=sender.clone();let scan_job=job.clone();let cancel_job=job.clone();let cancel=Arc::new(move||cancel_job.cancel.load(Ordering::Relaxed));let accept=move|input|{ensure!(!scan_job.cancel.load(Ordering::Relaxed),"cancelled");batch_sender.blocking_send(ScanMessage::Batch(input)).context("research consumer stopped")};let scan=if let Some((directory,manifest))=saved_source{tokio::task::spawn_blocking(move||super::results::scan_saved_run(&directory,&manifest,256,move||cancel(),accept)).await.map_err(anyhow::Error::from).and_then(|result|result)}else{crate::quant_input::scan_controlled(&state,&request.input,256,cancel,accept).await};
        let _=sender.send(ScanMessage::Complete(scan.map_err(|e|e.to_string()))).await;drop(sender);let outcome=worker.await;drop(permit);if let Err(error)=outcome{let mut current=job.status.lock().expect("status lock").clone();current["status"]=json!("failed");current["error"]=json!(format!("research worker failed: {error}"));let _=publish(&job,current);}});
    Ok(Json(initial))
}
fn ensure_simulation_context(input:&QuantInputRequest)->Result<()>{ensure!(input.application_cursor.is_none(),"原始消息回放游标不能用于最终修订历史模拟；当前尚未提供逐消息成交执行器，请回到实时后运行明确标注的历史模拟");Ok(())}
fn ensure_saved_scope(request:&RunRequest,manifest:&Value,input:&QuantInput)->Result<()>{
 let original:QuantInputRequest=serde_json::from_value(manifest["request"].clone())?;let config:SimulationConfig=serde_json::from_value(manifest["config"].clone())?;
 ensure!(request.input.code==input.code&&request.input.period==input.period&&request.input.source_id.as_ref().is_none_or(|source|source==&input.source_id)&&request.input.research_snapshot_id==original.research_snapshot_id&&request.input.research_asset==original.research_asset&&request.input.research_adjustment==original.research_adjustment,"comparison source differs from selected instrument/source/period/research authority");
 ensure!(request.config.start==config.start&&request.config.end==config.end,"固定数据比较保留原运行范围；请恢复原开始和结束时刻后修改费用或策略参数");Ok(())
}
enum ScanMessage{Batch(QuantInput),Complete(std::result::Result<CanonicalScanSummary,String>)}
fn process(mut receiver:mpsc::Receiver<ScanMessage>,job:&Job,config:SimulationConfig,expected:Option<String>)->Result<()>{let result=process_inner(&mut receiver,job,config,expected);if let Err(e)=&result{let mut current=job.status.lock().expect("status lock").clone();current["status"]=json!(if job.cancel.load(Ordering::Relaxed){"cancelled"}else{"failed"});current["phase"]=json!("stopped");current["error"]=json!(e.to_string());current["complete"]=json!(false);publish(job,current)?;}result}
fn process_inner(receiver:&mut mpsc::Receiver<ScanMessage>,job:&Job,config:SimulationConfig,expected:Option<String>)->Result<()>{let mut simulator=None;let mut prefix=None;let mut context=None;let mut completion=None;let mut writer=EventWriter::new(job.directory.clone());let mut canonical=BufWriter::new(fs::File::create(job.directory.join("canonical-input.jsonl"))?);let mut processed=0_u64;let mut canonical_hash=Sha256::new();
    while let Some(message)=receiver.blocking_recv(){match message{ScanMessage::Batch(mut input)=>{ensure!(!job.cancel.load(Ordering::Relaxed),"cancelled");input.validate()?;if context.is_none(){prefix=Some(PrefixHash::new(&input,&config.parameters)?);simulator=Some(Simulator::new(config.clone(),input.semantics.clone())?);let bars=std::mem::take(&mut input.bars);write_canonical(&mut canonical,&mut canonical_hash,&json!({"metadata":input}))?;input.bars=bars;}
        if let Some(previous)=&context{let previous:&QuantInput=previous;ensure!(content_hash(&previous.token)?==content_hash(&input.token)?&&previous.code==input.code&&previous.source_id==input.source_id&&previous.period==input.period&&previous.decision_as_of==input.decision_as_of&&previous.semantics==input.semantics,"simulation batches changed authority MVCC identity");}
        let mut metadata=input.clone();metadata.bars.clear();context=Some(metadata);for bar in input.bars{if job.cancel.load(Ordering::Relaxed){writer.flush()?;canonical.flush()?;let mut current=job.status.lock().expect("status lock").clone();current["processed_bars"]=json!(processed.to_string());current["event_pages"]=json!(writer.pages);publish(job,current)?;anyhow::bail!("cancelled");}if bar.state!="final"||(input.semantics==HistorySemantics::OriginalEventReplay&&bar.finalized_at.is_none())||bar.bucket_end>input.decision_as_of||(input.semantics==HistorySemantics::OriginalEventReplay&&bar.known_at(&input.semantics)>input.decision_as_of)||input.application_cursor.is_some_and(|seq|bar.applied_frame_seq.is_none_or(|at|at>seq)){continue;}write_canonical(&mut canonical,&mut canonical_hash,&bar)?;let prefix=prefix.as_mut().unwrap();prefix.push(&bar)?;let metadata=context.as_ref().unwrap();let(_,version)=prefix.finish(metadata,bar.known_at(&metadata.semantics),if metadata.semantics==HistorySemantics::OriginalEventReplay{bar.applied_frame_seq}else{None})?;let mut events=simulator.as_mut().unwrap().push(bar,version)?;
            for event in &mut events{if let LedgerEvent::Decision(point)=event{external_context(point,metadata);}}
            for event in events{writer.push(event)?;}processed+=1;}
        writer.flush()?;canonical.flush()?;let mut current=job.status.lock().expect("status lock").clone();current["processed_bars"]=json!(processed.to_string());current["event_pages"]=json!(writer.pages);current["phase"]=json!("evaluating");current["snapshot_token"]=serde_json::to_value(&input.token)?;publish(job,current)?;
    },ScanMessage::Complete(result)=>{completion=Some(result.map_err(anyhow::Error::msg)?);break;}}}
    let summary=completion.context("MVCC scan ended without completion")?;ensure!(summary.complete,"incomplete authority scan");ensure!(!job.cancel.load(Ordering::Relaxed),"cancelled");let context=context.context("missing authority snapshot context")?;let prefix=prefix.context("missing canonical prefix")?;let(input_hash,snapshot_hash)=prefix.finish(&context,context.decision_as_of,context.application_cursor)?;ensure!(expected.as_ref().is_none_or(|value|value==&input_hash),"input version changed; results are not comparable to the requested input");let (ledger,events)=simulator.context("missing simulation")?.finish()?;for event in events{writer.push(event)?;}writer.flush()?;canonical.flush()?;canonical.get_ref().sync_all()?;sync_directory(&job.directory)?;
    let run_hash=config.hash(&input_hash)?;let mut current=job.status.lock().expect("status lock").clone();current["status"]=json!("completed");current["phase"]=json!("finished");current["complete"]=json!(true);current["processed_bars"]=json!(processed.to_string());current["event_pages"]=json!(writer.pages);current["event_count"]=json!(writer.events.to_string());let canonical_file_hash=hex::encode(canonical_hash.finalize());current["canonical_file_sha256"]=json!(canonical_file_hash);current["market_data_hash"]=json!(canonical_file_hash);current["event_pages_sha256_chain"]=json!(writer.checksum());current["canonical_file_bytes"]=json!(canonical.get_ref().metadata()?.len().to_string());current["input_hash"]=json!(input_hash);current["snapshot_hash"]=json!(snapshot_hash);current["run_hash"]=json!(run_hash);current["scan"]=serde_json::to_value(summary)?;current["semantics"]=serde_json::to_value(context.semantics)?;current["warmup_complete"]=json!(context.warmup_complete);current["summary"]=serde_json::to_value(ledger)?;current["completed_at"]=json!(chrono::Utc::now());publish(job,current)?;Ok(())
}

async fn audit(Path(id):Path<String>)->ApiResult{ensure_id(&id)?;let value=tokio::task::spawn_blocking(move||{let manifest=persisted(&id)?;super::results::audit(&root().join(id),&manifest)}).await.map_err(error)?.map_err(error)?;Ok(Json(value))}

#[cfg(test)]mod authority_scope_tests{
 use super::*;
 #[test]fn chart_delta_is_exact_full_metadata_and_requires_matching_actual_projection(){
  let mut input:QuantInput=serde_json::from_value(json!({"code":"DELTA-SCOPE-TEST","instrument":"TEST","name":"delta fixture","unit":"test","executable_contract":false,"source_id":"fixture","period":"1m","decision_as_of":"2026-10-01T00:03:00Z","application_cursor":null,"token":{"store_epoch":"delta-store","commit_id":"1","aggregation_version":"fixed","schema_version":"fixed","projector_version":"fixed","committed_frame_seq":"10","catalog_version":"fixed","schedule_version":"calendar1","route_version":"fixed"},"semantics":"final_revision_history","capabilities":[],"warmup_complete":false,"bars":[{"open_time":"2026-10-01T00:00:00Z","bucket_end":"2026-10-01T00:01:00Z","open":"100","high":"102","low":"99","close":"101","volume":null,"known_volume_sum":"0","known_volume_count":"0","component_count":"1","state":"final","revision":"1","observed_at":"2026-10-01T00:01:00Z","received_at":"2026-10-01T00:01:00Z","finalized_at":null,"applied_frame_seq":null,"source_precision_ns":null}],"external_facts":[]})).unwrap();
  let p=Parameters::default();let compute=|input:QuantInput|{let mut acc=super::super::snapshot::SnapshotAccumulator::new(p.clone()).unwrap();acc.push(input).unwrap();acc.current().unwrap()};
  let base=compute(input.clone());let request=QuantInputRequest{code:input.code.clone(),source_id:Some(input.source_id.clone()),period:input.period.clone(),parameters:p.clone(),..Default::default()};let basis=chart_basis_hash(&base,&request).unwrap();let original=serde_json::to_value(&base).unwrap();
  let equal=|snapshot:&super::super::snapshot::QuantSnapshot|{
   let next=chart_basis_hash(snapshot,&request).unwrap();assert_eq!(next,basis);let status=json!({"state":"ready","job_id":"fixed","complete":true,"processed_bars":"1","chart_basis_hash":next,"snapshot":snapshot});let delta=snapshot_status_payload(&status,Some(&basis));assert!(delta.get("snapshot").is_none());assert_eq!(delta["snapshot_delta"]["base_id"],basis);let mut merged=delta["snapshot_delta"]["snapshot"].clone();for field in ["bars","series"]{merged[field]=original[field].clone();}assert_eq!(merged,status["snapshot"]);assert_eq!(snapshot_status_payload(&status,None)["snapshot"],status["snapshot"]);assert_eq!(snapshot_status_payload(&status,Some("lost-base"))["snapshot"],status["snapshot"]);
  };
  equal(&base);input.decision_as_of+=chrono::Duration::seconds(1);input.token.commit_id=2;equal(&compute(input.clone()));input.quote=Some(serde_json::from_value(json!({"price":"101.0000000000000000000000000001","observed_at":"2026-10-01T00:02:00Z","received_at":"2026-10-01T00:02:00.000000001Z","applied_frame_seq":null,"source_precision_ns":null})).unwrap());equal(&compute(input.clone()));
  let mut forming=input.bars[0].clone();forming.open_time+=chrono::Duration::minutes(1);forming.bucket_end+=chrono::Duration::minutes(1);forming.state="forming".into();input.bars.push(forming);equal(&compute(input.clone()));input.bars[1].close=super::super::exact::d("100");equal(&compute(input.clone()));input.bars[1].state="final".into();assert_ne!(chart_basis_hash(&compute(input.clone()),&request).unwrap(),basis);
  input.bars.pop();input.bars[0].revision+=1;assert_ne!(chart_basis_hash(&compute(input.clone()),&request).unwrap(),basis);input.bars[0].revision-=1;input.token.schedule_version="calendar2".into();assert_ne!(chart_basis_hash(&compute(input.clone()),&request).unwrap(),basis);
  let mut changed=base.clone();changed.series[0].indicators.insert("preview-influence".into(),json!("1"));assert_ne!(chart_basis_hash(&changed,&request).unwrap(),basis);let mut range=request.clone();range.start=Some(input.decision_as_of);assert_ne!(chart_basis_hash(&base,&range).unwrap(),basis);
  let mut source=base.clone();source.bars[0].source_volume_components=Some(SourceVolumeComponents{known_volume_sum:super::super::exact::d("2"),known_count:1,total_count:2,policy:"fuyao-source-field-13-interval-v1".into()});assert_ne!(chart_basis_hash(&source,&request).unwrap(),basis);
  for field in ["aggregation","catalog","schema","projector"]{let mut version=base.clone();match field{"aggregation"=>version.evidence.token.aggregation_version="new".into(),"catalog"=>version.evidence.token.catalog_version="new".into(),"schema"=>version.evidence.token.schema_version="new".into(),_=>version.evidence.token.projector_version="new".into()};assert_ne!(chart_basis_hash(&version,&request).unwrap(),basis);}
 }
 #[test]#[ignore="explicit read-only actual checkpoint I/O profile"]fn checkpoint_buffered_io_profile(){
  let path=PathBuf::from(std::env::var("QUANT_CHECKPOINT_PROFILE_FILE").expect("explicit checkpoint path required"));let before=fs::metadata(&path).unwrap();let mut samples=vec![];let mut expected=None;
  for buffered in [false,true,false,true]{let started=std::time::Instant::now();let file=fs::File::open(&path).unwrap();let value:Value=if buffered{serde_json::from_reader(BufReader::with_capacity(128*1024,file)).unwrap()}else{serde_json::from_reader(file).unwrap()};let read_parse_us=started.elapsed().as_micros();if let Some(previous)=&expected{assert_eq!(previous,&value);}else{expected=Some(value.clone());}
   assert_eq!(value["checkpoint_schema"],"quant-persisted-v1");let started=std::time::Instant::now();assert_eq!(value["state_sha256"],content_hash(&value["state"]).unwrap());let state_hash_us=started.elapsed().as_micros();let parameters:Parameters=serde_json::from_value(value["state"]["state"]["parameters"].clone()).unwrap();let started=std::time::Instant::now();let restored=super::super::snapshot::SnapshotAccumulator::restore(value["state"].clone(),&parameters).unwrap();let restore_us=started.elapsed().as_micros();samples.push(json!({"buffered":buffered,"read_parse_us":read_parse_us.to_string(),"state_hash_us":state_hash_us.to_string(),"typed_restore_us":restore_us.to_string(),"confirmed_count":restored.processed_bars().to_string()}));
  }
  let after=fs::metadata(&path).unwrap();assert_eq!(before.len(),after.len());assert_eq!(before.modified().unwrap(),after.modified().unwrap());println!("CHECKPOINT_IO_PROFILE {}",json!({"path":path,"bytes":before.len().to_string(),"conditions":"same real fixed33 checkpoint, read-only alternating unbuffered/buffered, OS cache warm; source build identity intentionally not reused by this diagnostic","samples":samples}));
 }
 #[test]fn buffered_checkpoint_restore_keeps_identity_checksum_and_parameter_guards(){
  let directory=tempfile::tempdir().unwrap();let path=directory.path().join("checkpoint.json");let parameters=Parameters::default();
  let accumulator=super::super::snapshot::SnapshotAccumulator::new(parameters.clone()).unwrap();let state=accumulator.snapshot().unwrap();
  let value=json!({"checkpoint_schema":"quant-persisted-v1","scope_key":"fixed-scope","engine_build":&*ENGINE_BUILD,"state_sha256":content_hash(&state).unwrap(),"complete":false,"state":state});atomic_json(&path,&value).unwrap();
  let (restored,profile)=load_checkpoint_file(&path,"fixed-scope",&parameters).unwrap();let(restored,complete)=restored.unwrap();assert!(!complete);assert_eq!(restored.snapshot().unwrap(),accumulator.snapshot().unwrap());assert_eq!(profile["bytes"],fs::metadata(&path).unwrap().len().to_string());for key in ["read_parse_us","state_hash_us","typed_restore_us"]{assert!(profile[key].as_str().unwrap().parse::<u128>().is_ok());}
  assert!(load_checkpoint_file(&path,"different-scope",&parameters).is_err());let mut changed=parameters.clone();changed.rsi_period+=1;assert!(load_checkpoint_file(&path,"fixed-scope",&changed).is_err());
  let mut tampered=value;tampered["state"]["state"]["input_count"]=json!(1);atomic_json(&path,&tampered).unwrap();assert!(load_checkpoint_file(&path,"fixed-scope",&parameters).err().unwrap().to_string().contains("checksum"));
 }
 #[test]fn simulation_rejects_original_event_cursor_instead_of_substituting_live_history(){let mut request=QuantInputRequest::default();assert!(ensure_simulation_context(&request).is_ok());request.application_cursor=Some(1);assert!(ensure_simulation_context(&request).unwrap_err().to_string().contains("逐消息成交执行器"));assert!(serde_json::from_value::<RunRequest>(json!({"input":{"code":"XAUUSD","period":"1m"},"config":SimulationConfig::default(),"replay_session_id":"raw-session"})).is_err());}
 #[tokio::test]async fn snapshot_long_poll_wakes_on_publication(){
  let id=uuid::Uuid::new_v4().to_string();let job=Arc::new(SnapshotJob{cancel:AtomicBool::new(false),status:Mutex::new(json!({"state":"building","job_id":id})),changed:Notify::new()});BUILD_JOBS.lock().unwrap().insert(id.clone(),job.clone());tokio::spawn(async move{tokio::time::sleep(std::time::Duration::from_millis(10)).await;*job.status.lock().unwrap()=json!({"state":"ready","complete":true});job.changed.notify_waiters();});let result=tokio::time::timeout(std::time::Duration::from_secs(1),snapshot_status(Path(id.clone()),Query(SnapshotWait{wait_ms:2000,..Default::default()}))).await.unwrap().unwrap_or_else(|error|panic!("{}",error.1));assert_eq!(result.0["state"],"ready");assert_eq!(result.0["long_poll"],true);BUILD_JOBS.lock().unwrap().remove(&id);
 }
 #[test]fn explicit_cursor_range_and_research_scope_reject_old_published_authority(){
  let at="2026-10-01T00:00:00Z".parse().unwrap();let mut input:QuantInput=serde_json::from_value(json!({"code":"AUTHORITY-SCOPE-TEST","instrument":"TEST","name":"authority scope fixed test","unit":"test","executable_contract":false,"source_id":"fixture","period":"1m","decision_as_of":at,"application_cursor":"7","token":{"store_epoch":"scope-test","commit_id":"1","aggregation_version":"fixed","schema_version":"fixed","projector_version":"fixed","committed_frame_seq":"10","catalog_version":"fixed","schedule_version":"fixed","route_version":"fixed"},"semantics":"original_event_replay","capabilities":[],"warmup_complete":false,"bars":[],"external_facts":[]})).unwrap();input.semantics=HistorySemantics::OriginalEventReplay;input.application_cursor=Some(7);let snapshot=super::super::snapshot::evaluate(&input,&Parameters::default()).unwrap();let scope=QuantInputRequest{code:input.code.clone(),source_id:Some(input.source_id.clone()),period:input.period.clone(),application_cursor:Some(7),start:Some(at),research_asset:Some("future".into()),research_adjustment:Some("raw".into()),..Default::default()};let hash=snapshot.evidence.input_hash.clone();VERSIONS.lock().unwrap().insert(hash.clone(),(std::time::Instant::now(),snapshot,scope.clone()));assert!(authority_version(&scope,&hash).is_ok());let mut other=scope.clone();other.application_cursor=Some(8);assert!(authority_version(&other,&hash).is_err());other=scope.clone();other.start=Some(at+chrono::Duration::days(1));assert!(authority_version(&other,&hash).is_err());other=scope;other.research_adjustment=Some("forward".into());assert!(authority_version(&other,&hash).is_err());VERSIONS.lock().unwrap().remove(&hash);
 }
}
