//! Isolated retained-prefix reconciliation pilot. No production write or activation.
#[path="../src/capture.rs"]mod capture;
#[path="../src/catalog.rs"]mod catalog;
#[path="../src/providers/mod.rs"]mod providers;
#[path="../src/quotes.rs"]mod quotes;
#[path="../src/replay.rs"]mod replay;
#[path="../src/legacy_import.rs"]mod legacy_import;
#[path="../src/legacy_reconcile.rs"]mod legacy_reconcile;
mod api {
 use std::sync::Arc;use axum::{http::StatusCode,response::{IntoResponse,Response}};
 #[derive(Clone)]pub struct Market{pub catalog:Arc<crate::catalog::Catalog>,pub store:tracefang_core::native_store::Store}
 impl Market{pub fn source(&self,code:&str)->anyhow::Result<String>{Ok(self.catalog.get(code)?.source_ids[0].clone())}}
 #[derive(Clone)]pub struct AppState{pub market:Market,pub capture:crate::capture::Capture,pub shutdown:tokio::sync::watch::Receiver<bool>}
 pub struct ApiError(pub StatusCode,pub String);impl From<anyhow::Error> for ApiError{fn from(error:anyhow::Error)->Self{Self(StatusCode::BAD_GATEWAY,error.to_string())}}
 impl IntoResponse for ApiError{fn into_response(self)->Response{(self.0,self.1).into_response()}}
}
mod pages {pub fn schedule(market:&crate::api::Market,code:&str)->anyhow::Result<tracefang_core::periods::MarketSchedule>{Ok(serde_json::from_value(market.catalog.schedules[&market.catalog.get(code)?.market_schedule_id].clone())?)}}
use anyhow::{Result,Context,ensure};use serde_json::{Value,json};use sha2::{Digest,Sha256};
use std::{path::{Path,PathBuf},sync::Arc,io::{BufRead,BufReader,BufWriter,Write},fs::File};
use tracefang_core::{native_store::{Store,CanonicalBarKey},persistence_contract::*,periods::Period};
use legacy_reconcile::BarChoice;
fn check(path:&Path)->Result<()>{ensure!(capture::available_bytes(path.parent().context("reconciliation path parent missing")?)?>4*1024*1024*1024,"reconciliation stopped below 4GiB free; preserved evidence");ensure!(std::fs::metadata(path)?.len()<4*1024*1024*1024,"disposable scope facts exceeds 4GiB pilot bound");Ok(())}
fn context(manifest:&legacy_import::LegacyManifest)->Result<ImportContext>{Ok(ImportContext{origin_id:manifest.id.clone(),source_fingerprint:manifest.postgres["fingerprint"].as_str().context("fixed input fingerprint missing")?.into(),schema_version:SCHEMA_VERSION.into(),range_label:"isolated_retained_prefix_reconciliation_pilot".into(),legacy_cursor:None,expected_sha256:None})}
fn semantic(mut value:Value)->Value{value.as_object_mut().unwrap().remove("evidence");if let Some(raw)=value["source_metadata"]["raw_payload"].as_object_mut(){raw.remove("applied_commit_id");}value}
fn private_file(path:&Path)->Result<File>{let file=std::fs::OpenOptions::new().write(true).create_new(true).open(path)?;#[cfg(unix)]{use std::os::unix::fs::PermissionsExt;file.set_permissions(std::fs::Permissions::from_mode(0o600))?;}Ok(file)}
fn line(file:&mut BufWriter<File>,value:&Value)->Result<()>{serde_json::to_writer(&mut *file,value)?;file.write_all(b"\n")?;Ok(())}
#[tokio::main]async fn main()->Result<()>{
 let args=std::env::args().skip(1).collect::<Vec<_>>();ensure!(args.len()==7,"pilot only: source-dir facts-file raw-file symbol source native-through report-file; terminal reconcile is a separate guarded phase");
 let source=Path::new(&args[0]);let manifest:legacy_import::LegacyManifest=serde_json::from_reader(File::open(source.join("manifest.json"))?)?;
 let through:u64=args[5].parse()?;ensure!(through>0,"pilot requires an inclusive raw prefix");let report=PathBuf::from(&args[6]);let root=report.parent().context("pilot evidence parent missing")?;std::fs::create_dir_all(root)?;
 let started=std::time::Instant::now();let started_at=chrono::Utc::now();
 let evidence=source.parent().context("private source parent absent")?.join("reconciliation-pilot").join(uuid::Uuid::new_v4().to_string());std::fs::create_dir_all(&evidence)?;#[cfg(unix)]{use std::os::unix::fs::PermissionsExt;std::fs::set_permissions(&evidence,std::fs::Permissions::from_mode(0o700))?;}
 let decode_error_path=evidence.join("decode-errors.ndjson");let mut decode_evidence=BufWriter::new(private_file(&decode_error_path)?);let mut decode_reason_counts=std::collections::BTreeMap::<String,u64>::new();
 let pg=Store::open_read_only(&args[1])?.read_generation(&format!("legacy-{}",manifest.id)).await?;let pg_before=pg.version().await?;
 let capture=capture::Capture::open_read_only(&args[2])?;let bounds=capture.bounds().await?;let epoch=bounds["epoch"].as_str().context("capture epoch missing")?.to_owned();let tail=capture.get(through).await?;
 let cache=std::env::var_os("TRACEFANG_RECONCILE_CACHE_DIR").map(PathBuf::from).unwrap_or_else(||std::env::temp_dir().join("tracefang-reconcile-pilot"));std::fs::create_dir_all(&cache)?;let temporary=tempfile::Builder::new().prefix("scope-").tempdir_in(&cache)?;
 let derived_path=temporary.path().join("retained-facts.redb");let derived=Store::open_replay(&derived_path)?;
 let catalog=Arc::new(catalog::Catalog::embedded()?);let definition=catalog.get(&args[3])?.clone();let schedule=serde_json::from_value(catalog.schedules[&definition.market_schedule_id].clone())?;
 let canonical_symbol=definition.instrument.symbol.clone();let mut projector=replay::Projector::new_facts(catalog,definition.instrument,args[4].clone(),Period::M1,schedule)?;let open_ms=started.elapsed().as_secs_f64()*1000.;let(mut decode_reduce_lookup_ms,mut projection_commit_ms)=(0f64,0f64);let(mut next,mut frames,mut effective,mut decode_errors)=(1u64,0u64,0u64,0u64);
 while next<=through {
  check(&derived_path)?;let rows=capture.scan(&epoch,next,through.checked_add(1),64,4*1024*1024).await?;ensure!(!rows.is_empty(),"retained prefix contains a gap");let last=rows.last().unwrap().position.sequence;let phase=std::time::Instant::now();let(returned,commits)=replay::retained_projection_group(projector,rows,&derived).await?;decode_reduce_lookup_ms+=phase.elapsed().as_secs_f64()*1000.;projector=returned;
  let mut batch=Vec::new();let mut bytes=0usize;
  for commit in commits{frames+=1;effective+=u64::from(!commit.bars.is_empty()||!commit.quotes.is_empty());decode_errors+=commit.errors.len() as u64;for error in &commit.errors{line(&mut decode_evidence,error)?;*decode_reason_counts.entry(error["decode_diagnostic"].as_str().unwrap_or("diagnostic unavailable").to_owned()).or_default()+=1;}let size=serde_json::to_vec(&commit)?.len();if !batch.is_empty()&&(batch.len()==64||bytes+size>4*1024*1024){let phase=std::time::Instant::now();derived.commit_replay_frames(std::mem::take(&mut batch)).await?;projection_commit_ms+=phase.elapsed().as_secs_f64()*1000.;bytes=0;}bytes+=size;batch.push(commit);}
  if !batch.is_empty(){let phase=std::time::Instant::now();derived.commit_replay_frames(batch).await?;projection_commit_ms+=phase.elapsed().as_secs_f64()*1000.;}if last==through{break}next=last.checked_add(1).context("pilot cursor exhausted")?;
 }
 ensure!(frames==through&&derived.version().await?.committed_capture.as_ref()==Some(&tail.position),"pilot missed a raw prefix frame");
 decode_evidence.flush()?;decode_evidence.get_ref().sync_all()?;drop(decode_evidence);let derived_bytes=std::fs::metadata(&derived_path)?.len();let projection_ms=started.elapsed().as_secs_f64()*1000.;
 let pilot_path=temporary.path().join("composite-facts.redb");let pilot=Store::open(&pilot_path)?.staging("isolated-composite-pilot").await?;let comparison_started=std::time::Instant::now();let(mut pg_key_lookup_ms,mut selected_import_ms)=(0f64,0f64);let expected_path=evidence.join(format!("{}.expected.ndjson",report.file_stem().unwrap().to_string_lossy()));let comparison_path=evidence.join("comparison.ndjson");let overlay_path=evidence.join("overlay.ndjson");
 let mut expected=BufWriter::new(private_file(&expected_path)?);let mut comparison=BufWriter::new(private_file(&comparison_path)?);let mut overlay=BufWriter::new(private_file(&overlay_path)?);
 let(mut checked,mut preserved,mut replaced,mut unresolved,mut selected_rows)=(0u64,0u64,0u64,0u64,0u64);let mut reason_counts=std::collections::BTreeMap::<String,u64>::new();let mut row_offset=0u64;
 for interval in [1,60] {
  let(sender,mut receiver)=tokio::sync::mpsc::channel(2);let source_id=args[4].clone();let symbol=canonical_symbol.clone();let scan=CanonicalScanRequest{symbol,source_id,interval_seconds:interval,start_ns:i64::MIN,end_ns:i64::MAX,final_only:false,expected_version:Some(derived.version().await?)};let input=derived.clone();
  let producer=tokio::spawn(async move{input.canonical_scan(scan,1000,move|batch|{sender.blocking_send(batch).context("pilot comparison receiver closed")}).await});
  while let Some(batch)=receiver.recv().await {
   check(&pilot_path)?;let keys=batch.rows.iter().map(|r|CanonicalBarKey{source_id:r.realtime_source_id.clone(),symbol:r.instrument_symbol.clone(),interval_seconds:r.interval_seconds,open_time_ns:r.open_time_ns}).collect();let phase=std::time::Instant::now();let(version,old)=pg.lookup_bars(keys).await?;pg_key_lookup_ms+=phase.elapsed().as_secs_f64()*1000.;ensure!(json!(version)==json!(pg_before),"PG authority changed during read-only pilot");
   let mut chosen=Vec::new();
   for(raw,old)in batch.rows.into_iter().zip(old){checked+=1;let choice=legacy_reconcile::choose_bar(old.as_ref(),&raw)?;let(reason,mut selected,is_overlay)=match choice{BarChoice::Preserve(reason)=>{preserved+=1;(reason,old.clone().context("preserved absent PG fact")?,false)},BarChoice::Replace{row,reason}=>{replaced+=1;(reason,row,true)},BarChoice::Unresolved(reason)=>{unresolved+=1;line(&mut comparison,&json!({"key":[raw.realtime_source_id,raw.instrument_symbol,raw.interval_seconds,raw.open_time_ns.to_string()],"reason":reason,"state":"unresolved","pg":old,"raw":raw}))?;let Some(existing)=old.clone()else{continue};(reason,existing,false)}};
    *reason_counts.entry(reason.into()).or_default()+=1;let old_hash=old.as_ref().map(|r|serde_json::to_vec(r).map(|b|hex::encode(Sha256::digest(b)))).transpose()?;
    let witness=json!({"initial_seed":"empty retained prefix; PG used only for authority selection","raw_position":raw.source_metadata["raw_payload"]["capture_sequence"],"raw_digest":raw.source_metadata["raw_payload"]["capture_digest"],"source_manifest_id":manifest.id,"original_pg_sha256":old_hash,"reason":reason});selected.evidence["retained_raw_reconciliation"]=witness.clone();
    line(&mut comparison,&json!({"key":[selected.realtime_source_id,selected.instrument_symbol,selected.interval_seconds,selected.open_time_ns.to_string()],"before_sha256":old_hash,"after_semantic_sha256":hex::encode(Sha256::digest(serde_json::to_vec(&semantic(json!(&selected)))?)),"reason":reason,"raw_witness":witness}))?;
    if is_overlay{line(&mut overlay,&json!({"kind":"bar","before":old,"after":selected,"raw_witness":witness}))?;}
    line(&mut expected,&json!(&selected))?;chosen.push(selected);selected_rows+=1;
   }
   if !chosen.is_empty(){let phase=std::time::Instant::now();pilot.import_bars(ImportBatch{context:context(&manifest)?,row_offset,rows:chosen}).await?;selected_import_ms+=phase.elapsed().as_secs_f64()*1000.;row_offset=checked;}
  }producer.await??;
 }
 for file in [&mut expected,&mut comparison,&mut overlay]{file.flush()?;file.get_ref().sync_all()?;}drop(expected);drop(comparison);drop(overlay);
 ensure!(checked>0,"retained pilot scope produced no affected facts; cannot claim reconciliation");let pg_comparison_and_selection_ms=comparison_started.elapsed().as_secs_f64()*1000.;let phase=std::time::Instant::now();let proof=pilot.verify_staging().await?;let full_pilot_fact_and_index_verification_ms=phase.elapsed().as_secs_f64()*1000.;let pilot_bytes=std::fs::metadata(&pilot_path)?.len();pilot.close().await?;derived.close().await?;
 // Reopen the independent target and compare every expected field (excluding
 // only its internal commit marker) and the complete selected source lineage.
 let reopen_started=std::time::Instant::now();let reopened=Store::open_read_only(&pilot_path)?.read_generation("isolated-composite-pilot").await?;let mut expected_hash=Sha256::new();let mut actual_hash=Sha256::new();let mut verified=0u64;let mut batch=Vec::new();
 for input in BufReader::new(File::open(&expected_path)?).lines(){batch.push(serde_json::from_str::<ImportBarRow>(&input?)?);if batch.len()==1000{verified+=verify(&reopened,std::mem::take(&mut batch),&mut expected_hash,&mut actual_hash).await?;}}
 if !batch.is_empty(){verified+=verify(&reopened,batch,&mut expected_hash,&mut actual_hash).await?;}let expected_sha=hex::encode(expected_hash.finalize());let actual_sha=hex::encode(actual_hash.finalize());ensure!(expected_sha==actual_sha&&verified==selected_rows,"pilot overlay verification differs");
 let independent_reopen_all_fields_ms=reopen_started.elapsed().as_secs_f64()*1000.;let after=pg.version().await?;ensure!(json!(after)==json!(pg_before),"pilot wrote original PG-authority generation");let result=json!({"kind":"isolated_actual_retained_prefix_composite_authority_pilot","scope":{"symbol":args[3],"source":args[4]},"capture_tail":tail.position,"raw_frames_scanned":frames.to_string(),"effective_frames":effective.to_string(),"decode_errors":decode_errors.to_string(),"decode_error_file":decode_error_path,"decode_error_sha256":legacy_import::file_hash(&decode_error_path)?,"decode_reason_counts":decode_reason_counts,"original_prefix_complete":bounds["origin_prefix_complete"],"initial_seed":"empty; imported PG facts never passed to raw decoder/reducer","affected_bar_keys":checked.to_string(),"preserved_pg":preserved.to_string(),"overlay_rows":replaced.to_string(),"unresolved_differences":unresolved.to_string(),"reason_counts":reason_counts,"complete":unresolved==0&&decode_errors==0,"comparison_file":comparison_path,"comparison_sha256":legacy_import::file_hash(&comparison_path)?,"overlay_file":overlay_path,"overlay_sha256":legacy_import::file_hash(&overlay_path)?,"independent_expected_file":expected_path,"expected_field_sha256":expected_sha,"actual_reopened_field_sha256":actual_sha,"verified_rows":verified.to_string(),"pilot_store_proof":proof,"derived_file_bytes":derived_bytes.to_string(),"pilot_file_bytes":pilot_bytes.to_string(),"projection_ms":projection_ms,"phase_ms":{"open_read_only_handles_and_scope":open_ms,"decode_reduce_and_existing_replay_fact_lookup":decode_reduce_lookup_ms,"projection_immediate_commits":projection_commit_ms,"pg_comparison_selection_and_selected_import":pg_comparison_and_selection_ms,"pg_key_lookup":pg_key_lookup_ms,"selected_immediate_import":selected_import_ms,"full_pilot_fact_and_index_verify":full_pilot_fact_and_index_verification_ms,"independent_reopen_all_fields_verify":independent_reopen_all_fields_ms},"opening_validation_scope":"schema/header checks only; opening is not a complete audit of original PG file","total_ms":started.elapsed().as_secs_f64()*1000.,"started_at":started_at,"completed_at":chrono::Utc::now(),"pg_version_before":pg_before,"pg_version_after":after,"production_terminal":false,"authority_boundary_created":false,"quote_events_reconciled":false,"limitations":"Pilot covers all source bar keys produced by the specified raw prefix, not terminal full retained quote/event reconciliation; provisional raw never downgrades imported final history; ambiguity blocks complete. Disposable facts removed after evidence and reopened verification; no activation or provider stop."});
 legacy_import::atomic_json(&report,&result)?;reopened.close().await?;pg.close().await?;capture.close_and_drain().await?;drop(temporary);println!("{}",json!({"report":report,"complete":result["complete"],"raw_frames":frames,"affected_keys":checked,"overlay":replaced,"unresolved":unresolved,"original_generation_unchanged":true}));Ok(())
}
async fn verify(store:&Store,expected:Vec<ImportBarRow>,h1:&mut Sha256,h2:&mut Sha256)->Result<u64>{
 let keys=expected.iter().map(|r|CanonicalBarKey{source_id:r.realtime_source_id.clone(),symbol:r.instrument_symbol.clone(),interval_seconds:r.interval_seconds,open_time_ns:r.open_time_ns}).collect();let(_,actual)=store.lookup_bars(keys).await?;
 for(a,b)in expected.iter().zip(actual){let b=b.context("selected pilot fact missing after reopen")?;ensure!(a.evidence==b.evidence,"reconciliation lineage lost after import");let a=semantic(json!(a));let b=semantic(json!(b));ensure!(a==b,"complete selected row differs after reopen");h1.update(serde_json::to_vec(&a)?);h1.update(b"\n");h2.update(serde_json::to_vec(&b)?);h2.update(b"\n");}Ok(expected.len() as u64)
}
