//! Source-evidenced legacy key projection. Original PostgreSQL rows are immutable.
use anyhow::{Result,Context,ensure};use serde::{Serialize,Deserialize};use serde_json::{Value,json};
use tracefang_core::{source_clock::{self,V6Label},domain::{Decimal,Instrument,AssetClass}};
use chrono::{DateTime,Utc};
#[derive(Debug,Serialize,Deserialize)]#[serde(tag="decision",rename_all="snake_case")]
pub enum Decision {Unchanged{reason:String},Shifted{row:Value,evidence:Value},Point{evidence:Value,unresolved:bool},Unresolved{reason:String}}
const EARLY_FINAL_REASON:&str="invalid_legacy_finality: finalization precedes structural bucket end; no later same-key confirmation in fixed snapshot";
fn ns(value:&Value)->Result<i64>{value.as_str().context("legacy source timestamp missing")?.parse::<DateTime<Utc>>()?.timestamp_nanos_opt().context("legacy source timestamp outside ns")}
fn number(value:&Value)->Result<String>{match value{Value::String(v)=>Ok(v.clone()),Value::Number(v)=>Ok(v.to_string()),_=>anyhow::bail!("exact legacy field missing")}}
fn same_values(a:&Value,b:&Value)->Result<bool>{for key in ["open","high","low","close","volume"]{if a[key].is_null()||b[key].is_null(){if a[key]!=b[key]{return Ok(false)}}else if Decimal::from_str_exact(&number(&a[key])?)?!=Decimal::from_str_exact(&number(&b[key])?)?{return Ok(false)}}Ok(true)}
fn flat(row:&Value)->Result<bool>{let open=Decimal::from_str_exact(&number(&row["open"])?)?;for key in ["high","low","close"]{if Decimal::from_str_exact(&number(&row[key])?)?!=open{return Ok(false)}}Ok(true)}
fn raw(row:&Value)->&Value{if row["source_raw_payload"].is_object(){&row["source_raw_payload"]}else{&row["raw_payload"]}}
fn identity(a:&Value,b:&Value)->Result<bool>{Ok(a["instrument_symbol"]==b["instrument_symbol"]&&a["provider_symbol"]==b["provider_symbol"]&&number(&a["interval_seconds"])?==number(&b["interval_seconds"])?&&ns(&a["open_time"])?==ns(&b["open_time"])?)}
pub fn describe()->Value{json!({"policy_id":source_clock::THS_V6_SHFE_END_V2,"prior_policy_id":source_clock::LEGACY_V6_OPEN_V1,"scopes":source_clock::VERIFIED_V6_SCOPES.into_iter().map(|(provider,symbol)|json!({"provider_code":provider,"instrument_symbol":symbol,"venue":"SHFE","period":"61"})).collect::<Vec<_>>(),"shift_quotes":false,"source_observed_unchanged":true,"received_and_finalized_unchanged":true,"source_point_policy":"evidenced session-start flat OHLC retained separately; other unclassified points remain unresolved"})}
/// `history` and `original` are individually resolved from the checksummed
/// source_records, never guessed from a normalized realtime source name.
pub fn project(row:&Value,history:Option<&Value>,original:Option<&Value>,source_ref:&Value,source_row_sha256:&str)->Result<Decision>{
 let provider=row["provider_symbol"].as_str().unwrap_or("");let symbol=row["instrument_symbol"].as_str().unwrap_or("");let instrument=Instrument{symbol:symbol.into(),asset_class:AssetClass::Future,venue:Some("SHFE".into()),base:None,quote:None};
 if !source_clock::verified_v6_scope(provider,&instrument)||number(&row["interval_seconds"])?!="60"{return Ok(Decision::Unchanged{reason:"outside_reviewed_v6_authoritative_minute_scope".into()})}
 let source=row["realtime_source_id"].as_str().or_else(||row["source_id"].as_str()).unwrap_or("");ensure!(source=="tonghuashun_futures","reviewed provider scope has different source identity");
 let derivation=raw(row)["derivation"].as_str().unwrap_or("");
 if derivation=="quote_event" {return Ok(Decision::Unchanged{reason:"quote_projection_uses_independent_source_point_clock".into()})}
 if derivation=="authoritative_bar_with_quote_overlay" {return Ok(Decision::Unresolved{reason:"mixed_history_and_quote_overlay_cannot_be_clock_shifted_as_one_fact".into()})}
 let history=history.or_else(||(raw(row)["channel"]=="tonghuashun_public_line_v6").then_some(row));let Some(history)=history else{return Ok(Decision::Unresolved{reason:"normalized_bar_lacks_original_v6_period61_history_lineage".into()})};
 let history_raw=raw(history);
 if history_raw["channel"]!="tonghuashun_public_line_v6"||history_raw["history_file"]!="tonghuashun_public_line_61_year"||history_raw["response_kind"]!="minute_year"||!identity(row,history)?||!same_values(row,history)?||ns(&row["received_at"])?!=ns(&history["received_at"])?{
  return Ok(Decision::Unresolved{reason:"source_record_does_not_prove_identical_complete_v6_period61_authoritative_history".into()})
 }
 let label=ns(&row["open_time"])?;let classification=source_clock::classify_v6_label(provider,&instrument,DateTime::from_timestamp_nanos(label))?;
 let base=json!({"policy_id":source_clock::THS_V6_SHFE_END_V2,"prior_policy_id":source_clock::LEGACY_V6_OPEN_V1,"provider_code":provider,"instrument_symbol":symbol,"source_label":row["open_time"],"source_label_ns":label.to_string(),"original_source_record":source_ref,"source_row_sha256":source_row_sha256,"source_row_encoding":"postgres-archive-ndjson","original_selected_state":row["state"],"original_finalized_at":row["finalized_at"],"original_observed_at":row["observed_at"],"original_received_at":row["received_at"]});
 match classification {
  V6Label::SourcePoint{reason}=>{
   let is_flat=flat(history)?;let resolved=reason=="session_start_source_point_aggregation_unverified"&&is_flat;let mut evidence=base;evidence["reason"]=json!(reason);evidence["ohlc_flat"]=json!(is_flat);evidence["original_full_row"]=row.clone();evidence["semantics"]=json!("independent_source_point; no invented canonical minute, no automatic aggregation");Ok(Decision::Point{evidence,unresolved:!resolved})
  },
  V6Label::Regular{canonical_open,interval_end}=>{
   let mut output=row.clone();output["open_time"]=json!(canonical_open);output["close_time"]=json!(interval_end);let end=interval_end.timestamp_nanos_opt().context("corrected end outside ns")?;let mut evidence=base;evidence["corrected_open_ns"]=json!(canonical_open.timestamp_nanos_opt().context("corrected open outside ns")?.to_string());evidence["corrected_end_ns"]=json!(end.to_string());evidence["restored_prior_final_state"]=json!(false);
   if let Some(prior)=row.get("_invalid_legacy_finality").filter(|v|!v.is_null()){
    let reason=prior["reason"].as_str().unwrap_or("");let Some(original)=original else{return Ok(Decision::Unresolved{reason:"prior_finality_downgrade_cannot_restore_without_original_source_record".into()})};
    if prior["original_state"]!="final"||original["state"]!="final"||reason!=EARLY_FINAL_REASON||!identity(row,original)?||!same_values(row,original)?||prior["original_finalized_at"]!=original["finalized_at"]||original["finalized_at"].is_null()||row["state"]!="provisional_authoritative"||!row["finalized_at"].is_null(){
     return Ok(Decision::Unresolved{reason:"prior_finality_downgrade_has_other_or_unproven_quality_reason".into()})
    }
    evidence["downgrade_reason"]=json!(reason);evidence["original_reported_final_state"]=original["state"].clone();evidence["original_reported_finalized_at"]=original["finalized_at"].clone();
    if ns(&original["finalized_at"])?<end{evidence["original_final_not_restored_reason"]=json!("confirmation_precedes_corrected_end");}
    else{output["state"]=json!("final");output["finalized_at"]=original["finalized_at"].clone();evidence["restored_prior_final_state"]=json!(true);}
   }
   if output["state"]=="final"&&!output["finalized_at"].is_null()&&ns(&output["finalized_at"])?<end{return Ok(Decision::Unresolved{reason:"original_confirmation_still_precedes_corrected_end".into()})}
   if (output["state"].is_null()||output["state"]=="final")&&output["finalized_at"].is_null()&&ns(&output["received_at"])?<end{output["state"]=json!("provisional_authoritative");evidence["unconfirmed_corrected_tail_preserved"]=json!(true);}
   let raw_key=if output["source_raw_payload"].is_object(){"source_raw_payload"}else{"raw_payload"};if !output[raw_key].is_object(){output[raw_key]=json!({})}output[raw_key]["source_clock_policy"]=json!(source_clock::THS_V6_SHFE_END_V2);output[raw_key]["source_label_ns"]=json!(label.to_string());output["_legacy_clock_projection"]=evidence.clone();Ok(Decision::Shifted{row:output,evidence})
  }
 }
}

#[cfg(test)]mod tests {
 use super::*;
 fn history()->Value{json!({"instrument_symbol":"AU8888","provider_symbol":"qh_au8888","source_id":"tonghuashun_futures","interval_seconds":60,"open_time":"2026-09-30T06:07:00Z","observed_at":"2026-09-30T06:07:00Z","received_at":"2026-09-30T06:07:01.123456Z","open":"0.0000000000000000000000000001","high":"2","low":"0.0000000000000000000000000001","close":"1","volume":null,"raw_payload":{"channel":"tonghuashun_public_line_v6","history_file":"tonghuashun_public_line_61_year","response_kind":"minute_year"}})}
 #[test]fn only_evidenced_authoritative_minute_moves_key_and_source_clocks_are_exact()->Result<()>{let input=history();let Decision::Shifted{row,..}=project(&input,None,None,&json!({}),"sha")?else{panic!("source proof ignored")};ensure!(row["open_time"]=="2026-09-30T06:06:00Z"&&row["close_time"]==input["open_time"]&&row["observed_at"]==input["observed_at"]&&row["received_at"]==input["received_at"]&&row["volume"].is_null()&&row["open"]==input["open"],"source clock or exact values altered");let mut quote=input.clone();quote["raw_payload"]=json!({"derivation":"quote_event"});ensure!(matches!(project(&quote,Some(&input),None,&json!({}),"sha")?,Decision::Unchanged{..}),"quote projection shifted");let mut mixed=quote.clone();mixed["raw_payload"]["derivation"]=json!("authoritative_bar_with_quote_overlay");ensure!(matches!(project(&mixed,Some(&input),None,&json!({}),"sha")?,Decision::Unresolved{..}),"mixed projection guessed");Ok(())}
 #[test]fn opening_flat_point_and_regular_flat_minute_remain_distinct()->Result<()>{let mut input=history();for key in ["open","high","low","close"]{input[key]=json!("1")}ensure!(matches!(project(&input,None,None,&json!({}),"sha")?,Decision::Shifted{..}),"ordinary flat minute became point");input["open_time"]=json!("2026-09-30T01:00:00Z");ensure!(matches!(project(&input,None,None,&json!({}),"sha")?,Decision::Point{unresolved:false,..}),"evidenced flat opening point disappeared");input["high"]=json!("2");ensure!(matches!(project(&input,None,None,&json!({}),"sha")?,Decision::Point{unresolved:true,..}),"unclassified nonflat opening passed");Ok(())}
 #[test]fn original_final_is_restored_only_with_real_original_clock_after_corrected_end()->Result<()>{let mut original=history();original["state"]=json!("final");original["finalized_at"]=json!("2026-09-30T06:07:01.123456Z");let mut input=original.clone();input["state"]=json!("provisional_authoritative");input["finalized_at"]=Value::Null;input["_invalid_legacy_finality"]=json!({"original_state":"final","original_finalized_at":original["finalized_at"],"reason":EARLY_FINAL_REASON});let Decision::Shifted{row,evidence}=project(&input,Some(&original),Some(&original),&json!({}),"sha")?else{panic!("original proven final not restored")};ensure!(row["finalized_at"]==original["finalized_at"]&&evidence["restored_prior_final_state"]==true,"new confirmation clock invented");original["finalized_at"]=json!("2026-09-30T06:06:59Z");input["_invalid_legacy_finality"]["original_finalized_at"]=original["finalized_at"].clone();let Decision::Shifted{row,evidence}=project(&input,Some(&original),Some(&original),&json!({}),"sha")?else{panic!("proven key mapping incorrectly blocked by early final")};ensure!(row["state"]=="provisional_authoritative"&&row["finalized_at"].is_null()&&evidence["original_final_not_restored_reason"]=="confirmation_precedes_corrected_end"&&evidence["original_reported_finalized_at"]==original["finalized_at"]&&evidence["original_finalized_at"].is_null(),"early final was restored or its real clock lost");input["_invalid_legacy_finality"]["reason"]=json!("another quality reason");ensure!(matches!(project(&input,Some(&original),Some(&original),&json!({}),"sha")?,Decision::Unresolved{..}),"other quality reason silently accepted");Ok(())}
}
