/** Approximate chart coordinates from authoritative evidence; never sent back as prices. */
import type {QuantSnapshot,QuantPoint} from './quantTypes';
import type {ExpertAnalysisSnapshot,ExpertIndicatorSeriesView,ExpertOverlaySeries,ExpertTrendLine,ExpertPricePattern} from './expertTypes';
import type {ExpertMarketStructureEvent} from './expertSmartMoney';
import {buildExpertAnalysisAt} from './expertAnalysis';
function number(value:unknown):number|null{if(value==null||value==='')return null;const n=Number(value);return Number.isFinite(n)?n:null;}
function seconds(value:unknown):number|null{return typeof value==='string'?Date.parse(value)/1000:null;}
function camel(value:unknown,key=''):unknown{if(value==null)return null;if(Array.isArray(value))return value.map(v=>camel(v));if(typeof value==='object')return Object.fromEntries(Object.entries(value).map(([name,v])=>[name.replace(/_([a-z])/g,(_,s:string)=>s.toUpperCase()),camel(v,name)]));if(typeof value==='string'){if(['time','start','end','formed_at','detected_at','invalidated_at'].includes(key))return seconds(value);if(/^-?\d+(?:\.\d+)?$/.test(value))return number(value);}return value;}
export function projectQuantAnalysis(snapshot:QuantSnapshot|null):ExpertAnalysisSnapshot{const empty=buildExpertAnalysisAt([],[],-1);const point=snapshot?.confirmed;if(!point)return empty;const v=point.indicators;const structure=v.structure as Record<string,unknown>|undefined;const score=number(point.composite_score)??0;const levels:ExpertAnalysisSnapshot["levels"]=[];if(structure){const support=number(structure.support),resistance=number(structure.resistance);if(support!==null)levels.push({id:"authority-support",price:support,label:"确认支撑",tone:"support",style:"dashed"});if(resistance!==null)levels.push({id:"authority-resistance",price:resistance,label:"确认压力",tone:"resistance",style:"dashed"});}
 return {...empty,asOf:seconds(point.as_of),signals:point.signals.map(s=>({id:`${s.strategy_id}:${s.as_of}`,strategyId:s.strategy_id,title:s.title,detail:`${s.state} · ${s.backtest_eligible?'可模拟方向':'上下文，排除合成/交易'}`,direction:s.direction,confidence:number(s.confidence)??0,triggeredAt:seconds(s.as_of)??0,evidence:s.evidence})),compositeScore:score,regime:point.direction>0?'trend-up':point.direction<0?'trend-down':'balanced',indicators:{...empty.indicators,macd:camel(v.macd) as ExpertAnalysisSnapshot['indicators']['macd'],kdj:camel(v.kdj) as ExpertAnalysisSnapshot['indicators']['kdj'],rsi:camel(v.rsi) as ExpertAnalysisSnapshot['indicators']['rsi'],movingAverage:camel(v.moving_average) as ExpertAnalysisSnapshot['indicators']['movingAverage'],bollinger:camel(v.bollinger) as ExpertAnalysisSnapshot['indicators']['bollinger'],nineCount:camel(v.nine_count) as ExpertAnalysisSnapshot['indicators']['nineCount'],momentum:camel(v.momentum) as ExpertAnalysisSnapshot['indicators']['momentum'],trendSlopePercent:number(v.trend_slope_percent),pocPrice:number((v.poc as Record<string,unknown>|undefined)?.price),orderFlowPressure:number((v.order_flow as Record<string,unknown>|undefined)?.pressure),volumePriceState:(v.volume_price_state??'unavailable') as ExpertAnalysisSnapshot['indicators']['volumePriceState']},levels,pricePatterns:camel(structure?.patterns??[]) as ExpertPricePattern[],marketStructureEvents:camel(v.market_structure_events??[]) as ExpertMarketStructureEvent[],valueZones:((v.value_zones??[]) as Array<Record<string,unknown>>).map((zone,index)=>({id:`authority-fvg:${zone.formed_at}:${index}`,start:seconds(zone.start)??0,end:seconds(zone.end)??0,low:number(zone.low)??0,high:number(zone.high)??0,direction:zone.direction as 'bullish'|'bearish',label:'FVG'}))};
}
export function projectQuantTrendLines(snapshot:QuantSnapshot|null):ExpertTrendLine[]{return camel(snapshot?.confirmed?.indicators.trend_lines??[]) as ExpertTrendLine[];}
export function projectQuantSeries(snapshot:QuantSnapshot|null):ExpertIndicatorSeriesView{const points=snapshot?.series??(snapshot?.confirmed?[snapshot.confirmed]:[]);if(!snapshot||!points.length)return {historyKey:null,revision:0,offset:0,length:0,visibleLength:0,changedFrom:0,bars:[],macd:{value:[],signal:[],histogram:[]},kdj:{k:[],d:[],j:[]},rsi:{value:[]}};const value=(point:Pick<QuantPoint,"indicators">,key:string,field:string)=>number((point.indicators[key] as Record<string,unknown>|null)?.[field]);const get=(key:string,field:string)=>points.map(p=>value(p,key,field)??NaN);return {historyKey:snapshot.evidence.snapshot_hash,revision:0,offset:0,length:points.length,visibleLength:points.length,changedFrom:0,bars:points.map(p=>({time:seconds(p.as_of)??0})),macd:{value:get('macd','value'),signal:get('macd','signal'),histogram:get('macd','histogram')},kdj:{k:get('kdj','k'),d:get('kdj','d'),j:get('kdj','j')},rsi:{value:points.map(p=>value(p,'rsi','value'))}};}
export function projectQuantOverlays(snapshot:QuantSnapshot|null):ExpertOverlaySeries[]{const points=snapshot?.series??[];const result:ExpertOverlaySeries[]=[];const periods=(snapshot?.evidence.parameters.ma_periods??[]) as number[];for(const [index,period]of periods.entries()){const values=points.flatMap(p=>{const ma=p.indicators.moving_average as {values:Array<{period:number;value:string|null}>}|null;const value=number(ma?.values.find(v=>v.period===period)?.value);return value==null?[]:[{time:seconds(p.as_of)??0,value}];});if(values.length)result.push({id:`ma-${period}`,label:`MA${period}`,color:['#58c4dd','#e7b65a','#a58be2','#df7185'][index%4],lineStyle:period>=120?'dashed':'solid',lineWidth:1,points:values,lastValueVisible:true});}for(const field of ['upper','middle','lower']){const values=points.flatMap(p=>{const value=number((p.indicators.bollinger as Record<string,unknown>|null)?.[field]);return value==null?[]:[{time:seconds(p.as_of)??0,value}];});if(values.length)result.push({id:`bollinger-${field}`,label:`BOLL ${field==='upper'?'上轨':field==='lower'?'下轨':'中轨'}`,color:'#7e9aca',lineStyle:'dashed',lineWidth:1,points:values,lastValueVisible:false});}return result;}
