import {useEffect,useState} from "react";
import {Play,Square,ChevronLeft,ChevronRight,RotateCcw} from "lucide-react";
import {quantApi} from "./quantApi";
import {formatQuantDecimal as money,multiplyQuantBy100} from "./quantFormat";
import {simulationReason} from "./simulationPresentation";
import {EXPERT_STRATEGIES} from "./strategyCatalog";
import type {SimulationConfig,SimulationRun,SimulationEvent,QuantMetric} from "./quantTypes";
import type {ExpertStrategyId} from "./expertTypes";
import "./quant.css";
interface Props{research?:import("./quantApi").ResearchSnapshotReference;code:string;sourceId?:string;period:string;strategies:ExpertStrategyId[];decisionAsOf?:string;applicationCursor?:string;onClose:()=>void;unit:string;onParametersChange?:(value:import("./quantTypes").QuantParameters)=>void}
function metric(value:QuantMetric|undefined,percent=false){return money(percent?multiplyQuantBy100(value?.value):value?.value,2,percent?"%":"");}
const decimalFields=[['initial_capital','初始资金'],['target_quantity','目标数量'],['multiplier','合约乘数 / 点值'],['tick_size','最小价格变动（tick）'],['fee_rate','单边费用比例'],['fixed_fee','单次固定费用'],['maximum_exposure_ratio','最大敞口倍数'],['risk_free_annual_rate','年无风险利率']] as const;
const parameterLabels:Record<string,string>={kdj_dulling_bars:"KDJ 钝化确认柱数",kdj_lower:"KDJ 下阈值",kdj_upper:"KDJ 上阈值",ma_slope_bars:"均线斜率窗口",bollinger_rank_bars:"布林宽度排名窗口",momentum_horizons:"动量窗口（逗号分隔）",momentum_weights:"动量权重（逗号分隔）",volatility_period:"波动周期",atr_period:"ATR 周期",slope_bars:"斜率窗口",slope_threshold:"斜率门槛",poc_bars:"价格密度窗口",flow_bars:"OHLC 订单流代理窗口",flow_threshold:"订单流代理门槛",fvg_bars:"FVG 回看柱数",lookback_bars:"结构回看柱数",double_minimum_separation:"双顶底最小间隔",double_maximum_separation:"双顶底最大间隔",double_confirmation_bars:"双顶底确认范围",double_price_tolerance_percent:"双顶底价格容差比例",double_price_tolerance_atr:"双顶底价格容差 ATR",minimum_pattern_height_atr:"最小结构高度 ATR",confirmation_buffer_atr:"突破确认缓冲 ATR",two_b_maximum_bars:"2B 最大范围",two_b_confirmation_bars:"2B 确认范围",two_b_minimum_breach_atr:"2B 最小穿透 ATR",two_b_maximum_breach_atr:"2B 最大穿透 ATR",invalidation_buffer_atr:"结构失效缓冲 ATR",macd_fast:"MACD 快线周期",macd_slow:"MACD 慢线周期",macd_signal:"MACD 信号周期",kdj_period:"KDJ 周期",kdj_smoothing:"KDJ 平滑周期",rsi_period:"RSI 周期",rsi_lower:"RSI 下阈值",rsi_upper:"RSI 上阈值",ma_periods:"均线周期（逗号分隔）",bollinger_period:"布林周期",bollinger_deviations:"布林标准差倍数",bollinger_percentile_window:"布林宽度排名窗口",momentum_lookbacks:"动量窗口（逗号分隔）",momentum_volatility_window:"动量波动窗口",momentum_scale:"动量归一化系数",poc_bins:"价格密度分箱数",poc_lookback:"价格密度窗口",flow_lookback:"OHLC 订单流代理窗口",volume_price_bars:"量价窗口",composite_threshold:"合成方向阈值",pivot_radius:"摆动确认半径",lookback:"结构回看范围",min_separation:"摆动最小间隔",tolerance_atr:"结构容差（ATR倍数）",breakout_atr:"突破门槛（ATR倍数）",invalidations:"失效确认柱数"};
export function QuantSimulationPanel({code,sourceId,period,strategies,decisionAsOf,applicationCursor,onClose,unit,onParametersChange,research}:Props){
 const key=`tracefang:simulation:v1:${code}:${sourceId??"route"}:${period}:${research?.research_asset??""}:${research?.research_adjustment??""}`;
 const [baseRun,setBaseRun]=useState<string|null>(null);
 const [config,setConfig]=useState<SimulationConfig|null>(null),[runs,setRuns]=useState<SimulationRun[]>([]),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[events,setEvents]=useState<SimulationEvent[]>([]),[page,setPage]=useState(0),[pages,setPages]=useState(0),[compare,setCompare]=useState<string[]>([]),[audit,setAudit]=useState<string|null>(null);
 useEffect(()=>{let disposed=false;setConfig(null);setSelected(null);setBaseRun(null);setEvents([]);setAudit(null);Promise.all([quantApi.defaults(),quantApi.runs()]).then(([defaults,result])=>{if(disposed)return;let saved:SimulationConfig|null=null;try{const raw=localStorage.getItem(key);if(raw)saved=JSON.parse(raw) as SimulationConfig;}catch{saved=null;}setConfig(saved??defaults.config);setRuns(result.runs.filter(r=>r.request.code===code&&r.request.period===period&&(!sourceId||r.request.source_id===sourceId)&&(!research||(r.request.research_asset===research.research_asset&&r.request.research_adjustment===research.research_adjustment))));}).catch(e=>{if(!disposed)setError(String(e.message??e));});return()=>{disposed=true;};},[key,code,period]);
 useEffect(()=>{if(config){try{localStorage.setItem(key,JSON.stringify(config));}catch{/* Current configuration remains usable. */}}},[config,key]);
 useEffect(()=>{const active=runs.filter(r=>r.status==='running');if(!active.length)return;let disposed=false;const timer=window.setInterval(()=>{Promise.all(active.map(r=>quantApi.status(r.id))).then(updated=>{if(!disposed)setRuns(current=>current.map(r=>updated.find(v=>v.id===r.id)??r));}).catch(e=>{if(!disposed)setError(String(e.message??e));});},750);return()=>{disposed=true;clearInterval(timer);};},[runs]);
 useEffect(()=>{if(!selected){setEvents([]);return;}let disposed=false;quantApi.events(selected,page).then(value=>{if(!disposed){setEvents(value.items);setPages(value.page_count);}}).catch(e=>{if(!disposed)setError(String(e.message??e));});return()=>{disposed=true;};},[selected,page,runs]);
 useEffect(()=>{if(config)onParametersChange?.(config.parameters);},[config?.parameters,onParametersChange]);
 const current=runs.find(r=>r.id===selected);const s=current?.summary;
 const update=(field:keyof SimulationConfig,value:string|number|boolean|null)=>setConfig(c=>c?({...c,[field]:value,assumption_provenance:{...c.assumption_provenance,[field]:`user_assumption; edited ${new Date().toISOString()}`}}):c);
 const run=async()=>{if(!config||busy)return;setBusy(true);setError(null);try{const base=runs.find(r=>r.id===baseRun);const result=await quantApi.run(base?.request??{code,source_id:sourceId,period,decision_as_of:decisionAsOf,application_cursor:applicationCursor,...research},{...config,parameters:{...config.parameters,enabled_strategies:[...strategies].sort()}},undefined,base?.id);setRuns(v=>[result,...v]);setSelected(result.id);setPage(0);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const comparisons=runs.filter(r=>compare.includes(r.id));const comparable=comparisons.length<2||comparisons.every(r=>(r.market_data_hash??r.canonical_file_sha256??r.input_hash)===(comparisons[0].market_data_hash??comparisons[0].canonical_file_sha256??comparisons[0].input_hash)&&r.config.start===comparisons[0].config.start&&r.config.end===comparisons[0].config.end&&r.summary?.execution_version===comparisons[0].summary?.execution_version);
 return <section className="quant-panel" aria-label="可配置模拟回测"><header><div><h2>模拟回测</h2><p>{code} · {period} · {unit}</p></div><button onClick={onClose} aria-label="关闭模拟回测">关闭</button></header>
 <p className="quant-note">收盘确认后于下一可用柱开盘成交。这里是价格序列账本；不包含交易所保证金、移仓或资金费。乘数、tick 和费用为本次模拟假设，请按实际合约核对。</p>
 {error?<p role="alert" className="quant-error">{error}</p>:null}
 {config?<><div className="quant-form"><label>开始时刻（UTC）<input value={config.start??""} placeholder="完整可追溯范围" onChange={e=>update('start',e.target.value||null)}/></label><label>结束时刻（UTC）<input value={config.end??""} placeholder="当前已提交截止" onChange={e=>update('end',e.target.value||null)}/></label>
 {decimalFields.map(([field,label])=><label key={field}>{label}<input inputMode="decimal" value={config[field]} onChange={e=>update(field,e.target.value)}/></label>)}
 <label>允许方向<select value={config.allowed_direction} onChange={e=>update('allowed_direction',e.target.value)}><option value="both">双向</option><option value="long_only">仅做多</option><option value="short_only">仅做空</option></select></label>
 <label>费用模式<select value={config.fee_mode} onChange={e=>setConfig(c=>c?{...c,fee_mode:e.target.value as SimulationConfig['fee_mode'],fee_rate:e.target.value==='fixed'?'0':c.fee_rate,fixed_fee:e.target.value==='percentage'?'0':c.fixed_fee}:c)}><option value="percentage">按名义金额比例</option><option value="fixed">每次固定费用</option><option value="combined">比例 + 固定费用</option></select></label>
 <label>不利滑点（tick）<input type="number" min={0} step={1} value={config.slippage_ticks} onChange={e=>update('slippage_ticks',Number(e.target.value))}/></label><label>金额结算小数位<input type="number" min={0} max={28} step={1} value={config.settlement_precision} onChange={e=>update('settlement_precision',Number(e.target.value))}/></label>
 <label>中性信号<select value={String(config.neutral_exit)} onChange={e=>update('neutral_exit',e.target.value==='true')}><option value="true">退出持仓</option><option value="false">保持持仓</option></select></label><label>期末持仓<select value={config.terminal_position} onChange={e=>update('terminal_position',e.target.value)}><option value="mark_only">按末价标记未实现损益</option><option value="settle_at_last_close">假设末价清算并计费用</option></select></label></div>
 <details className="quant-parameters"><summary>指标周期、阈值与结构参数</summary><div className="quant-form">{Object.entries(config.parameters).filter(([field])=>field!=='enabled_strategies'&&field!=='pattern').map(([field,value])=><label key={field}>{parameterLabels[field]??field}<input value={Array.isArray(value)?value.join(','):String(value)} onChange={e=>setConfig(c=>c?{...c,parameters:{...c.parameters,[field]:Array.isArray(value)?e.target.value.split(',').map(v=>typeof value[0]==='number'?Number(v.trim()):v.trim()):typeof value==='number'?Number(e.target.value):e.target.value}}:c)}/></label>)}{Object.entries(config.parameters.pattern??{}).map(([field,value])=><label key={field}>结构 · {parameterLabels[field]??field}<input value={String(value)} onChange={e=>setConfig(c=>c?{...c,parameters:{...c.parameters,pattern:{...(c.parameters.pattern as Record<string,string|number>),[field]:typeof value==='number'?Number(e.target.value):e.target.value}}}:c)}/></label>)}</div></details>
 <button className="quant-start" disabled={busy} onClick={()=>void run()}><Play size={14}/>{baseRun?"用固定数据运行新配置":"运行模拟"}</button>{baseRun?<p className="quant-note">固定使用运行 {baseRun.slice(0,8)} 已校验的完整输入，不重新读取当前行情；可以修改费用、成交假设和策略参数，开始与结束时刻保留原范围。<button onClick={()=>setBaseRun(null)}>恢复当前行情</button></p>:null}</>:<p>正在读取服务端配置…</p>}
 <div className="quant-runs">{runs.map(r=><div key={r.id}><button className={selected===r.id?'is-active':''} onClick={()=>{setSelected(r.id);setPage(0);setAudit(null);}}>{new Date(r.created_at).toLocaleTimeString()} · {r.status==='running'?`计算 ${r.processed_bars} 根`:r.status==='completed'?'已完成':r.status==='cancelled'?'已取消':r.status==='interrupted'?'已中断':'失败'}</button>{r.status==='running'?<button onClick={()=>void quantApi.cancel(r.id)} aria-label="取消模拟"><Square size={12}/></button>:null}{r.complete?<label><input type="checkbox" checked={compare.includes(r.id)} onChange={e=>setCompare(v=>e.target.checked?[...v,r.id]:v.filter(id=>id!==r.id))}/>比较</label>:null}</div>)}</div>
 {current?.error?<p className="quant-error">{simulationReason(current.error)}</p>:null}
 {s?<><p className="quant-note">{current?.semantics==='final_revision_history'?'最终修订历史模拟':'原始事件可见性回放'} · {current?.warmup_complete?'预热范围可追溯':'预热不完整，递推结果可能依赖可用起点'}。买入持有基准使用同一首个可成交点与成本设置。</p><dl className="quant-metrics">{[['净收益',money(s.return_percent,4,'%')],['末期权益',money(s.final_equity,config?.settlement_precision??4)],['已实现',money(s.realized_profit,4)],['未实现',money(s.unrealized_profit,4)],['总成本',money(s.total_cost,4)],['费用',money(s.fees,4)],['滑点损耗',money(s.slippage_cost,4)],['最大回撤',money(multiplyQuantBy100(s.maximum_drawdown),4,'%')],['净胜率',metric(s.win_rate,true)],['已平仓 / 盈 / 亏 / 零',`${s.closed_trades} / ${s.wins} / ${s.losses} / ${s.breakeven}`],['平均盈利',metric(s.average_win)],['平均亏损',metric(s.average_loss)],['利润因子',metric(s.profit_factor)],['盈亏比',metric(s.payoff_ratio)],['平均持有秒数',metric(s.average_held_seconds)],['最大敞口',money(s.maximum_exposure,4)],['拒绝 / 未成交',`${s.rejected_intents} / ${s.unfilled_intents}`],['买入持有净收益',s.benchmark?.unavailable_reason?'—':money(s.benchmark?.return_percent,4,'%')]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="quant-note">年化：{metric(s.risk_sampling.annualized_return,true)}；Sharpe：{metric(s.risk_sampling.sharpe)}。UTC 自然日的每日末期权益，样本 {s.risk_sampling.samples}，年化因子 {s.risk_sampling.annual_factor}。{simulationReason(s.risk_sampling.sharpe.unavailable_reason)} {simulationReason(s.risk_sampling.annualized_return.unavailable_reason)}</p><p className="quant-version" title={current?.input_hash}>输入版本 {current?.input_hash?.slice(0,16)} · 运行 {current?.run_hash?.slice(0,16)}</p><button onClick={()=>{if(current)void quantApi.audit(current.id).then(result=>setAudit(result.verified?`已核验完整输入与 ${result.event_count} 条账本记录`:"证据校验未通过")).catch(e=>setAudit(e.message));}}>校验已保存证据</button>{audit?<p role="status">{audit}</p>:null}<details className="quant-provenance"><summary>本次配置来源与修改记录</summary><ul>{Object.entries(s.config.assumption_provenance??{}).map(([key,value])=><li key={key}>{decimalFields.find(v=>v[0]===key)?.[1]??key}：{value.startsWith("generic_simulation_default")?"通用模拟默认值；未取得可核验合约规格":value.replace("user_assumption; edited ","用户模拟假设；修改于 ")}</li>)}</ul><p>使用带符号价格序列现金账本；不包含交易所保证金、移仓、资金费。最终修订历史不能视为当时实际可见行情。</p></details><button onClick={()=>{setConfig(s.config);setBaseRun(null);}}><RotateCcw size={12}/>载入此配置重新运行</button><button onClick={()=>{setConfig(s.config);setBaseRun(current!.id);setError(null);}}>用本次数据比较新配置</button></>:null}
 {comparisons.length>=2?<div className="quant-comparison"><strong>{comparable?'同市场数据配置比较':'输入版本、范围或成交政策不同，不能作为同数据配置比较'}</strong><table><thead><tr><th>运行</th><th>净收益</th><th>回撤</th><th>成本</th></tr></thead><tbody>{comparisons.map(r=><tr key={r.id}><td>{r.run_hash?.slice(0,8)}</td><td>{money(r.summary?.return_percent,4,'%')}</td><td>{money(multiplyQuantBy100(r.summary?.maximum_drawdown),4,'%')}</td><td>{money(r.summary?.total_cost,4)}</td></tr>)}</tbody></table></div>:null}
 {selected?<div className="quant-ledger"><header><h3>完整运行账本</h3><div><button disabled={page===0} onClick={()=>setPage(v=>v-1)} aria-label="上一页"><ChevronLeft size={14}/></button><span>{page+1} / {Math.max(1,pages)}</span><button disabled={page+1>=pages} onClick={()=>setPage(v=>v+1)} aria-label="下一页"><ChevronRight size={14}/></button></div></header><table><thead><tr><th>记录</th><th>时刻</th><th>数量 / 价格</th><th>费用 / 权益</th></tr></thead><tbody>{events.map((event,index)=><tr key={`${page}:${index}`}><td>{{fill:'成交',trade:'平仓损益',equity:'权益',rejected:'拒绝',unfilled:'未成交',decision:'确认决策'}[event.type as 'fill']}{event.value.terminal_valuation_assumption?' · 期末假设':''}</td><td>{String(event.value.executed_at??event.value.closed_at??event.value.at??event.value.decision_at??(event.value.intent as Record<string,unknown>)?.decision_at??'')}</td><td>{event.type==='fill'?`${money(String(event.value.delta_quantity),4)} @ ${money(String(event.value.fill_price),8)}`:event.type==='trade'?money(String(event.value.net_profit),4):event.type==='equity'?money(String(event.value.quantity),4):event.type==='decision'?<details><summary>{Number(event.value.direction)>0?'多头':Number(event.value.direction)<0?'空头':'中性'} · 合成 {money(String(event.value.composite_score),4)}</summary><ul>{(event.value.signals as {strategy_id:string;direction:string;state:string;evidence:string[]}[]??[]).map(signal=><li key={signal.strategy_id}>{EXPERT_STRATEGIES.find(item=>item.id===signal.strategy_id)?.name??signal.strategy_id} · {{bullish:'多头',bearish:'空头',neutral:'中性'}[signal.direction as 'neutral']??signal.direction} · {{ready:'已确认',warming:'预热中',unavailable:'不可用',context:'上下文',context_unavailable:'上下文缺失'}[signal.state as 'ready']??signal.state}<p>{signal.evidence.join('；')}</p></li>)}</ul></details>:simulationReason(String(event.value.reason??''))}</td><td>{event.type==='fill'?`费 ${money(String(event.value.fee),4)} · 现金 ${money(String(event.value.cash_after),4)}`:event.type==='equity'?money(String(event.value.equity),4):'—'}</td></tr>)}</tbody></table><small>分页只控制展示，不截断计算范围。滑点已计入成交价，成本展示不会再次扣现金。</small></div>:null}
 </section>;
}
