import {mergeQuantSnapshotDelta,QuantDeltaBaseMismatch,type QuantSnapshotDelta} from "./quantDelta.ts";
import type { QuantSnapshot, QuantParameters, SimulationConfig, SimulationRun, SimulationEvent } from "./quantTypes";
class QuantHttpError extends Error {readonly status:number;constructor(message:string,status:number){super(message);this.status=status;}}
async function api<T>(path:string,payload?:unknown,signal?:AbortSignal):Promise<T>{const response=await fetch(path,{method:payload===undefined?"GET":"POST",headers:payload===undefined?undefined:{"Content-Type":"application/json"},body:payload===undefined?undefined:JSON.stringify(payload),signal});const text=await response.text();let value;try{value=JSON.parse(text);}catch{value={detail:text||'研究服务暂时不可用'};}if(!response.ok)throw new QuantHttpError(value.detail??"研究服务暂时不可用",response.status);return value as T;}
export interface QuantBuildProgress{state:"building"|"ready"|"cancelled"|"failed";job_id:string;processed_bars:string;phase?:string;error?:string;snapshot?:QuantSnapshot;snapshot_delta?:QuantSnapshotDelta;chart_basis_hash?:string;long_poll?:boolean}
export type ResearchSnapshotReference={research_snapshot_id:string;research_adjustment:string;research_asset:string};
export type SnapshotInput={code:string;source_id?:string;period:string;parameters?:QuantParameters;decision_as_of?:string;application_cursor?:string}&Partial<ResearchSnapshotReference>;
function pause(signal?:AbortSignal,ms=350):Promise<void>{return new Promise((resolve,reject)=>{const aborted=()=>{clearTimeout(timer);reject(new DOMException("Aborted","AbortError"));};const timer=setTimeout(()=>{signal?.removeEventListener('abort',aborted);resolve();},ms);if(signal?.aborted)aborted();else signal?.addEventListener('abort',aborted,{once:true});});}
async function snapshot(input:SnapshotInput,signal?:AbortSignal,onProgress?:(value:QuantBuildProgress)=>void,base?:QuantSnapshot|null):Promise<QuantSnapshot>{let value:QuantBuildProgress|QuantSnapshot;let attempt=0;
 for(;;){try{value=await api<QuantBuildProgress|QuantSnapshot>("/api/expert/quant/snapshot",input,signal);break;}catch(error){if(!(error instanceof QuantHttpError)||error.status!==429||attempt++>=180)throw error;onProgress?.({state:'building',job_id:'',processed_bars:'0',phase:'waiting_capacity'});await pause(signal,Math.min(5000,attempt*1000));}}
 if('evidence' in value)return value;for(;;){if(signal?.aborted)throw new DOMException("Aborted","AbortError");onProgress?.(value);if(value.state==='ready'&&value.snapshot)return {...value.snapshot,chart_basis_hash:value.chart_basis_hash};if(value.state==='ready'&&value.snapshot_delta){try{return mergeQuantSnapshotDelta(base??null,value.snapshot_delta,value.chart_basis_hash,input);}catch(error){if(!(error instanceof QuantDeltaBaseMismatch))throw error;value=await api<QuantBuildProgress>(`/api/expert/quant/snapshot/jobs/${encodeURIComponent(value.job_id)}`,undefined,signal);if(!value.snapshot)throw new Error('指标缓存已变化，请刷新完整快照');continue;}}if(value.state!=='building')throw new Error(value.error??'指标计算已停止');value=await api<QuantBuildProgress>(`/api/expert/quant/snapshot/jobs/${encodeURIComponent(value.job_id)}?wait_ms=1000${base?.chart_basis_hash?`&known_chart_basis_hash=${encodeURIComponent(base.chart_basis_hash)}`:""}`,undefined,signal);if(value.state==='building'&&!value.long_poll)await pause(signal);}}
export const quantApi={
 defaults:()=>api<{config:SimulationConfig;parameters:QuantParameters;calculation_version:string}>("/api/expert/quant/defaults"),snapshot,
 cancelSnapshot:(id:string)=>api<{cancel_requested:boolean}>(`/api/expert/quant/snapshot/jobs/${encodeURIComponent(id)}/cancel`,{}),
 replaySnapshot:(session_id:string,cursor:string,parameters:QuantParameters,signal?:AbortSignal)=>api<QuantSnapshot>("/api/replay/quant/snapshot",{session_id,cursor,parameters},signal),
 run:(input:SnapshotInput,config:SimulationConfig,expected_input_hash?:string,base_run_id?:string)=>api<SimulationRun>("/api/expert/simulations",{input,config,expected_input_hash,base_run_id}),
 runs:()=>api<{runs:SimulationRun[]}>("/api/expert/simulations"),status:(id:string)=>api<SimulationRun>(`/api/expert/simulations/${encodeURIComponent(id)}`),
 cancel:(id:string)=>api<{cancel_requested:boolean}>(`/api/expert/simulations/${encodeURIComponent(id)}/cancel`,{}),
 events:(id:string,page:number)=>api<{items:SimulationEvent[];page:number;page_count:number;has_next:boolean}>(`/api/expert/simulations/${encodeURIComponent(id)}/events?page=${page}`),
 audit:(id:string)=>api<{verified:boolean;event_count:string;canonical_file_sha256:string}>(`/api/expert/simulations/${encodeURIComponent(id)}/audit`),
};
