import type {
  ExpertStrategyDefinition,
  ExpertStrategyId,
  ExpertStrategyReference,
} from "./expertTypes";

const REFERENCES: Record<string, ExpertStrategyReference> = {
  technicalPatterns: {
    title: "Foundations of Technical Analysis: Computational Algorithms, Statistical Inference, and Empirical Implementation",
    publisher: "National Bureau of Economic Research",
    url: "https://www.nber.org/papers/w7613",
    note: "以可复现算法识别价格形态，并强调形态信息必须通过条件分布和样本外检验评估。",
  },
  movingAverageRules: {
    title: "Simple Technical Trading Rules and the Stochastic Properties of Stock Returns",
    publisher: "The Journal of Finance / Wiley",
    url: "https://onlinelibrary.wiley.com/doi/10.1111/j.1540-6261.1992.tb04681.x",
    note: "经典移动平均与交易区间突破检验；研究对象并非黄金，不能直接外推收益率。",
  },
  dataSnooping: {
    title: "Data-Snooping, Technical Trading Rule Performance, and the Bootstrap",
    publisher: "The Journal of Finance / Wiley",
    url: "https://doi.org/10.1111/0022-1082.00163",
    note: "用于约束参数搜索、幸存者偏差与多重试验；所有技术规则都应做样本外和现实检验。",
  },
  taLibFunctions: {
    title: "TA-Lib Function Reference",
    publisher: "TA-Lib",
    url: "https://ta-lib.org/functions/",
    note: "指标公式、输入输出与开源实现索引，用于交叉核对 MA、MACD、Stochastic 与 BBANDS 口径。",
  },
  macdReference: {
    title: "Moving Average Convergence/Divergence (MACD)",
    publisher: "TA-Lib Technical Analysis Documentation",
    url: "https://ta-lib.github.io/ta-doc/indicator/MACD.htm",
    note: "Gerald Appel 的 MACD 参考与 TA-Lib 实现入口；预测有效性仍需独立验证。",
  },
  stochasticReference: {
    title: "Stochastic Oscillator Slow (STOCH)",
    publisher: "TA-Lib Technical Analysis Documentation",
    url: "https://ta-lib.github.io/ta-doc/indicator/STOCH.htm",
    note: "给出 %K、%D 的标准公式；KDJ 的 J 线属于在此基础上的扩展。",
  },
  rsiOfficial: {
    title: "Relative Strength Index (RSI)",
    publisher: "TA-Lib",
    url: "https://ta-lib.org/functions/rsi.html",
    note: "Wilder RSI 的官方函数说明与实现入口；14 期和 70/30 是常用默认值，不是黄金反转胜率结论。",
  },
  twoBReference: {
    title: "2B or Not 2B: A Classic Rule Revisited",
    publisher: "Wiley / Trader Vic on Commodities",
    url: "https://onlinelibrary.wiley.com/doi/10.1002/9781119196792.ch4",
    note: "2B 原始规则描述创新高/低后无法延续并回到旧极值内侧；本系统的 ATR 阈值和时间窗是可审计的工程实现。",
  },
  bollingerOfficial: {
    title: "A Complete Explanation of Bollinger Bands",
    publisher: "John Bollinger",
    url: "https://www.bollingerbands.com/bollinger-bands",
    note: "创作者对动态波动带和相对高低位置的原始说明，明确建议结合其他指标确认。",
  },
  demarkSequential: {
    title: "DeMARK Sequential Indicator",
    publisher: "DeMARK Analytics / Symbolik",
    url: "https://help.symbolik.com/hc/en-us/articles/37782822323987-DeMARK-Sequential-Indicator",
    note: "官方产品文档给出 Setup 9 的连续收盘比较；本策略只实现九计数，不冒充完整 Sequential。",
  },
  timeSeriesMomentum: {
    title: "Time Series Momentum",
    publisher: "Journal of Financial Economics / author manuscript",
    url: "https://w4.stern.nyu.edu/facdir/lpederse/papers/TimeSeriesMomentum.pdf",
    note: "在含商品期货的多资产样本中研究跨期限趋势延续；并不等同单一黄金品种的实时胜率承诺。",
  },
  orderFlowImpact: {
    title: "The Price Impact of Order Book Events",
    publisher: "Journal of Financial Econometrics / Oxford University Press",
    url: "https://doi.org/10.1093/jjfinec/nbt003",
    note: "一手盘口研究显示订单流不平衡比总成交量更稳健；OHLC 代理不得标成真实 OFI。",
  },
  stopLossCascades: {
    title: "Stop-Loss Orders and Price Cascades in Currency Markets",
    publisher: "Federal Reserve Bank of New York",
    url: "https://www.newyorkfed.org/research/staff_reports/sr150.html",
    note: "外汇研究发现止损单可能聚集并放大价格运动；它不能证明某根黄金影线代表机构扫单或真实止损位置。",
  },
  cboeVolatilityMethodology: {
    title: "Volatility Index Methodology for Selected Broad-Based Index, Equity and ETF Volatility Indices",
    publisher: "Cboe Global Indices",
    url: "https://cdn.cboe.com/api/global/us_indices/governance/Volatility_Index_Methodology_Selected_Broad_Based_Index_Equity_and_ETF_Volatility_Indices.pdf",
    note: "定义 VIX 类指数及 Cboe Gold ETF Volatility Index（GVZ）的 30 日预期波动率口径。",
  },
  cftcOpenInterest: {
    title: "Commitments of Traders Explanatory Notes",
    publisher: "U.S. Commodity Futures Trading Commission",
    url: "https://www.cftc.gov/MarketReports/CommitmentsofTraders/ExplanatoryNotes/index.htm",
    note: "官方定义持仓量及报告覆盖范围；总持仓量不能直接解释为单边多空方向。",
  },
  futuresDepth: {
    title: "Price Volatility, Trading Volume, and Market Depth: Evidence from Futures Markets",
    publisher: "Journal of Financial and Quantitative Analysis / Cambridge University Press",
    url: "https://www.cambridge.org/core/journals/journal-of-financial-and-quantitative-analysis/article/abs/price-volatility-trading-volume-and-market-depth-evidence-from-futures-markets/19A7F7A79CAFC48F03758DD57A5965C7",
    note: "区分预期与意外成交活动，并研究持仓量作为市场深度代理与波动的关系。",
  },
};

function defineStrategy(definition: ExpertStrategyDefinition): ExpertStrategyDefinition {
  return definition;
}

export const EXPERT_STRATEGIES: ExpertStrategyDefinition[] = [
  defineStrategy({
    id: "structure",
    name: "价格结构",
    shortName: "结构",
    description: "因果摆动高低点、W/M 与 2B 失败突破",
    dataSource: "OHLC",
    evidenceMode: "native",
    details: {
      role: "structure",
      horizon: "当前图表周期的近 30–160 根已收盘 Bar",
      principle: "将 W 底、M 顶和 2B 失败突破转换为只依赖当时已完成 K 线的机械事件。摆动点必须等右侧 Bar 完成后才可使用；形态在收盘确认前不产生方向信号。",
      formula: [
        "趋势斜率：对最近最多 30 根收盘价做 OLS，斜率除以均价后换算为 %/Bar。",
        "摆动点：某 Bar 的高/低值分别是左右各 2 根 Bar 的局部极值。",
        "W/M：相邻同类摆动相隔 5–80 Bar；两端容差取价格均值 0.4% 与 0.5 ATR14 的较大者，颈线高度至少 1 ATR14。",
        "第二极值确认后最多 40 Bar 内，W 底收盘高于颈线 + 0.05 ATR14、M 顶收盘低于颈线 - 0.05 ATR14 后确认。",
        "2B：价格越过已确认旧极值 0.05–1.25 ATR14，并在穿越当根或其后 3 根内收盘回到旧极值内侧 0.05 ATR14。",
      ],
      parameters: ["回归窗口 30", "结构扫描窗口 160", "摆动半径 2", "W/M 间隔 5–80", "W/M 第二极值确认后最多 40 Bar 确认", "W/M 两端容差 max(0.4%, 0.5 ATR)", "2B 参考摆动后最多扫描 30 Bar，回收窗 3 Bar"],
      signalRules: [
        "斜率 > 0.004%/Bar 判为结构偏多；< -0.004%/Bar 判为结构偏空。",
        "只在 W/M 颈线或 2B 回收由当前已完成 Bar 确认时输出一次方向事件；历史确认形态继续用于图层审计，不重复触发。",
        "W 底与 2B 底部偏多，M 顶与 2B 顶部偏空；形态方向优先于同期斜率背景。",
        "最近有效摆动低点/高点分别输出结构支撑/压力。",
      ],
      requiredFields: ["open", "high", "low", "close", "open_time", "Bar 完结状态"],
      suitableRegimes: ["有连续摆动点的趋势转折或宽幅震荡", "W/M 颈线突破", "旧高低点的快速失败突破"],
      boundaryConditions: [
        "少于 4 根 Bar 时不计算斜率；样本不足时结构位退化为窗口极值；ATR14 不足时使用当时可得真实波幅均值。",
        "局部极值确认需要右侧 Bar，实时端只使用已经完成确认的摆动点。",
        "当前 W/M 不要求先验趋势，2B 的回收本身就是确认；这比部分交易书籍的自由裁量定义更机械，但也更窄。",
        "Lo 等人的形态研究来自美国股票，2B 来源是交易规则章节；两者都不是黄金样本外预测率证据。",
      ],
      invalidation: ["候选在确认前若先收盘越过固定失效位，立即作废且后续不得复活", "多方形态确认后收盘低于第二低点/穿越低点 - 0.25 ATR14；空方镜像", "支撑/压力被有效收盘穿越", "历史 Bar 修订会触发因果重算并可能改变尚未成交的最新事件"],
      references: [REFERENCES.technicalPatterns, REFERENCES.twoBReference, REFERENCES.dataSnooping],
      validation: "W/M 与 2B 已进入因果逐 Bar evaluator、结构图层和实验回测；已覆盖摆动右侧确认、形态去重与截止时点测试，仍需黄金分品种/周期 walk-forward、成本和阈值稳定性报告。",
      version: "structure-wm-2b-v2",
      compositeEligible: true,
      backtestEligible: true,
    },
  }),
  defineStrategy({
    id: "ma-structure",
    name: "MA 均线结构与动态支撑",
    shortName: "MA结构",
    description: "多空排列、斜率共振与 60/250MA 周期支撑",
    dataSource: "收盘价 + 当前周期",
    evidenceMode: "native",
    details: {
      role: "direction",
      horizon: "20/60/120/250 根当前周期已收盘 Bar；日、周等周期分别计算",
      principle: "均线只总结当前周期的历史成本与方向。短、中、长均线有序且同向时定义趋势结构；价格回踩中长期均线后收回可作为动态支撑候选，但必须以波动容差和收盘确认约束。",
      formula: [
        "SMA_n(t) = (C_t + … + C_{t-n+1}) / n。",
        "多头排列：可用均线按 MA20 > MA60 > MA120 > MA250 有序；空头排列反向。",
        "支撑距离：|Close - MA_n| / ATR14；回踩后收盘回到均线上方才算多方确认。",
      ],
      parameters: ["MA20/60/120/250", "ATR14 归一化", "60/250MA 接触容差按 ATR 自适应", "方向确认只使用最后一根 final Bar"],
      signalRules: [
        "排列方向与 MA60、MA250 斜率一致时输出趋势确认。",
        "日线 MA250 通常称为年线；周线 MA60、MA250 与年线 MA60、MA250 是各自周期统计，必须分别解释。",
        "价格接近 MA60/250 后收回且未有效跌破，输出动态支撑；反向规则输出压力。",
      ],
      requiredFields: ["close", "high", "low", "open_time", "period_id", "至少 250 根同周期已收盘 Bar"],
      suitableRegimes: ["中期和长期单边趋势", "趋势中的首次或第二次有序回踩"],
      boundaryConditions: [
        "不足 60/250 根时对应均线必须显示为样本不足，不允许缩短窗口替代。",
        "日线 MA250 约覆盖一个交易年；若切到周线或年线，MA250 就需要 250 个周/年样本，不允许借用日线值。",
        "横盘中均线反复缠绕会产生频繁假信号；跨品种价格尺度必须用 ATR 或百分比归一化。",
      ],
      invalidation: ["排列被收盘交叉破坏", "MA60/250 斜率反向", "价格超过容差并连续收盘在支撑另一侧"],
      references: [REFERENCES.movingAverageRules, REFERENCES.taLibFunctions, REFERENCES.dataSnooping],
      validation: "已进入逐 Bar evaluator、合成评分和实验回测，并补充 250 Bar 预热、周期隔离与无未来函数测试；正式交易前仍需按品种和周期做 walk-forward。",
      version: "ma-structure-v1",
      compositeEligible: true,
      backtestEligible: true,
    },
  }),
  defineStrategy({
    id: "macd",
    name: "MACD 动量",
    shortName: "MACD",
    description: "12/26 EMA 与 9 周期信号线",
    dataSource: "收盘价",
    evidenceMode: "native",
    details: {
      role: "confirmation",
      horizon: "约 26–60 根当前周期 Bar",
      principle: "比较快慢 EMA 的差值及其信号线，描述趋势动量的方向和变化；柱值不是未来收益概率。",
      formula: ["DIF = EMA12(close) - EMA26(close)", "DEA = EMA9(DIF)", "Histogram = DIF - DEA"],
      parameters: ["快线 12", "慢线 26", "信号线 9", "EMA 使用因果递推"],
      signalRules: ["柱值 > 0 偏多，< 0 偏空", "DIF/DEA 交叉只作确认", "绝对柱值相对价格越大，当前实现置信度越高但有上限"],
      requiredFields: ["close", "open_time", "至少 26 根 Bar"],
      suitableRegimes: ["方向性行情", "与结构或均线同向的动量确认"],
      boundaryConditions: ["震荡区会反复交叉", "不同价格尺度需归一化比较", "当前参数未经黄金各周期独立优化"],
      invalidation: ["柱值穿越零轴反向", "DIF 与 DEA 方向反转", "历史 Bar 修订改变 EMA 链"],
      references: [REFERENCES.macdReference, REFERENCES.taLibFunctions, REFERENCES.dataSnooping],
      validation: "已进入现有逐 Bar evaluator、composite 和实验回测；待补黄金分周期样本外与成本后稳定性验证。",
      version: "macd-12-26-9-v1",
      compositeEligible: true,
      backtestEligible: true,
    },
  }),
  defineStrategy({
    id: "kdj",
    name: "KDJ 摆动",
    shortName: "KDJ",
    description: "9 周期随机值与平滑动量",
    dataSource: "OHLC",
    evidenceMode: "native",
    details: {
      role: "exhaustion",
      horizon: "9–30 根当前周期 Bar",
      principle: "用收盘价在近期高低区间中的位置衡量短期摆动，再平滑得到 K/D；J 放大 K 与 D 的差异，用来提示极端而不是单独预测反转。",
      formula: ["RSV = 100 × (Close - LowestLow9) / (HighestHigh9 - LowestLow9)", "K、D 为 RSV 的递推平滑", "J = 3K - 2D"],
      parameters: ["观察窗口 9", "K/D 平滑 3", "J 高位 100、低位 0 仅作风险提示"],
      signalRules: ["K > D 输出短线偏多，K < D 输出偏空", "J 超过 100 或低于 0 标为极端区", "极端区信号降低置信度并要求结构确认"],
      requiredFields: ["high", "low", "close", "open_time", "至少 9 根 Bar"],
      suitableRegimes: ["区间震荡", "趋势回撤后的节奏确认"],
      boundaryConditions: ["强趋势中可长期钝化", "KDJ 的 J 线不是 TA-Lib STOCH 标准输出", "高低区间为零时必须稳定处理"],
      invalidation: ["K/D 再次反向交叉", "J 极端但价格继续沿趋势扩展", "结构方向与摆动信号冲突"],
      references: [REFERENCES.stochasticReference, REFERENCES.taLibFunctions, REFERENCES.dataSnooping],
      validation: "已进入现有逐 Bar evaluator、composite 和实验回测；极端区目前只降低解释强度，尚无独立反转胜率结论。",
      version: "kdj-9-3-3-v1",
      compositeEligible: true,
      backtestEligible: true,
    },
  }),
  defineStrategy({
    id: "rsi",
    name: "Wilder RSI 动量",
    shortName: "RSI",
    description: "14 期 Wilder 平滑与 30/70 极端区回收",
    dataSource: "收盘价",
    evidenceMode: "native",
    details: {
      role: "confirmation",
      horizon: "至少 15 根当前周期已收盘 Bar；14 个价格变化量完成种子",
      principle: "RSI 比较 Wilder 平滑后的平均上涨与平均下跌幅度。30/70 只表示当前窗口动量处于相对极端区；本策略只在指标从极端区收回时产生候选方向，不把持续超买/超卖直接当作反转。",
      formula: [
        "Gain_t = max(Close_t-Close_{t-1}, 0)，Loss_t = max(Close_{t-1}-Close_t, 0)。",
        "首个 AvgGain/AvgLoss 是 14 个变化量的简单平均；之后 Avg_t = (13×Avg_{t-1}+Current)/14。",
        "RSI = 100 - 100/(1 + AvgGain/AvgLoss)；涨跌都为 0 时固定为 50。",
      ],
      parameters: ["Wilder 周期 14", "超卖阈值 30", "超买阈值 70", "递推只使用当时已知收盘价"],
      signalRules: [
        "上一根 RSI <= 30 且当前 > 30，输出超卖区回收的偏多候选。",
        "上一根 RSI >= 70 且当前 < 70，输出超买区回落的偏空候选。",
        "RSI 仍在 30 以下或 70 以上时只显示极端状态，方向置信度为 0，不进入合成评分。",
      ],
      requiredFields: ["close", "open_time", "至少 15 根连续已收盘 Bar"],
      suitableRegimes: ["区间边缘的动量回收", "高周期方向明确时的低周期回撤结束确认", "与 W/M、2B 或结构突破同向的二次确认"],
      boundaryConditions: [
        "强趋势中 RSI 可以长时间钝化在极端区，阈值穿越不是价格止跌/止涨保证。",
        "当前版本没有实现 RSI 背离，也不要求价格突破摆动位；详情页不得将回收事件写成已确认反转。",
        "历史 close 修订会从受影响位置重算 Wilder 链；种子窗口内修订从头重建。",
      ],
      invalidation: ["回收后 RSI 再次进入原极端区且价格延续原方向", "价格结构给出相反 BOS/2B", "数据缺口或源切换破坏连续递推口径"],
      references: [REFERENCES.rsiOfficial, REFERENCES.dataSnooping],
      validation: "已实现 Wilder14 递推、flat-input=50、种子预热、历史修订与因果截止测试，并进入逐 Bar evaluator/composite/实验回测；仍需黄金各周期 walk-forward、成本和阈值稳定性检验。",
      version: "rsi-wilder-14-v1",
      compositeEligible: true,
      backtestEligible: true,
    },
  }),
  defineStrategy({
    id: "bollinger",
    name: "布林带波动结构",
    shortName: "BOLL",
    description: "20 周期中轨、标准差通道与带宽压缩/扩张",
    dataSource: "收盘价",
    evidenceMode: "native",
    details: {
      role: "confirmation",
      horizon: "20–60 根当前周期 Bar",
      principle: "用滚动均值和标准差给出价格相对位置与波动状态；触及上下轨不是自动反转信号，趋势中沿轨运行同样常见。",
      formula: ["Middle = SMA20(close)", "Upper/Lower = Middle ± 2 × rollingStd20(close)", "%B = (Close - Lower) / (Upper - Lower)", "Bandwidth = (Upper - Lower) / Middle"],
      parameters: ["窗口 20", "标准差倍数 2", "总体/样本标准差口径必须固定", "压缩阈值用历史带宽分位数而非硬编码价格"],
      signalRules: ["收盘突破上/下轨且带宽扩张，作为趋势延续确认", "触轨后回到带内且动量背离，才作为均值回归候选", "带宽低分位只提示蓄势，不预测突破方向"],
      requiredFields: ["close", "open_time", "至少 20 根 Bar"],
      suitableRegimes: ["波动率从压缩向扩张切换", "有方向确认的趋势延续或区间均值回归"],
      boundaryConditions: ["标准差带不是正态置信区间", "跳空和厚尾会频繁越轨", "不同周期带宽分位数不可混用"],
      invalidation: ["突破后收盘迅速回到中轨另一侧", "带宽未扩张且动量不确认", "滚动样本不足或存在长缺口"],
      references: [REFERENCES.bollingerOfficial, REFERENCES.taLibFunctions, REFERENCES.dataSnooping],
      validation: "已进入逐 Bar evaluator、合成评分和实验回测；标准差口径、120 Bar 带宽分位窗与扩张阈值已固定，仍需按黄金周期做样本外与成本检验。",
      version: "bollinger-20-2-v1",
      compositeEligible: true,
      backtestEligible: true,
    },
  }),
  defineStrategy({
    id: "nine-count",
    name: "九转计数（Setup 9）",
    shortName: "九转",
    description: "连续 9 根收盘相对第 4 根之前的趋势耗竭提示",
    dataSource: "收盘价",
    evidenceMode: "native",
    details: {
      role: "exhaustion",
      horizon: "至少 13 根当前周期已收盘 Bar",
      principle: "连续比较当前收盘与四根之前收盘，计数到 9 时提示趋势可能过度延伸。本实现含 Setup 9 及第 8/9 根的简化 perfected 判定，但不实现或声称完整的 DeMARK Sequential Countdown。",
      formula: ["Buy setup：连续 9 根 Close_t < Close_{t-4}", "Sell setup：连续 9 根 Close_t > Close_{t-4}", "任一不满足即重置对应连续计数"],
      parameters: ["回看间隔 4", "连续计数 9", "第 8/9 根相对第 6/7 根极值的 perfected 子条件", "只在最后一根 final Bar 上确认"],
      signalRules: ["完成向下九计数只提示潜在下跌耗竭", "完成向上九计数只提示潜在上涨耗竭", "必须叠加结构、波动或动量确认后才可形成方向观点"],
      requiredFields: ["close", "open_time", "至少 13 根无序列缺口的已收盘 Bar"],
      suitableRegimes: ["单边走势后段的风险提示", "与支撑压力或背离共同出现的耗竭场景"],
      boundaryConditions: ["不是完整 Sequential，不包含 countdown 13 或 TDST；perfected 仅实现可审计的 Setup 子条件", "强趋势可能在 9 后继续延伸", "休市压缩不等于 Bar 缺失，真正缺失 Bar 应中断或降级"],
      invalidation: ["计数完成后价格继续创新高/低且无确认反转", "中间比较条件被破坏", "Bar 修订改变连续序列"],
      references: [REFERENCES.demarkSequential, REFERENCES.dataSnooping],
      validation: "仅作为视觉耗竭标记；不直接进入 composite，也不在未定义进出场前生成回测交易。",
      version: "nine-count-4x9-v1",
      compositeEligible: false,
      backtestEligible: false,
    },
  }),
  defineStrategy({
    id: "momentum-ensemble",
    name: "多尺度趋势动量集成",
    shortName: "MOM×",
    description: "跨短中长窗口的方向投票与波动归一化",
    dataSource: "收盘价",
    evidenceMode: "native",
    details: {
      role: "direction",
      horizon: "20/60/120 根当前周期 Bar",
      principle: "避免依赖单一窗口，将多个因果回报方向按波动归一化后集成；只有多数窗口一致且风险不过度扩张时才输出方向。",
      formula: ["Momentum_n = Close_t / Close_{t-n} - 1", "RealizedVol20 = std(log(C_t/C_{t-1}))", "Scaled_n = tanh(Momentum_n / (RealizedVol20 × √n))", "Score = 0.5×Scaled20 + 0.3×Scaled60 + 0.2×Scaled120（按可用权重重标）"],
      parameters: ["窗口 20/60/120", "20 根对数收益实现波动率", "tanh 限幅", "权重 0.5/0.3/0.2"],
      signalRules: ["多尺度同向且综合分超过阈值时确认趋势", "窗口分裂时输出中性", "极高波动下只降置信度，不扩大仓位建议"],
      requiredFields: ["close", "open_time", "至少 21 根；完整组合需要 121 根同周期 Bar"],
      suitableRegimes: ["持续性趋势", "跨周期方向一致且波动受控"],
      boundaryConditions: ["研究证据覆盖多资产期货，不代表单一黄金源的实时效果", "窗口和阈值必须在训练集固定后走样验证", "反转和震荡期会滞后"],
      invalidation: ["多数窗口方向分裂", "短中期动量穿越零且结构同步转弱", "波动急升导致归一化后分数失真"],
      references: [REFERENCES.timeSeriesMomentum, REFERENCES.dataSnooping],
      validation: "已进入逐 Bar evaluator、合成评分和实验回测，并要求至少两个期限同向；上线前仍需完成黄金/白银分层 walk-forward、成本和参数稳定区间检验。",
      version: "momentum-ensemble-v1",
      compositeEligible: true,
      backtestEligible: true,
    },
  }),
  defineStrategy({
    id: "multi-timeframe",
    name: "跨周期趋势差异",
    shortName: "周期张力",
    description: "1小时/日线/周线方向对齐、分歧与回撤候选",
    dataSource: "同品种同来源的 1h + 1d + 1w 已收盘 K 线",
    evidenceMode: "conditional",
    details: {
      role: "risk-context",
      horizon: "短周期 1h、中周期 1d、长周期 1w；每档固定使用最近 20 根合格 final Bar",
      principle: "分别计算每个周期的因果趋势摘要，再比较方向是否一致。长周期上涨而短周期下跌只表示顺大势回撤的候选观察窗口；必须等待短周期 RSI 回收、W/2B 或结构确认，不能把周期分歧本身当作入场保证。",
      formula: [
        "Up：Close > SMA5 > SMA20 且 20-Bar return > 0；Down 为完全镜像；其余为 Mixed。",
        "Aligned：三个可比周期同为 Up 或同为 Down；Divergent：至少同时出现 Up 与 Down；否则 Mixed。",
        "共同信息截止为 decision_as_of；每档只纳入 final 且 bucket_end、finalized_at、observed_at、received_at 都不晚于该时刻的 Bar。",
      ],
      parameters: ["profile swing-1h-1d-1w-v1", "周期映射 1h/1d/1w", "SMA5/SMA20", "20-Bar 回报", "每档至少 20 根 final Bar"],
      signalRules: [
        "长周期 Up、短周期 Down 显示多头回撤候选；长周期 Down、短周期 Up 显示空头反弹候选。",
        "三个周期同向只显示趋势一致背景；任何一档不足 20 根时整体比较为 not_comparable。",
        "候选必须由当前交易周期的价格结构/RSI 另行确认，不直接贡献方向 composite。",
      ],
      requiredFields: ["同 instrument_symbol 与 source_id", "1h/1d/1w OHLC", "Bar state/finalized_at", "bucket_end/observed_at/received_at", "decision_as_of"],
      suitableRegimes: ["高周期趋势中的低周期回撤或反弹", "需要区分背景方向与执行节奏的波段观察", "周期同步趋势的风险确认"],
      boundaryConditions: [
        "20 根是工程窗口，不是黄金最优参数；1h、1d、1w 的 20 根代表不同钟表长度。",
        "各周期最后一根自然结束于不同时间；共同 as-of 只保证信息可得性，不保证 bucket 同步。",
        "历史修订快照未保留：decision_as_of 之后收到的修订会保守排除，不能重建当时旧版本。",
        "时序动量研究覆盖多资产和较低频率，不能外推为本 1h/1d/1w 规则的预测率。",
      ],
      invalidation: ["长周期方向转为 mixed 或反向", "短周期回撤继续演变为高周期结构破坏", "任一周期数据不足、非 final 或来源不一致", "短周期确认事件失效"],
      references: [REFERENCES.timeSeriesMomentum, REFERENCES.movingAverageRules, REFERENCES.dataSnooping],
      validation: "已实现 final-only as-of join、三周期摘要、对齐/分歧/不可比状态与 API 测试；当前仅作上下文和机会候选，不进入 composite，也未接入多序列因果回测。",
      version: "multi-timeframe-trend-v1",
      compositeEligible: false,
      backtestEligible: false,
    },
  }),
  defineStrategy({
    id: "auto-trend",
    name: "智能趋势线",
    shortName: "趋势线",
    description: "因果摆动锚点、触碰质量与失效淡化",
    dataSource: "OHLC + ATR",
    evidenceMode: "native",
    details: {
      role: "structure",
      horizon: "最近 80–240 根当前周期 Bar",
      principle: "从已确认摆动点中生成候选直线，以触碰次数、穿越惩罚、时间跨度和斜率稳定性评分；失效后保留审计记录并淡化，而不是回看式删除。",
      formula: ["Line(t) = p1 + (p2-p1) × (t-t1)/(t2-t1)", "Touch error = |price-line| / ATR14", "Quality = touches + span reward - breaches - recency decay"],
      parameters: ["摆动半径 2", "最少 2 个锚点，第三次触碰进入 tested", "接触容差 0.28 ATR", "连续 2 根越线或单根超过 0.75 ATR 判失效"],
      signalRules: ["上升支撑线与下降压力线分开评分", "只用当时已经确认的锚点，不回填历史信号", "收盘有效穿越后状态转 invalid，线条低透明度虚线保留并记录原因"],
      requiredFields: ["open", "high", "low", "close", "open_time", "ATR 可计算", "Bar 完结状态"],
      suitableRegimes: ["摆动结构清晰的趋势", "多次触碰但尚未有效穿越的通道"],
      boundaryConditions: ["极短线和跳空会造成大量候选线", "锚点确认具有天然延迟", "自动评分不能替代人工选择，也不能使用未来触碰回写早期置信度"],
      invalidation: ["收盘超过 ATR 容差并满足连续确认", "新摆动结构使旧线失去覆盖", "数据修订导致锚点消失；需记录 revision 而非静默删除"],
      references: [REFERENCES.technicalPatterns, REFERENCES.dataSnooping],
      validation: "作为系统视觉标注运行，已补逐 Bar 截止点一致性与失效状态测试；当前不进入方向合成或交易回测，避免把事后触碰质量回写成历史信号。",
      version: "auto-trend-v1",
      compositeEligible: false,
      backtestEligible: false,
    },
  }),
  defineStrategy({
    id: "smart-money",
    name: "流动性与结构代理",
    shortName: "结构代理",
    description: "OHLC 可观测的扫位回收、BOS 与 CHOCH 共振",
    dataSource: "已收盘 OHLC + ATR14（价格行为代理）",
    evidenceMode: "proxy",
    details: {
      role: "structure",
      horizon: "最近最多 220 根当前周期已收盘 Bar；摆动半径 2",
      principle: "把市场上常称为“聪明钱”的部分价格行为拆成可证伪事件：影线越过已确认摆动位后收回、以及收盘突破摆动位。它只能描述价格与流动性位置代理，不识别订单所有者、机构意图、真实止损或订单簿流动性。",
      formula: [
        "Sweep proxy：影线越过最近已确认摆动位 0.08–1.50 ATR14，并收盘回到该位内侧至少 0.02 ATR14。",
        "BOS/CHOCH：上一收盘尚未越过阈值，当前收盘越过最近摆动高/低 0.12 ATR14；若突破前摆动趋势相反则标 CHOCH，否则标 BOS。",
        "方向候选只在同方向、仍有效的 Sweep 后 8 根 Bar 内，最新 Bar 再确认 BOS/CHOCH 时产生。",
      ],
      parameters: ["摆动半径 2", "扫描窗口 220", "Sweep 0.08–1.50 ATR", "收回缓冲 0.02 ATR", "结构突破缓冲 0.12 ATR", "Sweep→BOS/CHOCH 最多 8 Bar", "事件失效缓冲 0.50 ATR"],
      signalRules: [
        "单独 Sweep、BOS 或 CHOCH 只在图上显示印记，不产生策略方向分数。",
        "同向有效 Sweep 与最新 Bar 的 BOS/CHOCH 同时满足才输出低置信度结构候选。",
        "BOS/CHOCH/SWEEP 失效后保留锚点并淡化，便于审计；不会回看式删除。",
      ],
      requiredFields: ["open", "high", "low", "close", "open_time", "连续已收盘 Bar", "可计算 ATR14"],
      suitableRegimes: ["明确旧高/旧低附近的失败突破", "Sweep 后快速发生同向结构切换", "与高周期方向一致的低周期确认"],
      boundaryConditions: [
        "OHLC 不含订单身份、撤单、主动买卖方向或盘口深度，因此策略名和 UI 必须保留“代理”表述。",
        "纽约联储证据来自外汇止损聚集，订单流论文来自真实限价簿；都不能证明本黄金 OHLC 事件由机构造成。",
        "当前 CHOCH 依据最近两组高低摆动的方向分类，不等同所有 SMC/ICT 流派的 protected high/low 定义。",
        "Sweep 与 2B 可能描述相近 Bar；当前各自展示，未完成事件簇去重前不得叠加计分。",
      ],
      invalidation: ["多方事件后收盘跌破参考位 - 0.50 ATR14；空方镜像", "Sweep 与结构切换间隔超过 8 Bar", "摆动结构因历史 Bar 修订而改变", "获得真实 L2/订单流后应另建 native evidence，不回填本代理"],
      references: [REFERENCES.stopLossCascades, REFERENCES.orderFlowImpact, REFERENCES.technicalPatterns, REFERENCES.dataSnooping],
      validation: "已实现因果摆动、Sweep/BOS/CHOCH、事件失效与同向共振测试，并在系统图层展示；因代理尚无黄金样本外效果且 2B 去重未完成，当前不进入 composite 或回测交易。",
      version: "smart-money-structure-proxy-v1",
      compositeEligible: false,
      backtestEligible: false,
    },
  }),
  defineStrategy({
    id: "vix-gvz",
    name: "VIX / GVZ 风险与黄金波动",
    shortName: "VIX·GVZ",
    description: "股票风险波动与黄金隐含波动的跨市场背景",
    dataSource: "Cboe VIX + GVZ 外部时间序列",
    evidenceMode: "conditional",
    details: {
      role: "risk-context",
      horizon: "日线为主；约 30 日隐含波动预期",
      principle: "VIX 描述股票市场期权隐含波动，GVZ 描述 GLD 期权隐含波动。二者用于区分风险环境和黄金自身波动溢价，不把 VIX 上升机械等同金价上涨。",
      formula: ["使用 Cboe 公布的日终指数值，不在客户端仿造 VIX/GVZ", "Percentile252 = count(history ≤ latest) / N × 100，N 最多 252", "VIX 与 GVZ 分别展示，不把二者差值伪装成已验证交易信号"],
      parameters: ["官方 EOD 历史 CSV", "最多 252 个已发布交易日", "各指数独立 as-of", "缺失与过期状态显式展示"],
      signalRules: ["VIX 与 GVZ 同升：风险和贵金属波动共同扩张", "GVZ 独升：黄金特异波动背景", "只调整置信度/风险提示，不直接给出金价方向"],
      requiredFields: ["VIX EOD close", "GVZ EOD close", "各自 as_of 与 source URL", "历史不足时分位显示不可用"],
      suitableRegimes: ["宏观风险切换", "事件前后隐含波动重定价"],
      boundaryConditions: ["VIX 与 GVZ 的标的和交易时段不同", "指数是期权隐含波动，不是方向指标", "节假日、延时源和跨时区不得前向填充为实时事实"],
      invalidation: ["任一序列过期或缺失", "对齐使用了尚未发布的收盘值", "把风险背景错误转换为单边方向"],
      references: [REFERENCES.cboeVolatilityMethodology],
      validation: "已接入官方可下载 EOD 历史并显示最新值与 252 日分位；不接 Cboe 延迟报价轮询，不进入 composite 或回测，条件收益仍待 as-of 样本外验证。",
      version: "vix-gvz-context-v1",
      compositeEligible: false,
      backtestEligible: false,
    },
  }),
  defineStrategy({
    id: "volume-open-interest",
    name: "期货量价持仓结构",
    shortName: "量·仓",
    description: "沪金/沪银加权量价与交易所持仓参与度背景",
    dataSource: "SHFE 加权 OHLC + volume + open_interest",
    evidenceMode: "conditional",
    details: {
      role: "confirmation",
      horizon: "当前 SHFE 延迟快照 + 当前图表最近 24 根成交量 Bar",
      principle: "成交量反映当期交易活动，持仓量反映尚未平仓合约总量。当前版本分别展示加权 K 线量价窗口与 SHFE 真实到期合约聚合量仓；没有同口径 ΔOI 时不做四象限方向判断。",
      formula: ["Volume_total = Σ 各真实 AU/AG 到期合约当日成交量", "OI_total = Σ 各真实 AU/AG 到期合约当前持仓", "量价窗口沿用 24 Bar 前后等长均量与价格变化比较", "只有全部合约都有同口径 ΔOI 时才允许聚合，否则 ΔOI = null"],
      parameters: ["SHFE 约 30 分钟延迟快照", "仅聚合真实到期合约", "成交量与持仓量均为单边手数", "量价窗口 24 Bar"],
      signalRules: ["有可比 Bar 成交量时显示量价确认或背离", "总 OI 只描述市场参与规模，不推断净多或净空", "当前快照缺完整 ΔOI 时明确显示不可用，不补 0、不与实时价格强行配对"],
      requiredFields: ["加权 K 线 open/high/low/close/volume", "SHFE 合约 volume/openinterest", "contract_code", "observed_at 与 declared delay"],
      suitableRegimes: ["沪金加权 AU8888、沪银加权 AG8888", "交易所延迟量仓口径可审计的参与度观察"],
      boundaryConditions: ["加权序列的合约切换会制造虚假 OI 跳变", "夜盘和日盘必须归到 SHFE 交易日", "持仓量多空总额相等，不能从总量推断净多头"],
      invalidation: ["volume/open_interest 任一缺失或口径变化", "真实合约集合异常或上游时点倒退", "延迟持仓量与实时价格错误混用"],
      references: [REFERENCES.cftcOpenInterest, REFERENCES.futuresDepth],
      validation: "当前只作为延迟的交易所市场参与度上下文；在取得逐时点 OI、连续合约换月元数据和因果历史前，不进入 composite 或回测。",
      version: "volume-open-interest-v1",
      compositeEligible: false,
      backtestEligible: false,
    },
  }),
  defineStrategy({
    id: "fair-value",
    name: "公允价值缺口",
    shortName: "FVG",
    description: "三根 K 线价格失衡区间",
    dataSource: "OHLC",
    evidenceMode: "native",
    details: {
      role: "structure",
      horizon: "最近 120 根当前周期 Bar",
      principle: "用第一根与第三根 K 线影线之间未重叠的价格区间标记快速位移留下的区域。它是 OHLC 形态，不是真实订单簿失衡，也不保证回补。",
      formula: ["Bullish FVG：Low_t > High_{t-2}，区间 [High_{t-2}, Low_t]", "Bearish FVG：High_t < Low_{t-2}，区间 [High_t, Low_{t-2}]"],
      parameters: ["三 Bar 结构", "扫描 120 根", "图上最多保留最近 4 个区间", "当前版本未按 ATR 过滤最小宽度"],
      signalRules: ["多方缺口作为下方潜在反应区，空方缺口作为上方潜在反应区", "只作位置证据；需要趋势、量价或收盘反应确认"],
      requiredFields: ["high", "low", "open_time", "至少 3 根 Bar"],
      suitableRegimes: ["快速位移后的回撤观察", "与结构支撑压力重合的区域"],
      boundaryConditions: ["场外现货 OHLC 不是集中订单簿", "小缺口可能只是采样与流动性噪声", "研究引用不直接验证 FVG 回补概率"],
      invalidation: ["价格完整穿越区间且未反应", "数据补齐后缺口消失", "源或周期切换改变 Bar 边界"],
      references: [REFERENCES.technicalPatterns, REFERENCES.orderFlowImpact, REFERENCES.dataSnooping],
      validation: "已进入现有逐 Bar evaluator、composite 和实验回测；当前固定置信度较低，尚无黄金专属回补统计。",
      version: "fvg-3bar-v1",
      compositeEligible: true,
      backtestEligible: true,
    },
  }),
  defineStrategy({
    id: "poc-proxy",
    name: "POC 价格密度",
    shortName: "POC≈",
    description: "由 K 线区间与可用总量构造，非逐价成交分布",
    dataSource: "OHLC + 可用总量",
    evidenceMode: "proxy",
    details: {
      role: "structure",
      horizon: "最近最多 240 根当前周期 Bar",
      principle: "把每根 K 线的可用总量均匀分摊到其覆盖价位桶，选择权重最高桶中心作为价格密度中心。该值不是交易所逐价成交量 POC。",
      formula: ["价格窗口分为 32 个等宽桶", "每根 Bar 权重 = volume/覆盖桶数；无 volume 时权重退化为 1", "POC≈ = 最大累计权重桶中心"],
      parameters: ["窗口 240", "桶数 32", "无成交量时等权退化"],
      signalRules: ["收盘在 POC≈ 上方偏多、下方偏空", "只作为相对价值位置，低置信度进入合成"],
      requiredFields: ["high", "low", "close", "volume 可选"],
      suitableRegimes: ["区间成交密集区观察", "有交易所成交量的期货数据"],
      boundaryConditions: ["非逐笔、非逐价分布", "桶宽随窗口极值变化会移动", "现货无量时只剩价格占用密度"],
      invalidation: ["窗口极值变化导致桶重划", "切换数据源后量口径不同", "真实 Volume Profile 与代理明显冲突"],
      references: [REFERENCES.orderFlowImpact, REFERENCES.dataSnooping],
      validation: "已进入现有 composite 与实验回测，但明确以代理低置信度运行；不得在 UI 去掉 ≈ 标识。",
      version: "poc-proxy-32x240-v1",
      compositeEligible: true,
      backtestEligible: true,
    },
  }),
  defineStrategy({
    id: "order-flow-proxy",
    name: "3D 订单流代理",
    shortName: "FLOW≈",
    description: "以实体/振幅/总量估计压力，等待 L2 与主动买卖方向",
    dataSource: "OHLC + 可用总量",
    evidenceMode: "proxy",
    details: {
      role: "confirmation",
      horizon: "最近 32 根当前周期 Bar",
      principle: "用 K 线实体在全振幅中的位置近似买卖压力，并以成交量平方根加权。它不含 bid/ask、撤单、主动方向或盘口深度，因此不能命名为真实订单流。",
      formula: ["barPressure = clamp((Close-Open)/(High-Low), -1, 1)", "weight = sqrt(volume)，无量时为 1", "FLOW≈ = Σ(barPressure×weight)/Σweight"],
      parameters: ["窗口 32", "多空阈值 ±0.08", "成交量平方根权重"],
      signalRules: ["FLOW≈ > 0.08 偏多，< -0.08 偏空", "只作低权重确认，不能覆盖真实结构或量仓证据"],
      requiredFields: ["open", "high", "low", "close", "volume 可选"],
      suitableRegimes: ["没有 L2 但 K 线连续的临时代理", "与价格结构同向的确认"],
      boundaryConditions: ["实体方向不等于主动买卖方向", "无法观测撤单和盘口深度", "原论文的 OFI 证据不能转嫁给 OHLC 代理"],
      invalidation: ["获得真实 OFI/L2 后应替换代理", "高低价异常或零振幅", "源切换造成成交量口径断裂"],
      references: [REFERENCES.orderFlowImpact],
      validation: "已进入现有 composite 与实验回测但固定低置信度；代理有效性尚未在黄金数据上独立证明。",
      version: "order-flow-proxy-v1",
      compositeEligible: true,
      backtestEligible: true,
    },
  }),
  defineStrategy({
    id: "volume-price",
    name: "量价确认",
    shortName: "量价",
    description: "仅在数据源提供可比较成交量时启用",
    dataSource: "OHLC + 成交量",
    evidenceMode: "conditional",
    details: {
      role: "confirmation",
      horizon: "最近 24 根当前周期 Bar，前后等长窗口",
      principle: "比较前后两个等长窗口的平均成交量变化与价格方向是否一致，用作趋势参与度确认。只描述当前源的总量口径。",
      formula: ["VolumeMove = mean(volume_late) - mean(volume_early)", "PriceMove = Close_last - Close_first", "同号或成交量变化绝对比例 < 4% 记为 confirming，否则 diverging"],
      parameters: ["窗口 24", "至少 12 根有效 volume", "量变化中性带 4%"],
      signalRules: ["价格与量同向变化输出确认", "方向相反输出背离", "volume 不足输出 unavailable，置信度为 0"],
      requiredFields: ["close", "volume", "open_time", "至少 12 根正成交量 Bar"],
      suitableRegimes: ["交易所成交量口径稳定的期货", "突破或趋势延续的参与度确认"],
      boundaryConditions: ["场外现货 tick volume 与交易所手数不可混用", "聚合周期改变会改变成交量分布", "总量与收益可能同步由新信息驱动，非单向因果"],
      invalidation: ["成交量字段缺失/归零", "数据源或合约口径切换", "最新窗口量价关系反向"],
      references: [REFERENCES.futuresDepth, REFERENCES.cftcOpenInterest],
      validation: "已实现条件 evaluator；有量时进入 composite/实验回测，无量时明确 unavailable 且不贡献分数。",
      version: "volume-price-24-v1",
      compositeEligible: true,
      backtestEligible: true,
    },
  }),
];

export const DEFAULT_EXPERT_STRATEGIES: ExpertStrategyId[] = [
  "structure",
  "ma-structure",
  "macd",
  "kdj",
  "rsi",
  "bollinger",
  "nine-count",
  "momentum-ensemble",
  "multi-timeframe",
  "auto-trend",
  "smart-money",
  "fair-value",
  "poc-proxy",
];

const STRATEGY_BY_ID = new Map<ExpertStrategyId, ExpertStrategyDefinition>(
  EXPERT_STRATEGIES.map((strategy) => [strategy.id, strategy]),
);

export function strategyById(id: ExpertStrategyId): ExpertStrategyDefinition {
  const strategy = STRATEGY_BY_ID.get(id);
  if (!strategy) throw new Error(`Unknown expert strategy: ${id}`);
  return strategy;
}
